### ISSUE TITLE
Ascpect Too Long Warning

### ISSUE THREAD

**Issue by nlietzow** [yangheng95/PyABSA#105]
Hi, 

I have recently updated to 1.2.12 and since then I am getting lots of "Aspect Too Long" warnings. 

Even when running the demo script demo (PyABSA\demos\aspect_term_extraction\train_atepc_english.py), I get lots of warnings like:
`
Aspect Too Long Warning to check -> aspect: my suggestion is to eat family style because you ' ll want to try the other dishes is too long, text:  my suggestion is to eat family style because you ' ll want to try the other dishes ., polarity: Neutral"
` 

Looking at the warning, I was wondering if maybe just the warning is wrong or if really the whole sentence is considered to be an aspect? Then something would be going wrong with reading in the input correctly.

Do you have any idea why this is happening? Is it safe to ignore the warning?

Thanks a lot!
Niclas

**Comment by yangheng95** [comment]
You can ignore it if there is no further exception. However It is unsafe to ignore the warnings. The whole sentence or a long text should not be the aspect. And sometimes this warning indicates the preprocessing error in the dataset.

**Comment by nlietzow** [comment]
Thanks for the reply. Do you think it's a preprocessing error in this case? I am just running the demo script without any modifications and no custom dataset.

The whole sentence is ``"my suggestion is to eat family style because you ' ll want to try the other dishes"`` from demos/integrated_datasets/laptop14/Restaurants_Train.xml.seg.atepc. The aspects are ``"eat family style"`` and ``"dishes"``. However, according to the warning the whole sentence has been read in as an aspect, right? 

And I get lots of these warnings before the model training starts, but no other exception.

**Comment by yangheng95** [comment]
Some errors exist in published dtasets. Unfortuantely, I am not available for fixing these errors. I add this warning to help users to find the potential prepcessing errors in thier custom dataset.

**Comment by b00033811** [comment]
I am facing the same error. I've noticed that if the aspect is at the end of the sentence, this error occurs.
@nlietzow did you find a solution?

**Comment by kerolzeeq** [comment]
> I am facing the same error. I've noticed that if the aspect is at the end of the sentence, this error occurs. @nlietzow did you find a solution?

Now that you mention it, yes it happens if the aspect is at the end of a sentence. I'm also facing the same error and it tends to ignore the training sample.

@b00033811 I'm sorry that I couldn't find the solution too but I was wondering if you have?

**Comment by kerolzeeq** [comment]
> > I am facing the same error. I've noticed that if the aspect is at the end of the sentence, this error occurs. @nlietzow did you find a solution?
> 
> Now that you mention it, yes it happens if the aspect is at the end of a sentence. I'm also facing the same error and it tends to ignore the training sample.
> 
> @b00033811 I'm sorry that I couldn't find the solution too but I was wondering if you have?

I managed to find the problem causing the warning to popup. Check #220
