### ISSUE TITLE
About the inferring of aspect polarity

### ISSUE THREAD

**Issue by ccscute** [yangheng95/PyABSA#11]
Your work is great！
However, when I run the polarity judgment, the following error occurred：
```
opt.seed = int(opt.state_dict_path.split('seed')[1])
AttributeError: 'Namespace' object has no attribute 'state_dict_path'
```
I have put the saved state-dicts in the infer_dataset directory, and modified the model_name and dataset.

**Comment by ccscute** [comment]
I put all the generated state_dict into it, or each data set only needs to put the last one?

**Comment by yangheng95** [comment]
The script indentified the file name contained 'acc' as state-dict, see https://github.com/yangheng95/LC-ABSA/blob/c945a94e0f86116c5578245aa9ad36c46c7b9c4a/apc_infer.py#L149

And each file only need one.

**Comment by yangheng95** [comment]
Tell me if any problem continues

**Comment by ccscute** [comment]
To match your example, I used dataset 'car'
like this 
![图片](https://user-images.githubusercontent.com/68651940/89771205-8ab22580-db32-11ea-806d-0b7cb96f06d2.png)But this problem still exists

**Comment by ccscute** [comment]
```
{
  "config1": {
    "model_name": "lcf_bert",
    "dataset": "car",
    "optimizer": "adam",
    "learning_rate": 0.00002,
    "dropout": 0.1,
    "l2reg": 0.00001,
    "num_epoch": 5,
    "batch_size": 4,
    "logdir": "logs",
    "pretrained_bert_name": "bert-base-chinese",
    "use_dual_bert": false,
    "use_bert_spc": true,
    "max_seq_len": 80,
    "SRD": 5,
    "sigma": 0.5,
    "lcf": "cdw",
    "lce": true,
    "lcp": true,
    "exp_rounds": 1
  }
}
```

**Comment by yangheng95** [comment]
Seems there is no seed in the file name. It is recommended to use the auto-generated state-dict file.
e.g. lce_bert_car_acc72.98_seed0seed

**Comment by ccscute** [comment]
I am sorry to trouble you with such a simple question.
I can run it successfully, thank you!
