### ISSUE TITLE
dealing with unbalanced dataset

### ISSUE THREAD

**Issue by jackie930** [yangheng95/PyABSA#115]
hi, 

i am focusing on a problem with my own dataset, and i've got two problems that seeking help here:
1) for atepc task, we are dealing with ate task as a sequence labeling task, meaning that we labeling ‘BIO' and convert it to a 6-class classification, for some dataset, it may have imbalanced problem, that contains too much ’O', do you have suggestions on how to deal with it?
2) For a task that not only need to extract term and aspect, but also need to classfy terms into various classes,
 any suggestions on solution?

thanks!

**Comment by yangheng95** [comment]
Hi,
Unfortunately, I have no suggestion about Q1, but you can try use APC model to process those text which have no aspect term, as the performance of APC is better (the MTL only improves ATE performance as our previous experiments)

**Comment by jackie930** [comment]
> Hi, Unfortunately, I have no suggestion about Q1, but you can try use APC model to process those text which have no aspect term, as the performance of APC is better (the MTL only improves ATE performance as our previous experiments)

ok - i will try that.

and for Q2, i have an idea that can we refer to NER task, which we are not label each token I-ASPECT, but I- CATE1, I-CATE2, ..., which should be ok to deal with a TABSA task, do you have any idea on whether we should implement this feature?

**Comment by yangheng95** [comment]
Hi, maybe I will rafactor the ner label which means we can use customized label according to our dataset, depends on my schedule.

**Comment by yangheng95** [comment]
> > Hi, Unfortunately, I have no suggestion about Q1, but you can try use APC model to process those text which have no aspect term, as the performance of APC is better (the MTL only improves ATE performance as our previous experiments)
> 
> ok - i will try that.
> 
> and for Q2, i have an idea that can we refer to NER task, which we are not label each token I-ASPECT, but I- CATE1, I-CATE2, ..., which should be ok to deal with a TABSA task, do you have any idea on whether we should implement this feature?

I notice it is a simple update, so I release 1.3.12 which support custmizing IOB labels
