### ISSUE TITLE
unable to load sentiment model for english

### ISSUE THREAD

**Issue by trinanjan12** [yangheng95/PyABSA#119]
Hi @yangheng95 
1. I am trying to run apc model from the example [demo script](https://github.com/yangheng95/PyABSA/blob/release/demos/aspect_polarity_classification/sentiment_inference.py)
2. I am on latest version 1.6
3. Not able to load english model(fast_lsa_s_acc_85.18_f1_82.72.zip)

here is a https://colab.research.google.com/drive/1PKVE4grlDFIMwvp1f_-di9pvmE85pbgx?authuser=1#scrollTo=TekWHOZ4BylS
Please help me with this!

**Comment by yangheng95** [comment]
Hi, 
Thank you, currently I can not reproduce this error in my environment, however I will fix it as soon as I can.

**Comment by yangheng95** [comment]
I have no other develop environment but I modfify the code to advoid error like this, as it is a fatal error, please update to 1.6.2 to test and tell me if it works. Thank you @trinanjan12

**Comment by yangheng95** [comment]
Here is my test result:
https://colab.research.google.com/drive/1PKVE4grlDFIMwvp1f_-di9pvmE85pbgx?usp=sharing

**Comment by yangheng95** [comment]
Here is my test result:
![image](https://user-images.githubusercontent.com/51735130/144870584-eec9b9b6-52c1-4164-9c63-764f8e684984.png)

**Comment by trinanjan12** [comment]
hi @yangheng95 , thanks for the quick turn around, with 1.6.2 I am able to load the english apc model. However as I was testing the output classes, I can see that the model is not good with negative classes,(not good as in I was not able to generate any sentiment that is negative). It is prediecting '-999' for both 'negative and unknown examples. I am attaching a screenshot. 
this is my reference sentiment map sentiment_map = {0: 'Negative', 1 : 'Neutral', 2: 'Positive', -999: ''} [this is just for reference]
. However it is good with postive and neutral classes

![Screenshot from 2021-12-06 21-13-14](https://user-images.githubusercontent.com/27989326/144876918-ab145ecd-a20f-487a-b6fa-751a709b3843.png)

**Comment by yangheng95** [comment]
I see, I will check it

**Comment by yangheng95** [comment]
Please try 1.6.7

**Comment by trinanjan12** [comment]
with 1.6.7 I am getting this following error on the infer method 
'APCConfigManager' object has no attribute 'label_to_index
![Screenshot from 2021-12-07 08-18-00](https://user-images.githubusercontent.com/27989326/144957033-c7478533-b1cb-4fa2-bd11-a3cd2aecdeff.png)'

**Comment by yangheng95** [comment]
please restart your colab notebook and remove cached dataset and downloaded checkpoint if any. Here is my test result, https://colab.research.google.com/drive/1LOBc_yJupqk3HIK9kYW0_RCAWkn73lt0#scrollTo=ePMnFPUnN4Iw&line=8&uniqifier=1

**Comment by yangheng95** [comment]
When update pyabsa, restart colab first to apply the change

**Comment by trinanjan12** [comment]
yes with 1.6.8 I am able to get the sentiment correctly, thank you @yangheng95
