### ISSUE TITLE
configs in experiments_apc.json

### ISSUE THREAD

**Issue by ghost** [yangheng95/PyABSA#12]
Hello,
I really appreciate your work here! But I have some questions that I want to clarify:

1- Is there a way to just run a specific config in the experiments_apc.json file?

2- Where can I specify the exact seed I want?

3- After training a model how can I use it on a new unlabeled data to extract aspects and their corresponding sentiments also with the polarity of these sentiments?

**Comment by yangheng95** [comment]
Hi, 

Thank you for your interest in this repo, I will give you some advice.

1. Maybe you mean to train the model in a specific config, in that case, you can leave only one configuration in the experiments_apc.json

2. No distinct method is provided to select the random seed, find the optimal seed by experiments.

3. Refactor the data with the format of the provided dataset. Perhaps you need to label some reviews to tain and fit on your dataset if your text is not English or not related to the SemEval 2014.

**Comment by ghost** [comment]
Thanks a lot! I will try those out.
