### ISSUE TITLE
error on sentiment classification for english model(1.6.2)

### ISSUE THREAD

**Issue by trinanjan12** [yangheng95/PyABSA#120]
Hi @yangheng95 
I am testing the sentiment classification for english model(1.6.2). I found one error, if the same aspect word is there in multiple position but only of them has been tagged for inference, the pipeline breaks.
here is a screen shot

![Screenshot from 2021-12-06 23-46-04](https://user-images.githubusercontent.com/27989326/144900415-bf646c20-6fe2-4484-9633-3996f65b31fc.png)

**Comment by yangheng95** [comment]
This error shoud gone in 1.6.3

**Comment by trinanjan12** [comment]
yes with 1.6.8 I am able to get the results correctly, thank you @yangheng95
