### ISSUE TITLE
unexpected behaviour while loading model

### ISSUE THREAD

**Issue by trinanjan12** [yangheng95/PyABSA#121]
hi @yangheng95  I am not able to load the model sometimes, Not sure if this is the right way to do it. Please check the screen shot for details
![Screenshot from 2021-12-09 01-19-02](https://user-images.githubusercontent.com/27989326/145274683-e05180b0-5dd2-480e-8aba-7cdd56de0115.png)

**Comment by trinanjan12** [comment]
To be more specific, Is it possible that I can download the zip file, unzip it, and load from that unzipped checkpoint. Or does it have to be in a specific path. Something like checkpoint/checkpointname.

**Comment by yangheng95** [comment]
Yes, you can down load the checkpoint using the id (url) and load the zipped file or unzipped folder.
It seems the googledrivedownloader dosent work now, not sure if it is a temporary issue.

**Comment by yangheng95** [comment]
just like this: 
![image](https://user-images.githubusercontent.com/51735130/145277581-918790d3-b7fe-49bd-b863-f1dae91cb8c5.png)

**Comment by trinanjan12** [comment]
I used gdown package for downloading
If you see the second example of my screenshot, I'm loading from checkpoint zip file. Any idea what is that error with seek? @yangheng95

**Comment by yangheng95** [comment]
It is a unfully download error, ie., broken checkpoint. Please try download manually

**Comment by trinanjan12** [comment]
I'll check and confirm that once tomorrow. Thanks you for the quick turn around

**Comment by yangheng95** [comment]
If you can handle the downlaoding problem using gdown, would you please share your idea which may help me improve the download stability?

**Comment by trinanjan12** [comment]
sure thing, hope this helps you

import gdown
url = '
https://drive.google.com/u/0/uc?id=1vAp1zQW3YNKzyjj8FfJdderBZYfOYhvw&export=download
'
output = 'fast_lsa_s_acc_84.9_f1_82.11.zip'
gdown.download(url, output, quiet=False)

**Comment by yangheng95** [comment]
Check it and found the downloaded checkpoint is 70kb only, I think that is the problem

**Comment by trinanjan12** [comment]
I think sometimes it doesn't download correctly. I just tried manually
downloading the model and loading it. I'm able to load the model without
the seek error.
While manually downloading also I had to download twice, I think the
problem is from Google drive side

**Comment by trinanjan12** [comment]
issue is resolved . thank you @yangheng95
