### ISSUE TITLE
Where to define path for saving checkpoint it always goes to current dir. Can't save it directly on gdrive

### ISSUE THREAD

**Issue by cnarte** [yangheng95/PyABSA#122]

**Comment by yangheng95** [comment]
It saves the model in "checkpoints/" dir, do you set checkpoint_save_mode=1 or other model !=0?

**Comment by yangheng95** [comment]
See here for usage of path_to_save arg in 1.6.13a0:
https://github.com/yangheng95/PyABSA/blob/30b23cd3d8e0f56a24d40275ae1fb92fe0ae4be0/pyabsa/functional/trainer/trainer.py#L62
