### ISSUE TITLE
LCF: A Local Context Focus Mechanism for Aspect-Based Sentiment Classification

### ISSUE THREAD

**Issue by karimmahalian** [yangheng95/PyABSA#123]
Hi,

First, thank u for this great repo. I have a question about this paper: LCF: A Local Context Focus Mechanism for Aspect-Based Sentiment Classification

Why u used a dense layer over the concatenation of local context and global context features before feeding it into an MHSA layer ?

![Screen Shot 2021-12-23 at 6 26 48 AM](https://user-images.githubusercontent.com/90440701/147192366-6049a335-974f-42d0-ad9c-e5a40cab7fb1.png)

Thank u in advance

**Comment by yangheng95** [comment]
Was trying to fuse the features, and a large dim (2xhidden_dim) seems to be inadequate in feature fusing.
And it is not inevitable, you can make your attempts to improve
