### ISSUE TITLE
no attribute 'sep_indices'

### ISSUE THREAD

**Issue by yarinKuper** [yangheng95/PyABSA#125]
Following the guide i tried to run the following example:

![image](https://user-images.githubusercontent.com/17201132/148188839-367eee36-0eed-4d89-89d3-a6ebeeceb0a4.png)

And getting the following error:

AttributeError: 'ATEPCConfigManager' object has no attribute 'sep_indices'

**Comment by yangheng95** [comment]
This is caused by outdated checkpoint. I am very busy now, and the training is expensive somehow, please wait for the update of checkpoints. (expected done soon)

**Comment by yangheng95** [comment]
Please check the updated checkpoints.
