### ISSUE TITLE
1.8.5与1.8.8版采用预训练的checkpoint，ATEPC任务的情感分类结果都为0（Negative）

### ISSUE THREAD

**Issue by amao2001** [yangheng95/PyABSA#126]
![image](https://user-images.githubusercontent.com/30647217/149601244-66534d03-d573-43bd-97d3-f5d9d48f347d.png)
![image](https://user-images.githubusercontent.com/30647217/149601292-85bcc62b-b5af-461c-a22a-3fae521398dd.png)
![image](https://user-images.githubusercontent.com/30647217/149601336-bd154059-bf4c-4403-b06d-c376e2f55815.png)
![image](https://user-images.githubusercontent.com/30647217/149601380-40ccdc4d-3716-45fc-861c-8ade59bfd719.png)
![image](https://user-images.githubusercontent.com/30647217/149601422-ab7c5841-9197-4916-a29c-5b9be5deb2fb.png)
![image](https://user-images.githubusercontent.com/30647217/149601460-69deb9ad-4d09-4eef-a7bb-072c2ede2a5c.png)
![image](https://user-images.githubusercontent.com/30647217/149601489-2c134552-912e-4c05-8546-f2842728d4c1.png)
![image](https://user-images.githubusercontent.com/30647217/149601519-34fbd039-66ce-49bb-974e-d3e5b96d962a.png)
![image](https://user-images.githubusercontent.com/30647217/149601540-1c64ef90-0f68-42a8-af4f-8d59c8651da3.png)
![image](https://user-images.githubusercontent.com/30647217/149601586-22acb5d4-a511-4956-ae3f-83468a142237.png)

**Comment by amao2001** [comment]
汉语与多语言都存在该问题

**Comment by yangheng95** [comment]
你好，谢谢反馈，我会尽快修复

**Comment by yangheng95** [comment]
这个问题的出现是缓存数据集的问题，禁用数据集缓存再训练可以避免这个问题。我已经更新逻辑，请尝试使用1.8.9版本，checkpoint将会在近几天上传，您可以先在中文数据集上自己训练，不会花费太长时间。

**Comment by amao2001** [comment]
好的，多谢
