### ISSUE TITLE
关于加载本地的模型 checkpoint

### ISSUE THREAD

**Issue by Edward-Joker** [yangheng95/PyABSA#128]
我查看了作者的demo文件，我发现这些都需要从goole云盘下载自己的预训练模型（先要上传至谷歌云盘）
然而，我想加载本地的模型。例如：
![image](https://user-images.githubusercontent.com/40120224/151295824-0412e49a-9ad2-47ea-8aa6-a2228aaba2cf.png)
![image](https://user-images.githubusercontent.com/40120224/151295837-7341fcb8-76e4-4ee7-bd66-025550799172.png)
请问如何解决，希望得到作者答复，谢谢

**Comment by Edward-Joker** [comment]
我找到一条您之前的回答：
Baidu网盘上的checkpoint不适合1.0以上的版本，我刚刚更新了新版的checkpoint，下载后克隆最新的examples，再将下载的zip文件名， 解压后的路径或者Google drive上的checkpoint名字作为ATEPCCheckpointManager.get_aspect_extractor的checkpoint参数即可
![image](https://user-images.githubusercontent.com/40120224/151297393-baec1ced-8c69-43d6-92da-4440cf7e6968.png)

我这边将checkpoint路径添加如下尝试
![image](https://user-images.githubusercontent.com/40120224/151297738-ca90b8b3-3292-479c-9b09-58c6ca4fb090.png)

但是这行代码ATEPCCheckpointManager.get_aspect_extractor(checkpoint=checkpoint, eval_batch_size=256)依然尝试从谷歌云盘下载模型训练

**Comment by Edward-Joker** [comment]
![image](https://user-images.githubusercontent.com/40120224/151303418-68000e80-5789-4be8-a980-22b276741c71.png)
 我尝试过
![image](https://user-images.githubusercontent.com/40120224/151305895-7fda757a-3bf8-433e-b22a-1847257c51c1.png)

**Comment by yangheng95** [comment]
> 我查看了作者的demo文件，我发现这些都需要从goole云盘下载自己的预训练模型（先要上传至谷歌云盘） 然而，我想加载本地的模型。例如： ![image](https://user-images.githubusercontent.com/40120224/151295824-0412e49a-9ad2-47ea-8aa6-a2228aaba2cf.png) ![image](https://user-images.githubusercontent.com/40120224/151295837-7341fcb8-76e4-4ee7-bd66-025550799172.png) 请问如何解决，希望得到作者答复，谢谢

这是由于findfile的实现在不同的系统中的表现不同导致的，请试试直接使用fast_lcf_atepc作为checkpoint参数传入
`checkpoint='fast_lcf_atepc'`

**Comment by yangheng95** [comment]
或者您可以尝试更新测试版findfile==1.7.6a0：
```bash
pip install findfile==1.7.6a0
```

**Comment by Edward-Joker** [comment]
您好，我再尝试
直接使用fast_lcf_atepc作为checkpoint参数传入
checkpoint='fast_lcf_atepc'
![image](https://user-images.githubusercontent.com/40120224/151326886-3513692c-5ac8-4add-bac1-3f3b56a5ce52.png)
以及
尝试更新测试版findfile==1.7.6a0：
![image](https://user-images.githubusercontent.com/40120224/151327022-2e5b1357-65f7-4513-bdfd-5be7c7cdb791.png)
依然无法读取本地模型
![image](https://user-images.githubusercontent.com/40120224/151327112-84535015-946b-4f8c-bf84-29ee50278894.png)

**Comment by Edward-Joker** [comment]
我认为代码bug可能出自findfile，我添加了两行代码在get_aspect_extractor()方法中，如下
![image](https://user-images.githubusercontent.com/40120224/151328350-cb2eb894-3d26-4148-aaaf-8b5f2c96885e.png)
得到输出
![image](https://user-images.githubusercontent.com/40120224/151328610-22662650-2196-415f-b5f5-00fa99ac7f97.png)

**Comment by Edward-Joker** [comment]
抱歉，我再次尝试后，发现又可以运行了
![image](https://user-images.githubusercontent.com/40120224/151334785-50a395c0-234c-4c16-8747-71f433447e70.png)

![image](https://user-images.githubusercontent.com/40120224/151334684-8eaa14d2-09d1-4baa-8797-04bab19bcbca.png)
![image](https://user-images.githubusercontent.com/40120224/151334756-21f390b8-2b49-40b1-aab4-6e1acab2f2b5.png)

**Comment by Edward-Joker** [comment]
再次感谢您的贡献

**Comment by Edward-Joker** [comment]
我在尝试使用作者提供的多语言预训练文件，在谷歌云盘下载
![image](https://user-images.githubusercontent.com/40120224/151341103-4e2330b7-614a-4725-830d-25164457b930.png)
当在预测时出现如下错误
![image](https://user-images.githubusercontent.com/40120224/151341260-bfe97ba3-1371-4c86-9569-228813145f7b.png)
![image](https://user-images.githubusercontent.com/40120224/151341292-c112705e-7c21-447c-87b7-067c0215bd81.png)

是否是因为英文是方面词三分类，而中文是二分类所致？

**Comment by yangheng95** [comment]
![image](https://user-images.githubusercontent.com/51735130/151344614-4387f8b6-5c7e-46ff-ad38-7beef0c948d6.png)
请更新版本PyABSA?

**Comment by yangheng95** [comment]
抱歉，因为GDrive可以使用的免费空间有限，所以每次更新checkpoint时不会保留旧版本。这应该不影响你自己训练checkpoint，并加载训练
