### ISSUE TITLE
Regard lcfs_atepc

### ISSUE THREAD

**Issue by Astudnew** [yangheng95/PyABSA#129]
Hello 
please could you help me use pyABSA to lcfs_atepc (using my own dataset and pre-triend bert model) on google colab? I need complete steps/code
Thanks in Advance

**Comment by yangheng95** [comment]
Please see https://colab.research.google.com/drive/1LOBc_yJupqk3HIK9kYW0_RCAWkn73lt0?usp=sharing

**Comment by Astudnew** [comment]
Thank you, but if my dataset is not in English can I use this code? also if I have the training and testing datasets where is the place of the test dataset in the code?

**Comment by yangheng95** [comment]
Sry I fail to understand you. You can use almost all languages thanks for transformers. Just follow the instructions in ABSADatasets https://github.com/yangheng95/ABSADatasets  to use your dataset in PyABSA

**Comment by Astudnew** [comment]
> Sry I fail to understand you. You can use almost all languages thanks to transformers. Just follow the instructions in ABSADatasets https://github.com/yangheng95/ABSADatasets to use your dataset in PyABSA

In the old Atepc repository the dataset has two labels one for tag and another for polarity, can I use this format directly in this notebook?
and for inference what should i put instead of ABSADatasetList.Laptop14? Note (my dataset not in english)
