### ISSUE TITLE
trying the model on fresh datasets

### ISSUE THREAD

**Issue by ghost** [yangheng95/PyABSA#13]
Hi!

I trained the model according to your instructions (with laptop dataset) and now I want to test the model on a different dataset, like the restaurant dataset of SemEval14.  I have some questions:

**1)** I already put my state-dict file in the inferring_dataset folder.  I don't know what to add as my inferring dataset here (can I just add **Restaurants_Test_Gold.xml.seg** from **datasets/apc_datasets/semeval2014** ?) 

**2)** Where should I add the path and name of the dataset I want to do the inferring on?

**Comment by yangheng95** [comment]
Um, why do you want to test the trained model on uncorresponded dataset?

Anyhow, follow the format of given examples for infering, the code detects corresponding file by https://github.com/yangheng95/LC-ABSA/blob/90ae7f41b3766761005caf015292926127fe3949/apc_infer.py#L147
Just keep the hyperparameters intact as training process.

**Comment by ghost** [comment]
I want to extract aspects and their corresponding sentiments and their polarities in a certain document or just a sentence. Using this trained model.

For example, let's say I want to extract aspects and corresponding sentiments with their polarity values of this sentence "The battery life is good but the price is too expensive." using the model I just trained. How can I do this?

**Comment by ghost** [comment]
Hello,

How can I test the model I trained on the laptop dataset on the restaurant dataset to see its accuracy?

Also, I couldn't manage to do what you said earlier about inferring data, I want to extract the aspects and their corresponding sentiment on an input sentence, how can I do this?

**Comment by yangheng95** [comment]
See the aspect term extraction and sentiment classification tutorial https://github.com/yangheng95/pyabsa/tree/release/examples/aspect_term_extraction.
