### ISSUE TITLE
加载模型时的报错

### ISSUE THREAD

**Issue by MaisieCai** [yangheng95/PyABSA#130]
![bug](https://user-images.githubusercontent.com/57559538/153715922-91de9fa0-d2ac-4fe7-9bf1-e7fb51ab987e.png)
这个问题该如何解决

**Comment by yangheng95** [comment]
请注意checkpoints版本与PyABSA版本兼容
![image](https://user-images.githubusercontent.com/51735130/153716114-5a4ccf36-d8d2-469e-ad41-9873f3c1e4fc.png)

**Comment by MaisieCai** [comment]
请问要怎么看PyABSA的版本？我是这两天才安装的PyABSA，checkpoints是直接这么传入的checkpoint = 'state_dict/lcf_atepc_cdw'

**Comment by yangheng95** [comment]
你安装的应该是最新版1.8.20，请在google drive下载最新checkpoint，百度云上的已经过期

**Comment by MaisieCai** [comment]
好的，谢谢，我再试试google drive上的
