### ISSUE TITLE
en_core_web_sm

### ISSUE THREAD

**Issue by MaisieCai** [yangheng95/PyABSA#131]
![image](https://user-images.githubusercontent.com/57559538/153746603-aee9ae69-f514-42a9-9288-38797eef60cd.png)
![image](https://user-images.githubusercontent.com/57559538/153746631-62850e20-0d2e-48af-b601-9387abbf4962.png)
en_core_web_sm已经下载安装好了，但是atepc_result = aspect_extractor.extract_aspect()这部分代码需要怎么修改？

**Comment by yangheng95** [comment]
下载好的en_core_web_sm已经用pip install en_core_web_sm安装了吗

**Comment by MaisieCai** [comment]
用pip install 安装了，但运行图上代码的时候一直会download

**Comment by yangheng95** [comment]
可否把你的代码共享在google colab，分享给我查看问题

**Comment by MaisieCai** [comment]
重新pip install，问题解决了，谢谢
