### ISSUE TITLE
Custom dataset import not functional in 1.8.22

### ISSUE THREAD

**Issue by brieucdandin** [yangheng95/PyABSA#132]
When trying use the [sentiment inference script](https://github.com/yangheng95/PyABSA/blob/release/demos/aspect_polarity_classification/sentiment_inference.py) given as example in demos/aspect_polarity_classification/ with a dataset made according to the guidelines provided in the [ABSADatasets](https://github.com/yangheng95/ABSADatasets) repository, an exception is raised during a [detect_infer_dataset](https://github.com/yangheng95/PyABSA/blob/release/pyabsa/functional/dataset/dataset_manager.py#L157) call.

At line 157, `if os.path.isdir(max(d, search_path)):` returns `TypeError: '>' not supported between instances of 'NoneType' and 'str'`.

Probably, the issue lies in the use of `max` on `search_path` and `d`, the later being first defined as a string, and then as an element of an iteration on a `DatasetItem` (line 147, ` for d in dataset_path:`).
Perhaps ```if not dataset_items: dataset_items = dataset_name``` in the class's `__init__` ([lines 47 and 48](https://github.com/yangheng95/PyABSA/blob/release/pyabsa/functional/dataset/dataset_manager.py#L27)) is not the best way to do it, especially considering that `dataset_name` could have been defined as `os.path.basename(dataset_name)` [prior to this](https://github.com/yangheng95/PyABSA/blob/release/pyabsa/functional/dataset/dataset_manager.py#L23), which **sometimes returns an empty string**.

In may be worth noting I use Databricks and its file storage system DBFS, which already seemed to affect the definition of the `dataset_items` of a `DatasetItem` object in (recent) previous versions: some paths end up with empty corresponding `dataset_items` lists. Although, it also seems that is the case on local environments like Windows.

#### Full stack:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<[command-759931538946855]()> in <module>
     41 results_mentions = sent_classifier.batch_infer(target_file=inference_sets_mentions,
     42                                                print_result=True,
     43                                                save_result=True,
---> 44                                                ignore_error=True,
     45                                               )

/local_disk0/.ephemeral_nfs/envs/pythonEnv-7eb1071f-0a42-4abe-bfbc-2f7e07c89670/lib/python3.7/site-packages/pyabsa/core/apc/prediction/sentiment_classifier.py in batch_infer(self, target_file, print_result, save_result, clear_input_samples, ignore_error)
    186         save_path = os.path.join(os.getcwd(), 'apc_inference.result.json')
    187 
--> 188         target_file = detect_infer_dataset(target_file, task='apc')
    189         if not target_file:
    190             raise FileNotFoundError('Can not find inference datasets!')

/local_disk0/.ephemeral_nfs/envs/pythonEnv-7eb1071f-0a42-4abe-bfbc-2f7e07c89670/lib/python3.7/site-packages/pyabsa/functional/dataset/dataset_manager.py in detect_infer_dataset(dataset_path, task)
    155 
    156     if len(dataset_file) == 0:
--> 157         if os.path.isdir(max(d, search_path)):
    158             print('No train set found from: {}, unrecognized files: {}'.format(dataset_path, ', '.join(os.listdir(max(d, search_path)))))
    159         raise RuntimeError('Fail to locate dataset: {}. If you are using your own dataset,' ' you may need rename your dataset according to {}'.format(

TypeError: '>' not supported between instances of 'NoneType' and 'str'
```

**Comment by yangheng95** [comment]
That is a problem, indeed. I will fix it soon, Also, I would like to ask for some advice. 
Would you like to make a PR to improve this block?

**Comment by brieucdandin** [comment]
Sure, here it is: [https://github.com/yangheng95/PyABSA/pull/133](https://github.com/yangheng95/PyABSA/pull/133)

Please note I only changed the `__init__` of `DatasetItem` and tested the result locally (Windows 10), and on one task only. So there very well may be other places that I don't know of where change is needed... You'll know better than me where to look for those, @yangheng95 !

Also, I probably have wrongly understood what you wanted to do with `dataset_name`. If that's the case, please accept my apologies and ignore this PR. Some more comments would be handy, though.

**Comment by brieucdandin** [comment]
It doesn't fix everything when I tested it, but works better when given a path and not just the name.
Perhaps you can consider separating the two in some way? With the argument `dataset_path` in addition to `dataset_name` in the `__init__` , both defaulting to `None` (and both attributes in the `DatasetItem` object). That would enable choosing to use either one or the other whenever are test is done.

**Comment by yangheng95** [comment]
Please try 1.8.23. Maybe it can accept dirname and shortname as dataset arg.
