### ISSUE TITLE
Checkpoints google drive link not working

### ISSUE THREAD

**Issue by AdLucem** [yangheng95/PyABSA#137]
Hello

The google drive link for the checkpoints shown in this message:

`Google Drive applies a restriction on public large file downloading, if you find the checkpoint downloaded if None or small, please download it via browser: https://drive.google.com/file/d/10TQGpYnQqry9uGDPvSKkVPdieRhycnAh/view?usp=sharing`

is not working. I navigated to the given gdrive link but it shows a `Page Not Found` error.

**Comment by yangheng95** [comment]
Hi, 
Sorry for your inconvenience. I made some changes trying to fix the automatic downloading, but I failed.
Which checkpoints can not be found? Can you test and report to fix them?

**Comment by yangheng95** [comment]
Hi, @AdLucem 
I made some updates to the checkpoint URLs; Please have a check.
