### ISSUE TITLE
Not Predicting Negative Label

### ISSUE THREAD

**Issue by anilkumar9912** [yangheng95/PyABSA#139]
Hi @yangheng95 ,
I'm trying out the atepc on English checkpoint.
pyabsa version: 1.8.30
Used  checkpoint: **fast_lcf_atepc_English_cdw_apcacc_80.16_apcf1_78.34_atef1_75.39.zip**
The model is predicting **Positive** and **Neutral**  sentiments only even when there are negative aspects.
I've performed inference on Tshirt and SemEval dataset but I did not find any negative polarity tag in any of the examples.
Can you please explain how to get the three classes?(Positive,Negative and Neutral)
Thank you.

**Comment by yangheng95** [comment]
Thanks for your report, I confirm there is a problem. However, I am not available for fixing it right now, maybe later. And you can tell me if you find the reason for this error to fix it.

**Comment by anilkumar9912** [comment]
My initial guess is to check the number of classes the checkpoint is trained on
I checked the config of the trained checkpoint ** fast_lcf_atepc_English_cdw_apcacc_80.16_apcf1_78.34_atef1_75.39.zip** for polarity classes: it's given 3. So it's a 3 class (0:Negative,1:Neutral,2:Positive) classifiation.
While inferring, Class 0 is neglected. Maybe there's an issue while decoding softmax scores to class labels.
Where's this decoding is happening? (mapping scores to class labels).

**Comment by yangheng95** [comment]
Sorry for late reply, please try 1.8.32 which may fixes this problem

**Comment by anilkumar9912** [comment]
Thanks @yangheng95 .It works with the new 1.8.32 version.
