### ISSUE TITLE
Only one sentiment for the aspect

### ISSUE THREAD

**Issue by pepi99** [yangheng95/PyABSA#141]
Hello,

Q1. Is it possible to achieve something like this: https://github.com/ScalaConsultants/Aspect-Based-Sentiment-Analysis . I want, for a sentence, to only specify the aspects, and get only one sentiment score for each aspect?

Q2.  Is it very bad if there is small class imbalance? I can overcome this by giving only one topic for each sentence and have the same amount of sentences for each topic. 

Q3. I have some words (like "bullish", "bearish", that carry specific meaning in the cryptocurrency field). Is it necessary to give to each aspect these words for the model to be able to classify the sentiments, or not?

And one example: "Bitcoin is bearish these days...". Bearish has negative meaning. So should I label "bearish" or "bitcoin" ? 

Thanks

**Comment by yangheng95** [comment]
Does the infer API solve your Q1?
``` result = sent_classifier.infer(ex, print_result=True)```
I have no systematic research on data imbalance, so the discussion in literature may help.
I am not sure what you mean about Q3, and the labeling strategy depends on yourself, this repo is only responsible for extracting the aspects as your label and classifying the sentiment of your aspects

**Comment by pepi99** [comment]
Yes, I think it will work. I have to put manually the "[ASP] aspect [ASP]" Asp tokens, right?

Also, I want to save a full checkpoint of the model. How can I specify the name of the checkpoint? Now I do it with checkpoint_save_model=2, but how can I know the name of the checkpoint? Also, how can I load the checkpoint?

Thanks.

**Comment by pepi99** [comment]
For Q3, I mean, if I want for example to learn the model to classify the word "bearish" as negative sentiment, and I give it examples "Bitcoin is Bearish", it will learn that [ASP]Bitcoin[ASP] is negative when the word Bearish is around? So it will learn that Bearish is a bad sentiment word, right? 

Thanks.
