### ISSUE TITLE
Error with transformers version 

### ISSUE THREAD

**Issue by anilkumar9912** [yangheng95/PyABSA#143]
Hi @yangheng95 ,
The transformers version required is kept greater than 4.5 **'4.5<transformers<5.0',** whereas the latest version of transformers itself is 
4.17 only.

Because of this we're getting the following error with ** pip install -U pyabsa**
![absa](https://user-images.githubusercontent.com/101084142/157601146-4ae7ffe3-2061-4f4a-aafe-e927b27f675b.png)

**Comment by AaronHeee** [comment]
I encounter the same issue when using `python setup.py install`

**Comment by anilkumar9912** [comment]
> I encounter the same issue when using `python setup.py install`

@AaronHeee If you are installing from source, you can edit the line **4.5<transformers<5.0** in setup.py to **4.0<transformers<5.0** .Alterntively you can **pip install transformers**.

**Comment by anilkumar9912** [comment]
Working well with 1.8.33 version.
