### ISSUE TITLE
Fast lsa deberta large error

### ISSUE THREAD

**Issue by pepi99** [yangheng95/PyABSA#144]
My code is: 

import random

import torch

from pyabsa.functional import Trainer
from pyabsa.functional import APCConfigManager
from pyabsa.functional import ABSADatasetList
from pyabsa.functional import APCModelList
import warnings

warnings.filterwarnings('ignore')

seeds = [random.randint(0, 10000) for _ in range(2)]

apc_config_english = APCConfigManager.get_apc_config_english()
apc_config_english.model = APCModelList.FAST_LSA_T
apc_config_english.lcf = 'cdw'
apc_config_english.similarity_threshold = 1
apc_config_english.max_seq_len = 80
apc_config_english.dropout = 0
apc_config_english.cache_dataset = False
apc_config_english.patience = 10
apc_config_english.optimizer = 'radam'
apc_config_english.pretrained_bert = 'microsoft/deberta-v3-large'
apc_config_english.hidden_dim = 1024
apc_config_english.embed_dim = 1024
apc_config_english.num_epoch = 1
apc_config_english.log_step = 50
apc_config_english.learning_rate = 1e-5
apc_config_english.batch_size = 16
apc_config_english.evaluate_begin = 0
apc_config_english.l2reg = 1e-8
apc_config_english.seed = seeds

apc_config_english.cross_validate_fold = -1  # disable cross_validate

CryptoDataset = ABSADatasetList.CryptoCustom

sent_classifier = Trainer(config=apc_config_english,
                         dataset=CryptoDataset,  # train set and test set will be automatically detected
                         checkpoint_save_mode=2,  # =None to avoid save model
                         auto_device=True  # automatic choose CUDA or CPU
                         ).load_trained_model()

Error happens in the end of training:

Traceback (most recent call last):
  File "/home/ubuntu/nlp/PyABSA/demos/aspect_polarity_classification/train_apc_crypto_lsa_deberta_large.py", line 39, in <module>
    sent_classifier = Trainer(config=apc_config_english,
  File "/home/ubuntu/nlp/PyABSA/pyabsa/functional/trainer/trainer.py", line 135, in __init__
    self.train()
  File "/home/ubuntu/nlp/PyABSA/pyabsa/functional/trainer/trainer.py", line 163, in train
    if os.path.exists(max(model_path)):
TypeError: '>' not supported between instances of 'APCEnsembler' and 'APCEnsembler'

Please help.

**Comment by yangheng95** [comment]
I can not reproduce your problem, can you reproduce this issue with provided datasets?

**Comment by pepi99** [comment]
I think i found the problem. It happens because I give it only 1 training epoch (apc_config_english.num_epoch = 1), and during training there is no accuracy shown (it was for testing purposes). So I increased the num_epochs and it works.
