### ISSUE TITLE
Performance difference when model is trained on the same data?

### ISSUE THREAD

**Issue by pepi99** [yangheng95/PyABSA#146]
Hello,
I already posted a similar issue where I described that I had problem using a checkpoint (when saved with checkpoint_save_mode=2) on a different machine. So I retrained the model on the same data (with checkpoint_save_mode=1), and the performance of the checkpoints is so different. Example:

sentence = 'I am a cool dude! #[ASP]bitcoin[ASP] sucks. What about [ASP]ethereum[ASP]?'

model1 = APCCheckpointManager.get_sentiment_classifier(checkpoint='fast_lsa_t_Crypto_acc_79.74_f1_80.21')
model2 =APCCheckpointManager.get_sentiment_classifier(checkpoint='fast_lsa_t_Crypto_acc_83.62_f1_84.14_state_dict')

model1.infer(sentence) -> i am cool dude! # bitcoin -> 1.0(confidence:Negative) sucks. what about ethereum -> 0.999(confidence:Neutral)? 

model2.infer(sentence) -> i am a cool dude! # bitcoin -> 0.998(confidence:Negative) sucks. what about ethereum -> 0.917(confidence:Positive)?

Obviously, model1 is correct, because the sentiment for ethereum should be neutral. Why is this problem happening when I train on the same dataset, and only change checkpoint_save_mode, why is there different predictions?

**Comment by pepi99** [comment]
@yangheng95 , can this be a possible reason:
checkpoint_save_mode =1 will only save the state_dict (so the trained pytorch model on top of bert). But the fine-tuned bert WILL NOT be saved, so this is probably why I get performance decrease.

While checkpoint_save_mode=2 will save the trained pytorch model + the fine-tuned bert (so the full trained model).

**Comment by yangheng95** [comment]
Hi, @pepi99 
No, the parameters of the whole model are both saved in two methods. 
Generally, if you use the same config and dataset, there should be no significant difference between saving .state_dict and .model. I suggest you can check the training detail and run more evaluations to make sure if it is a common situation in your dataset.

**Comment by pepi99** [comment]
OK. This is useful to know. More evaluations you mean more epochs, or to run the training more times?

**Comment by yangheng95** [comment]
Run inference on more cases to confirm the issue you found

**Comment by pepi99** [comment]
Ok there are slight performance differencess (+-20%), but I think it just needs more training data to be more conclusive.
