### ISSUE TITLE
ATEPC predict时如何解决先有鸡还是先有蛋的问题？

### ISSUE THREAD

**Issue by jkkl** [yangheng95/PyABSA#150]
如果使用BERT-SPC，那么input是：CLS + text + SEP + aspect + SEP，而预测时并不知道aspect...
如果不使用BERT-SPC，那么只能假设当前text中只有一个aspect..
所以，ATEPC模型，只能做单aspect的联合抽取和情感预测是吗？

**Comment by yangheng95** [comment]
可以同时抽取多个方面，但情感是一个一个预测的

**Comment by yangheng95** [comment]
抽取方面时采用[CLS] + Seq+ [SEP]的数据，预测情感才启用SPC:
https://github.com/yangheng95/PyABSA/blob/abe1ecfeb8af3efae08a72901a7739107afa997d/pyabsa/core/atepc/prediction/aspect_extractor.py#L341

**Comment by jkkl** [comment]
> 可以同时抽取多个方面，但情感是一个一个预测的

谢谢 @yangheng95 ，所以，对online text预测时，只能通过这种pipeline的方式吧。
1.先预测出所有的aspect
2.分别对每一个aspect做情感预测。
举个例子，拿着训练好的multi task 的atepc模型，online预测一个新的text：
【这个手机内存有点小，但系统还是比较流畅的。】
并不能一次性预测出：
aspect:内存   sentiment：negtive
aspect:系统   sentiment：postive
而是需要pipeline的方式吧？

**Comment by yangheng95** [comment]
是的，多个方面的抽取是并行的，但是每个方面的情感分类是串行的。参照aspect_extractor.py中的实现

**Comment by jkkl** [comment]
> 是的，多个方面的抽取是并行的，但是每个方面的情感分类是串行的。参照aspect_extractor.py中的实现

嗯嗯，online预测时，即便是单aspect与sentiment也不能同时出结果吧？因为SPC的input就需要aspect。。。

**Comment by yangheng95** [comment]
是的，先抽取asp，再分类情感，具体流程请参照代码
