### ISSUE TITLE
使用deploy demo，情感预测总是Positive

### ISSUE THREAD

**Issue by jkkl** [yangheng95/PyABSA#152]
checkpoint = 'model_garden/V0.8.8.0/Chinese/ATEPC/fast_lcf_atepc_Chinese_cdw_apcacc_96.69_apcf1_96.25_atef1_92.26'
checkpoint = 'model_garden/V0.8.8.0/Chinese/ATEPC/fast_lcf_atepc_Multilingual_cdw_apcacc_79.61_apcf1_76.24_atef1_63.29.zip'
这两个模型都试了，Sentiment总是Positive，即便用很负向的表达。

![image](https://user-images.githubusercontent.com/3937341/159253178-498c6da1-4a31-474d-84b4-f3345aea6d19.png)

**Comment by yangheng95** [comment]
请问你使用的哪个版本？请尝试更新到最新版本，有些低版本已知有bug

**Comment by jkkl** [comment]
> 请问你使用的哪个版本？请尝试更新到最新版本，有些低版本已知有bug

代码是上周刚clone的master

**Comment by jkkl** [comment]
> 请问你使用的哪个版本？请尝试更新到最新版本，有些低版本已知有bug

你说的版本是指模型还是代码？

**Comment by yangheng95** [comment]
代码与checkpoint应该匹配

**Comment by yangheng95** [comment]
请都使用最新版本

**Comment by yangheng95** [comment]
我随后会测试确定问题原因

**Comment by jkkl** [comment]
> 请都使用最新版本

最新版的模型在哪找~~

**Comment by jkkl** [comment]
> 请都使用最新版本

我使用的这个模型，应该是最新的吧：fast_lcf_atepc_Chinese_cdw_apcacc_96.69_apcf1_96.25_atef1_92.26

**Comment by yangheng95** [comment]
PyABSA版本大于1.8.33吗

**Comment by yangheng95** [comment]
![image](https://user-images.githubusercontent.com/51735130/159256940-97b9a183-764d-4920-903a-d8605b044c97.png)
checkpoint没有问题，请升级PyABSA.
测试版本：V1.8.39
请在此测试：https://55336.gradio.app/

**Comment by jkkl** [comment]
> ![image](https://user-images.githubusercontent.com/51735130/159256940-97b9a183-764d-4920-903a-d8605b044c97.png) checkpoint没有问题，请升级PyABSA. 测试版本：V1.8.39 请在此测试：https://55336.gradio.app/

Thanks，升级代码后成功了~
