### ISSUE TITLE
segment id 是不是少计算了 [CLS]

### ISSUE THREAD

**Issue by jkkl** [yangheng95/PyABSA#155]
![image](https://user-images.githubusercontent.com/3937341/159667355-7524baec-5387-40bb-8db4-55ac748ca54e.png)

**Comment by yangheng95** [comment]
确认是个bug

**Comment by yangheng95** [comment]
这个bug不会影响使用，您可以同步最新版本并PR或者等待下次更新

**Comment by jkkl** [comment]
> 这个bug不会影响使用，您可以同步最新版本并PR或者等待下次更新

好的，晚会儿我提个PR~~

**Comment by jkkl** [comment]
> 这个bug不会影响使用，您可以同步最新版本并PR或者等待下次更新

更正一下，应该是少了一个CLS 和SEP，segment_id 少了2个0.

**Comment by yangheng95** [comment]
我直接使用全零向量作为segment ids，因为实验证明这个task不需要使用segment ids
