### ISSUE TITLE
在计算cdm和cdw时，有疑问...

### ISSUE THREAD

**Issue by jkkl** [yangheng95/PyABSA#157]
在计算text_len 时，是不是少减了一个SEP。
![image](https://user-images.githubusercontent.com/3937341/160075138-f208ba0a-a212-4c9f-8c69-6fa41cf93a97.png)
导致 cdm 和 cdw计算时，认为SEP是一个local feature。
![image](https://user-images.githubusercontent.com/3937341/160074840-3dbcc3d6-301b-49ab-9404-4d2ccd61f020.png)

还是说，SEP 就应该是一个local feature ？

**Comment by yangheng95** [comment]
实验表明[SEP]算不算local context都不会显著影响效果。 但具体的性能差距难以量化，因为ABSA的数据集metric波动太大了

**Comment by ningmiaokai** [comment]
> 在计算text_len 时，是不是少减了一个SEP。 ![image](https://user-images.githubusercontent.com/3937341/160075138-f208ba0a-a212-4c9f-8c69-6fa41cf93a97.png) 导致 cdm 和 cdw计算时，认为SEP是一个local feature。 ![image](https://user-images.githubusercontent.com/3937341/160074840-3dbcc3d6-301b-49ab-9404-4d2ccd61f020.png)
> 
> 还是说，SEP 就应该是一个local feature ？

请问一下您，您用这个模块成功了吗？这里的Opt是什么呢？

**Comment by ningmiaokai** [comment]
> 实验表明[SEP]算不算local context都不会显著影响效果。 但具体的性能差距难以量化，因为ABSA的数据集metric波动太大了

请问一下您，他这里的opt是什么呀，我都看了好长时间，没弄明白
