### ISSUE TITLE
train data 一般不是用RandomSampler吗？

### ISSUE THREAD

**Issue by jkkl** [yangheng95/PyABSA#158]
![image](https://user-images.githubusercontent.com/3937341/160080142-69a68005-79e3-4592-bd6c-ba0ce6d044bb.png)

**Comment by yangheng95** [comment]
是的，将会修改

**Comment by yangheng95** [comment]
已修复，欢迎测试

**Comment by yangheng95** [comment]
V1.8.42版本对逻辑改动较大，训练时在分类情感时启用了SPC，抽取情感时禁用了SPC。这是一个测试版本，尚不确定会不会有问题

**Comment by jkkl** [comment]
> 

ATE 任务 不上个CRF 嘛~~

**Comment by yangheng95** [comment]
hh，可以， 但是感觉效果够了，你可以试试看有没有CRF的区别

**Comment by jkkl** [comment]
> 

哈哈，工业界效果没有够这一说~~，回来我试一下~~

**Comment by jkkl** [comment]
> hh，可以， 但是感觉效果够了，你可以试试看有没有CRF的区别

对了，代码里Fast_LCF  和 论文里LCF有啥区别？

**Comment by yangheng95** [comment]
实现方式不同，原始版本在训练时计算LCF，很慢。新版本在预处理时计算，更节省内存和时间。
