### ISSUE TITLE
Is the above technique(model) valid, when I train on Laptop dataset and test it on say Restaurant Dataset?

### ISSUE THREAD

**Issue by ptiwari2407** [yangheng95/PyABSA#16]
I am trying to develop a general solution, where I train in one domain but have no labelled dataset in another domain. So will training this model in one domain, generalize for other domains. (e.g If I train on laptop dataset, will the model generalize on restaurant dataset)?

Note: Of-course the language is the same for both the datasets(e.g both domains are presented in English language).

**Comment by yangheng95** [comment]
Yes, make sure the config or hyperparameters are the same.

**Comment by ptiwari2407** [comment]
@yangheng95 thanks for your response. i will try it out and experiment with different hyperparameters.
