### ISSUE TITLE
预测APC任务时ATE label id 与训练时 是不是没对齐

### ISSUE THREAD

**Issue by jkkl** [yangheng95/PyABSA#160]
预测时是固定的，但训练时时动态获取的。可能会ID不一致吧？
![image](https://user-images.githubusercontent.com/3937341/160745526-d4d92cf5-4a5d-4b17-9374-068e8c2b1dba.png)

![image](https://user-images.githubusercontent.com/3937341/160745864-64d0adee-4612-430c-9252-096623ca81db.png)

![image](https://user-images.githubusercontent.com/3937341/160746031-cbb30968-1d07-420e-a5e2-64789a769c17.png)

**Comment by yangheng95** [comment]
您好！我有时间看下

**Comment by yangheng95** [comment]
你好，这个应该不会对预测造成影响，因为get_labels()返回的标签只有list长度会起作用，其中顺序不重要。

**Comment by jkkl** [comment]
> 
图3, 315行的label_map,是根据get_labels()的顺序构建的，所以，导致ID不一致。
