### ISSUE TITLE
支持多种aspect标签

### ISSUE THREAD

**Issue by jkkl** [yangheng95/PyABSA#161]
建议这个5动态获取，例如：改为：
sep_index = np.argmax((labels[text_i] == len(self.opt.label_list)))
可以兼容，多种aspect
![image](https://user-images.githubusercontent.com/3937341/160748135-582f1a11-8049-49be-b2f6-9289b48dd870.png)

**Comment by yangheng95** [comment]
精力有限，这个可能短时间没时间做

**Comment by yangheng95** [comment]
please check branch 1.10.0.rc0

**Comment by yangheng95** [comment]
@jkkl
