### ISSUE TITLE
Hyper parameter tuning

### ISSUE THREAD

**Issue by dimtsintzou** [yangheng95/PyABSA#17]
Hi, could you please explain to me at which point I could use an optimizer for hyperparameter tuning?

**Comment by yangheng95** [comment]
This is a good idea for automatic optimizing hyperparameters, but I am  sorry that I have no clue now for the amswer

**Comment by pepi99** [comment]
Optuna could be used. Please check this: https://github.com/ScalaConsultants/Aspect-Based-Sentiment-Analysis/blob/master/examples/train_classifier.py
