### ISSUE TITLE
Train model on continuous data

### ISSUE THREAD

**Issue by pepi99** [yangheng95/PyABSA#170]
Hello,
I want to run the model: [fast_lsa_t.py.py], but I want to possibly run it on continuous data.

What I mean is: 
Instead of having the examples in the format: [Sentence (with $T$ for the aspects) \n $ASPECT$ \n SENTIMENT] (where sentiment is a value in [Positive, Negative, Neutral]), I want to have the same format, but SENTIMENT being a continuous value between [-3.5, 3.5]. So I can have a sentence with a sentiment -2.312, another one with 1.91, another one with 3.11, and so on. 

Is there an easy way to adapt to this problem? I am thinking of changing the loss function to MSE and also the last layer being Dense(output_dim=1). Can you help me do it?

**Comment by pepi99** [comment]
Or it's not possible?

**Comment by yangheng95** [comment]
Sorry, I can not do this now, I am occupied on other tasks.

**Comment by pepi99** [comment]
I did it, should I open a pull request?

**Comment by yangheng95** [comment]
Yes, of course you can. 
I will test if it works fine with other models. Please create a new model file (give it a new model name as weel) or related data preprocessing files to minimize the impact of existing models.

**Comment by pepi99** [comment]
OK! I will probably do it in a couple of days. I had to change so many things. I hope it works. I will open a new pull request when I am free.
