### ISSUE TITLE
import pyabsa hangs when running on docker

### ISSUE THREAD

**Issue by shim52** [yangheng95/PyABSA#171]
### Description

When importing `pyabsa` running on a docker, the execution hangs.

### Debugging

The code hangs in [`pyabsa/utils/file_utils.py:312` ](https://github.com/yangheng95/PyABSA/blob/0785ad6b440dd9a7ed5423e55796517eaf9f12a8/pyabsa/utils/file_utils.py#L312)
Probably due to a third-party package called `findfile` which searches for a local version but never times out.

### Setup

- PyABSA 1.9.6
- Docker version 20.10.8, build 3967b7d
- Python 3.9

### Files to reproduce

**Dockerfile**
```
FROM python:3.9-slim-buster

COPY test.py .

RUN apt-get update && apt-get -y install git
RUN pip install pyabsa==1.9.5

CMD ["python test.py"]
```

**test.py**
```
import pyabsa

pyabsa.check_dataset()
```

**Comment by yangheng95** [comment]
You may try 
```docker
FROM python:3.9-slim-buster

COPY test.py .

RUN apt-get update && apt-get -y install git
RUN pip install findfile==1.7.7
RUN pip install pyabsa==1.9.5

CMD ["python test.py"]
```
which uses the updated version of findfile.

**Comment by shim52** [comment]
Thank you for your response @yangheng95 !

We have managed to resolve this issue by setting the `WORKDIR` of the dockerfile to something other than the root path as I wrote in the issue.
`cwd` is not root in runtime, and the code doesn't hang, so it's good enough for me.
