### ISSUE TITLE
请问下fast_lcf_bert和lcf_bert的区别是什么？

### ISSUE THREAD

**Issue by shikimoon** [yangheng95/PyABSA#173]
首先很感谢作者的开源，本人在公司项目中有借鉴一些想法和思路。最近再重新浏览该项目发现多了fast_lcf_bert，请问下和lcf_bert的区别是什么？我注意到lcf_bert在长文本中内存和显存的占用会明显高于其他模型，另外关于这么多的absa模型有什么建议或使用经验可以分享下吗，期待回复！

**Comment by yangheng95** [comment]
fast_lcf_bert通过在数据预处理时计算LCF权重，而不是在训练时计算，因此可以达到与原始bert相近的运行时间和资源占用。 性能没有明显可见损失。使用经验的话不好说，我只做研究，没有做过项目落地

**Comment by shikimoon** [comment]
好的，非常感谢
