### ISSUE TITLE
运行demos/aspect_polarity_classification/glove_baselines/train_apc_glove.py出错

### ISSUE THREAD

**Issue by LiYouL** [yangheng95/PyABSA#176]
您好
运行环境为colab 通过git安装，手动pip install setup.py内依赖。
问题一：
在运行示例时demos/aspect_polarity_classification/glove_baselines/train_apc_glove.py
代码如下：
![image](https://user-images.githubusercontent.com/42906603/163340834-57038321-ba7a-4e9a-b5d3-7ab8c00af272.png)  

出现：AttributeError: 'TNet_LF' object has no attribute 'eta1'  
替换其他模型及数据集也出提示类似问题。

问题二：
![image](https://user-images.githubusercontent.com/42906603/163341635-bd786888-3aa1-4d46-a6ba-3bfe0be5e6f5.png)
这几个config的区别是什么呢？即模型如何对应以上配置信息呢？

**Comment by yangheng95** [comment]
您好，请升级到1.10.1或者降级到1.9.6。这个错误debug过程中的代码忘记删除。

**Comment by yangheng95** [comment]
除了使用glove的模型需要使用apc_config_glove之外，其他的区别不大，主要是预训练模型的不同，一般根据语言使用

**Comment by LiYouL** [comment]
感谢解答
感谢您做的所有工作！
