### ISSUE TITLE
Can't use local path dataset

### ISSUE THREAD

**Issue by radya13rahman** [yangheng95/PyABSA#177]
![image](https://user-images.githubusercontent.com/48096736/163355726-4300fe8b-9381-45ff-b30b-0ed70416f727.png)
I've entered a path like this and am trying to use the existing dataset on my github (the github branch I've forked from the main github). But the code always fetches the dataset from the main github not from the fork and when I want to use a custom dataset an exception appears as above.

**Comment by radya13rahman** [comment]
Here the exception
![image](https://user-images.githubusercontent.com/48096736/163356365-5bc59296-e025-46f5-b3d0-7eb30770fcf2.png)

**Comment by yangheng95** [comment]
Try:
```python3
from pyabsa.functional.dataset import DatasetItem
dataset_path = DatasetItem('100.CustomDataset')
```
then use it in your code

**Comment by radya13rahman** [comment]
Thanks, Mr Heng
in the config manager code

I also want to ask why when I have changed the target repository that was cloned but the results still point to your repository?

Here's the code I edited
![image](https://user-images.githubusercontent.com/48096736/163361296-42effcd1-da6e-4d74-9571-21bb245b48c1.png)

**Comment by yangheng95** [comment]
You need to remove downloaded datasets

**Comment by radya13rahman** [comment]
`
import sys
sys.path.append('..')

from pyabsa.functional.dataset import DatasetItem
from pyabsa.functional import ATEPCConfigManager
from pyabsa.functional import ABSADatasetList
from pyabsa.functional import Trainer, ATEPCTrainer
from pyabsa.functional import ATEPCModelList
import os
`
I want to run the code locally but when I run this code, there is always an exception that there is no pyabsa module. how to solve it?

**Comment by radya13rahman** [comment]
``

**Comment by radya13rahman** [comment]
```
import sys
sys.path.append('..')

from pyabsa.functional.dataset import DatasetItem
from pyabsa.functional import ATEPCConfigManager
from pyabsa.functional import ABSADatasetList
from pyabsa.functional import Trainer, ATEPCTrainer
from pyabsa.functional import ATEPCModelList
import os
```
I want to run the code locally but when I run this code, there is always an exception that there is no pyabsa module. how to solve it?
![image](https://user-images.githubusercontent.com/48096736/163415221-fa386d24-adbe-431e-8d56-5d60c54b8a67.png)

**Comment by yangheng95** [comment]
please make sure that you properly installed the package

**Comment by yangheng95** [comment]
or the relative path is correct
