### ISSUE TITLE
Support dynamic window for test examples with more than max_len setting

### ISSUE THREAD

**Issue by brightgems** [yangheng95/PyABSA#178]
Looks like dynamic_truncate can solve the problems of exceed max_seq_len at training time, but interfence with longer text is till problem.

it will be great if can support dynamic window for longer text more than max_seq_len

**Comment by brightgems** [comment]
Looks like dynamic_truncate can solve the problems of exceed max_seq_len at training time, but interfence with longer text is till problem.

**Comment by yangheng95** [comment]
Can you give an example to help understand what you need? Can we set longer mex_seq to solve your problem?
