### ISSUE TITLE
Infer dataset text_raw truncation in data_utils_for_inferring.py

### ISSUE THREAD

**Issue by tusharkgerg** [yangheng95/PyABSA#18]
Hi,
I was trying to understand why in the inferring output - a sentence in my data was truncated, and then started seeing how max_seq_len truncation is working in class ABSADataset in:
 LC-ABSA/modules/utils/data_utils_for_inferring.py

In the code, text_right is initialized to null and then used to initialize text_right again. Was this intentional? Would be great to understand better if yes. 

```
            text_left = lines[i].replace('$', '').strip()
            text_right = ''

            aspect = lines[i][lines[i].find('$')+1:]
            aspect = aspect[:aspect.find('$')].strip()

            aspect_indices = tokenizer.text_to_sequence(aspect)
            aspect_len = np.sum(aspect_indices != 0)

            # Trick: dynamic truncation on input text
            text_left = ' '.join(text_left.split(' ')[int(-(tokenizer.max_seq_len - aspect_len) / 2) - 1:])
            text_right = ' '.join(text_right.split(' ')[:int((tokenizer.max_seq_len - aspect_len) / 2) + 1])
            text_left = ' '.join(text_left.split(' '))
            text_right = ' '.join(text_right.split(' '))
            text_raw = text_left + ' ' + aspect + ' ' + text_right

            text_raw_without_aspect_indices = tokenizer.text_to_sequence(text_left + " " + text_right)
```

Also, what would occur if I double the max_seq_len to lets say 160... in terms of memory requirements.
Would inferring also require similar machine specs after loading the trained model?

**Comment by yangheng95** [comment]
Thanks for reporting this, the text_right is not used in the BERT-based models, it was used in some models relying on left and right contexts. And this inferring script has not been tested on those non-BERT-based models. I will fix some problems later. 

The truncating of sentences is useful in low resources systems, If you use large max_len, it may help, however not very apparent.

Actually, it is difficult to integrate multilingual datasets and multiple models, I have not much time to test new code. Again, sorry for causing your inconvenience.

**Comment by yangheng95** [comment]
Please check here https://github.com/yangheng95/LC-ABSA/blob/dc27f9b09607e8125c49de9b00cd508a21b9b75a/modules/utils/data_utils_for_inferring.py#L276

**Comment by tusharkgerg** [comment]
thanks @yangheng95 that was helpful!

**Comment by yangheng95** [comment]
> thanks @yangheng95 that was helpful!

I am sorry that you may check the code again, I update the code because I ignored some cases that aspect is at the beginning or ending.

**Comment by tusharkgerg** [comment]
@yangheng95 I just ran the code. Seems to have fixed the truncation problem where aspect was in the beginning! :) Awesome Stuff 👍 
Also would be great to discuss how I am approaching the problem by using your model implementation.. In case you may have some spare time :p For reassurance.
