### ISSUE TITLE
[Failed to convert APC into ATEPC]

### ISSUE THREAD

**Issue by radya13rahman** [yangheng95/PyABSA#188]
![image](https://user-images.githubusercontent.com/48096736/166871214-4b6ad5c2-f970-4a17-9c0d-19adfe915fef.png)
I have used file.dat instead of file.dat.inference but it still fails? what do you think is wrong with my files and code?
![image](https://user-images.githubusercontent.com/48096736/166871319-7dd58468-8afb-4235-8bb3-069951774b63.png)

**Comment by radya13rahman** [comment]
![Uploading image.png…]()
my code

**Comment by radya13rahman** [comment]
here my code
![image](https://user-images.githubusercontent.com/48096736/166872051-59c08310-a9be-4e25-918d-2d2d681a1b4c.png)

**Comment by yangheng95** [comment]
Can you show one piece of your dataset?

**Comment by radya13rahman** [comment]
![image](https://user-images.githubusercontent.com/48096736/166888913-a9fcc9dd-1659-4bfd-93a1-0280bdc2cc71.png)

**Comment by yangheng95** [comment]
Can you update your version, the newer version may tell the specific error.

**Comment by yangheng95** [comment]
Or you can share your dataset with me via email, I will check the problem.

**Comment by radya13rahman** [comment]
I already send my dataset to your email

**Comment by radya13rahman** [comment]
Hello Mr.Heng
I've run my model successfully, but I want to improve the accuracy of the model do you have any suggestions for tuning the hyperparameters ?What should I do to improve the accuracy?

**Comment by radya13rahman** [comment]
![image](https://user-images.githubusercontent.com/48096736/167073885-f8e62da4-d600-4836-aca9-62d390e2fc92.png)
