### ISSUE TITLE
运行时出现了一个错误

### ISSUE THREAD

**Issue by yaoysyao** [yangheng95/PyABSA#190]
pyabsa\core\atepc\prediction\aspect_extractor.py", line 205, in extract_aspect
    extraction_res, sentence_res = self._extract(inference_source)
pyabsa\core\atepc\prediction\aspect_extractor.py", line 255, in _extract
    for i_batch, (input_ids_spc, input_mask, segment_ids, label_ids, polarity, valid_ids, l_mask) in enumerate(self.infer_dataloader):
TypeError: 'NoneType' object is not iterable

在使用已经预训练的模型进行情感分析时出现了这个错误，数据量很大，有三个文件，每个文件大概六七万的数据，里面的评论长度有些很长，每次读取一条进行分析然后保存，读取到某一条的时候出现了这个错误，出现这个错误的原因是什么？是不是因为数据量太大，还是评论长度太长导致？

**Comment by yangheng95** [comment]
出错的原因很多，具体需要调试，比如整个文本都等于aspect，使用try except跳过该文本，并把改文本反馈到这里我看一下

**Comment by yaoysyao** [comment]
> 出错的原因很多，具体需要调试，比如整个文本都等于aspect，使用try except跳过该文本，并把改文本反馈到这里我看一下

错误目前还没重现，等我重现一下，另外，出现了
AspectTooLongWarning -> <aspect: Salami Toscana , Goat Cheese & Black Olive Tapenade panini Prosciutto> is too long, <text: Get : House - made Italian Wedding Cookies Bread Pudding with Marsala & Citrus Mussels with Pancetta , Crme Fraiche & Marjoram Pass : Salami Toscana , Goat Cheese & Black Olive Tapenade panini Prosciutto Bread Balls I personally like the ambiance of this place . It gets really loud too if its crowded , and its pretty much always crowded at night , so if you want a little bit of a quieter setting , brave the cold and eat outside in the tented area and sit near the heater : ) The service here is really great - They didn ' t have any seats open when I called in , and they said they would call me back when one opened . My friends and I decided to walk around and go to a wine bar across the street and when our seat opened , they called us . I explained we were in the middle of a glass of wine and they told me they would hold our seats for up to 15 minutes , which I thought was great , considering how long the waiting list was . The servers were all very knowledgable about the wine they served and what would pair well with what you ordered , and they didn ' t try to push anything on us . I got the panini , and it was just okay , nothing special . Same goes for the bread balls . For both of those , they are perfectly okay , but I probably wouldn ' t get them again . I really liked the mussels and the wedding cookies and the bread pudding however . Great place , great atmosphere , and great service .>, <polarity: >
这个警告，对于结果有影响吗

**Comment by yangheng95** [comment]
这警告一定程度上是噪音，在最新版本中会被忽略

**Comment by yangheng95** [comment]
以上的意思是产生警告的example是噪音，会在训练时被忽略掉

**Comment by yaoysyao** [comment]
> 以上的意思是产生警告的example是噪音，会在训练时被忽略掉

我有一个问题，就是，如果我使用已经预训练好的模型，比如说预训练好的模型使用的是餐厅的评论数据集，然后我用来分析的数据集是房屋的评论，这样的话结果会不会有偏差？还是说，如果我的测试数据集是酒店的，那么我就要使用酒店数据集进行训练？训练的数据集和测试的数据集属于不同的类型，结果会有很大的偏差吗

**Comment by yangheng95** [comment]
会有偏差。但是如果这些数据集都包含在预训练的语料库中，那么这种差距就不明显（在DeBERTa中测试）

**Comment by yangheng95** [comment]
另外，默认的最长建模长度为80，兼顾效果和效率。你上面的警告的例子句子太长了
