### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by pepi99** [yangheng95/PyABSA#191]
When you have

apc_config_english.pretrained_bert = 'microsoft/deberta-v3-large'
apc_config_english.hidden_dim = 1024
apc_config_english.embed_dim = 1024
,
instead of defining these parameters, extract them from the model that you define in pretrained_bert.
Otherwise people might get confused and wonder what are the correct numbers

**Comment by yangheng95** [comment]
I did set this param according to the pretrained model config. Do you mean I should remove things like `apc_config_english.hidden_dim = 1024` in the demos?

**Comment by pepi99** [comment]
Yes, exactly. Because, for example, if I use deberta-v3-large instead of deberta-v3-base, I will get a matrix multiplication error if I also don't change apc_config_english.hidden_dim = 768 and apc_config_english.embed_dim = 768 both to 1024.

**Comment by yangheng95** [comment]
Yes, it is a great suggestion. I will check and update later, thank you very much.

**Comment by pepi99** [comment]
Thanks!
