### ISSUE TITLE
Train ATEPC model with different Optimizer

### ISSUE THREAD

**Issue by radya13rahman** [yangheng95/PyABSA#195]
![image](https://user-images.githubusercontent.com/48096736/168959701-973a3e17-e2eb-483a-bd59-c71cb3a6efba.png)
I plan to use another optimizer as a test in parameters. But when running the code suddenly there is an error,
![image](https://user-images.githubusercontent.com/48096736/168959807-1673193d-687b-4f98-acb8-906474e54694.png)
I've added adagrad to the code in question but still getting the same error
![image](https://user-images.githubusercontent.com/48096736/168959868-30442ca9-b3a7-4875-b83d-802c4a4abce3.png)
Do you have any suggestions regarding this?

**Comment by yangheng95** [comment]
Please try optimizer = torch.optim.Adagrad

**Comment by radya13rahman** [comment]
I already do that and get another error
![image](https://user-images.githubusercontent.com/48096736/169191099-8060f1f6-2bc6-49b8-b32c-c941c2a18e5a.png)

**Comment by yangheng95** [comment]
please check the latest version
