### ISSUE TITLE
Questions about training files

### ISSUE THREAD

**Issue by caibird2020** [yangheng95/PyABSA#196]
Hello blogger, I came from Zhihu and I am a newbie in the field of ABSA. I have a few questions:
1.There is no dataset in this project, do you need to download the relevant dataset from your homepage?
2.There is no main function and related parameter construction in the training file in the apc folder. I don't know how to write the main function and set the parameters. Do you have a complete training file that can run the model? If so, can you post it? give to me?2448481865@qq.com
![image](https://user-images.githubusercontent.com/64406248/169547288-2dd1ba26-c2f0-472b-aae4-5dadbb03533a.png)

**Comment by yangheng95** [comment]
You can find the usages from https://github.com/yangheng95/PyABSA/tree/release/demos/aspect_polarity_classification
