### ISSUE TITLE
Aspect term extraction & sentimental classification in Korean

### ISSUE THREAD

**Issue by seominseok48349278** [yangheng95/PyABSA#198]
Hi, I want to apply pyABSA to Korean data, what should I modify?
Do I just need to modify the configuration file after labeling the dataset? (https://github.com/yangheng95/ABSADatasets)

Should I specify the configuration file as _apc_config_multiple? Don't I need to change the tokenizer or word embedding?

**Comment by yangheng95** [comment]
Just need to change the pretrained model

**Comment by seominseok4834** [comment]
Are you asking me to change the checkpoint from get_aspect_extractor to multiple languages?

**Comment by seominseok48349278** [comment]
> Just need to change the pretrained model

Are you asking me to change the checkpoint from get_aspect_extractor to multiple languages?

**Comment by yangheng95** [comment]
I did not train a korean-based checkpoint, so you can try the multilingual checkpoint. If it does not wrok, please train our model on your own dataset. TO DO SO, set the pretrained_bert to a korean-based transformer model, e.g.,:
```python3
config = get_apc_config_base()
config.pretrained_bert='korean model from huggingface transformers'
 ```

**Comment by seominseok4834** [comment]
![스크린샷 2022-05-25 오후 8 03 52](https://user-images.githubusercontent.com/76269316/170248044-d1d79555-924d-4af7-b54e-ffcfdd0678c7.png)

The original dataset looks like this

**Comment by seominseok48349278** [comment]
> I did not train a korean-based checkpoint, so you can try the multilingual checkpoint. If it does not wrok, please train our model on your own dataset. TO DO SO, set the pretrained_bert to a korean-based transformer model, e.g.,:
> 
> ```python
> config = get_apc_config_base()
> config.pretrained_bert='korean model from huggingface transformers'
> ```

I'll build a dataset and try it.
Thank you

**Comment by seominseok4834** [comment]
> > Just need to change the pretrained model
> 
> Are you asking me to change the checkpoint from get_aspect_extractor to multiple languages?

I'm sorry, but what does B-ASP mean and I-ASP mean?

**Comment by seominseok48349278** [comment]
Hi. I tried what you said and it works. But the performance is not good.
When I execute extract_aspect, it is displayed as a character level, not a word level, and the result comes out.
Is this a tokenizer problem? Is it my data set?
When labeling a dataset, split it to a word level or the result is the same.

<img width="1093" alt="스크린샷 2022-05-31 오후 8 13 54" src="https://user-images.githubusercontent.com/76269316/171160876-8e9739d2-da70-446c-975a-d1204bdf1466.png">

**Comment by yangheng95** [comment]
which pretrained model do you use?

**Comment by seominseok48349278** [comment]
> which pretrained model do you use?

I used this. https://huggingface.co/monologg/kobert (https://github.com/monologg/KoBERT-Transformers)

**Comment by yangheng95** [comment]
The Koeran are tokenized into single words before extracting aspect terms: https://github.com/yangheng95/PyABSA/blob/ff0ce097307049d9a8b9a9b2c99836ec7afdad83/pyabsa/core/atepc/dataset_utils/atepc_utils.py#L20 , which result in this results. This tool has not considered other tokenization strategy for koearn.

**Comment by seominseok48349278** [comment]
> The Koeran are tokenized into single words before extracting aspect terms:
> 
> https://github.com/yangheng95/PyABSA/blob/ff0ce097307049d9a8b9a9b2c99836ec7afdad83/pyabsa/core/atepc/dataset_utils/atepc_utils.py#L20
> 
> , which result in this results. This tool has not considered other tokenization strategy for koearn.

All right, thank you for letting me know.
I'll find another way

**Comment by seominseok4834** [comment]
Hi, I'm back
Do I just need to modify the split_text method? What is the role of that method?
