### ISSUE TITLE
Train from checkpoint

### ISSUE THREAD

**Issue by pepi99** [yangheng95/PyABSA#199]
Hello,
I have a checkpoint saved in the checkpoints directory called "pyabsa_model". I want to train on top of this checkpoint, how can I do it? How can I obtain the apc_config of my checkpoint so I can pass it to new trainer to do training from checkpoint?

**Comment by yangheng95** [comment]
See demos/aspect_polarity_classification/train_based_on_checkpoint.py

**Comment by pepi99** [comment]
It worked. It was my bad, I had messed up my code (i had added different bert model).
Thanks
