### ISSUE TITLE
Error when running the code from cmd

### ISSUE THREAD

**Issue by Llannis** [yangheng95/PyABSA#2]
Hi, 

when I try to run locally

python train.py --model lcf_bert --dataset laptop --SRD 3 --local_context_focus cdm --use_single_bert=True
I get the following error

Model name 'bert_pretrained_models/laptop' not found in model shortcut name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc). Assuming 'bert_pretrained_models/laptop' is a path or url to a directory containing tokenizer files.
Didn't find file bert_pretrained_models/laptop. We won't load it.
Didn't find file bert_pretrained_models/laptop. We won't load it.
Didn't find file bert_pretrained_models/laptop. We won't load it.
Model name 'bert_pretrained_models/laptop' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc). We assumed 'bert_pretrained_models/laptop' was a path or url but couldn't find tokenizer filesat this path or url.
Model name 'bert_pretrained_models/laptop' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc). We assumed 'bert_pretrained_models/laptop' was a path or url but couldn't find any file associated to this path or url.
Model name 'bert_pretrained_models/laptop' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc). We assumed 'bert_pretrained_models/laptop' was a path or url but couldn't find any file associated to this path or url.
Traceback (most recent call last):
  File "train.py", line 260, in <module>
    single_train()
  File "train.py", line 254, in single_train
    ins = Instructor(opt)
  File "train.py", line 35, in __init__
    self.model = opt.model_class(bert, opt).to(opt.device)
    self.model = opt.model_class(bert, opt).to(opt.device)
  File "LCF-ABSA-master\models\lcf_bert.py", line 35, in __init__
    self.bert_SA = SelfAttention(bert.config, opt)
AttributeError: 'NoneType' object has no attribute 'config'

Any ideas how I can solve this issue?

Also can this script produe a prediction column with aspect/category and sentiment for the test data?

Thank you very much

**Comment by yangheng95** [comment]
Hello, this is a mistake because you may not download the domain-adapted BERT from [BERT-ADA](https://github.com/deepopinion/domain-adapted-atsc#release-of-bert-language-models-finetuned-on-a-specific-domain) and place it in the directory 'bert_pretrained_models/laptop' or 'bert_pretrained_models/restaurant'. If you are not convenient to download the domain-adapted BERT model, you can specify '--pretrained_bert_name bert-base-uncased' to train the models with the base BERT model. Besides, unfortunately, this repo didn't implement the script to predict the polarities in batch, but if you want DIY, then the inferring script provided by [Pytorch-ABSA](https://github.com/songyouwei/ABSA-PyTorch/blob/master/infer_example_bert_models.py) may help.
