### ISSUE TITLE
Probabilities of all classes for the APC

### ISSUE THREAD

**Issue by miguelwon** [yangheng95/PyABSA#200]
How can I get the softmax probabilities associated with each class for the sentiment classifier?

**Comment by yangheng95** [comment]
Just insert this line

```python
print({label:i_probs[self.opt.label_to_index[label]] for label in self.opt.label_to_index})
```
 before
https://github.com/yangheng95/PyABSA/blob/42aac7857fd6fb781184433f68063581ed1c3cc4/pyabsa/core/apc/prediction/sentiment_classifier.py#L239

**Comment by yangheng95** [comment]
<img width="455" alt="image" src="https://user-images.githubusercontent.com/51735130/172259031-ef5f8adf-3a84-48d5-a205-8ba0757b48da.png">
