### ISSUE TITLE
关于训练模型时加载数据集网络访问不到的问题

### ISSUE THREAD

**Issue by yaoysyao** [yangheng95/PyABSA#201]
由于需要讲代码部署到服务器进行训练，但是在训练的过程中需要从Gitee或者github下载数据集，由于网络限制的问题，无法下载数据集，请问可不可以手动下载[ABSADatasets](https://github.com/yangheng95/ABSADatasets)，然后通过配置代码指定数据集的方式，从而不需要重新下载数据集，请问有没有具体的例子代码？

**Comment by yangheng95** [comment]
可以，直接在工作目录下克隆数据集就可自动搜索数据集

**Comment by yaoysyao** [comment]
> 可以，直接在工作目录下克隆数据集就可自动搜索数据集

需要修改配置代码吗？直接把ABSADatasets目录放在和执行代码的同一级目录下就可以？

**Comment by yangheng95** [comment]
不用修改，放在同一级目录就行

**Comment by yaoysyao** [comment]
> 不用修改，放在同一级目录就行

好的，我试一下

**Comment by yangheng95** [comment]
如果直接运行存在问题可以将克隆出来的ABSADatasets下的datasets文件夹重命名为integrated_datasets，并移动到工作目录

**Comment by yaoysyao** [comment]
> 如果直接运行存在问题可以将克隆出来的ABSADatasets下的datasets文件夹重命名为integrated_datasets，并移动到工作目录

好的，问题已解决
