### ISSUE TITLE
how to apply ATEPC for korean?

### ISSUE THREAD

**Issue by seominseok48349278** [yangheng95/PyABSA#202]
Hi, I'm back
Do I just need to modify the split_text method? Could you tell me where to modify in order to officially apply for Korean?

**Comment by yangheng95** [comment]
This method preprocess the text into tokens, which is designed for mutilingual text.
If you only aims at Koeran, you can replace this method with your own preprocessing method.
Note that many pretrained models tokenize non-latin language into single words, in this case this method does not need to be replaced.

**Comment by seominseok4834** [comment]
Is there any modification for model training or inference?

**Comment by seominseok4834** [comment]
Hello, I can understand Korean well because I am modifying it as you said. Thank you.

By the way, I don't know when the split_text method is called in the code, can you tell me?

**Comment by seominseok4834** [comment]
Hello, I modified the split_text method as you said, so it works well. Thank you.

By the way, I don't know when the split_text method is called in the code, so could you tell me?

**Comment by seominseok4834** [comment]
Hello, I modified the split_text method as you said, so it works well. Thank you.

But, I don't know when the split_text method is called in the code, so could you tell me?

**Comment by seominseok48349278** [comment]
Hello, I modified the split_text method as you said, so it works well. Thank you.

But, I don't know when the split_text method is called in the code, so could you tell me?

I think it's being called in Aspect Extractor class, but I can't find it exactly

**Comment by yangheng95** [comment]
It can be used in two cases: 1. converting apc examples to atepc examples. 2. ATPC inference: https://github.com/yangheng95/PyABSA/blob/1382fbd6086a4944d1a41db978165bb22399c404/pyabsa/core/atepc/dataset_utils/data_utils_for_inference.py#L62

BTW, how do you modfiy this function? It will be useful for others facing same problem.

**Comment by seominseok4834** [comment]
Thanks for letting me know.

I modified the [41 line of split_text method](https://github.com/yangheng95/PyABSA/blob/1382fbd6086a4944d1a41db978165bb22399c404/pyabsa/core/atepc/dataset_utils/atepc_utils.py#L41)

https://gist.github.com/seominseok4834/67e3ed7bfd418161e87561f4ef964c24#file-split_text-py-L23

There are spaces in Korean too, so I think I can do it like this

Actually, there's a [morpheme in Korean](https://en.wiktionary.org/wiki/Category:Korean_morphemes), so if you go into detail, you have to change the concatenate part, so I think you can do it like this for now

If I have time later on, I'll try to fix this part

**Comment by seominseok48349278** [comment]
Thanks for letting me know.

I modified the [41 line of split_text method](https://github.com/yangheng95/PyABSA/blob/1382fbd6086a4944d1a41db978165bb22399c404/pyabsa/core/atepc/dataset_utils/atepc_utils.py#L41)

```python
    # Modification: Split and return even if Korean exists
    if not any(latin_lan) or latin_lan[2]:
        return text.split()
```
https://gist.github.com/seominseok4834/67e3ed7bfd418161e87561f4ef964c24#file-split_text-py-L23

There are spaces in Korean too, so I think I can do it like this

Actually, there's a [morpheme in Korean](https://en.wiktionary.org/wiki/Category:Korean_morphemes), so if you go into detail, you have to change the concatenate part, so I think you can do it like this for now

If I have time later on, I'll try to fix this part

**Comment by yangheng95** [comment]
Thanks, it is indeed difficult to preprocess multilingual text.

**Comment by seominseok4834** [comment]
That's right. Thank you so much for creating such a great open source framework.

If I have any questions, I will open the issue again.

**Comment by seominseok48349278** [comment]
That's right. Thank you so much for creating such a great open source framework.

If I have any questions, I will open the issue again.

**Comment by yangheng95** [comment]
I'd  prefer to share the credits with the community, and looking forward to your contribution :D

**Comment by yangheng95** [comment]
@seominseok4834  You may try the 1.16.2 version, it may do better on non-latin languages.

**Comment by seominseok48349278** [comment]
@yangheng95  Okay, I'll try it tomorrow

**Comment by seominseok48349278** [comment]
Hi. Can you tell me where to concatenate split words?

I'm going to fix it this time

**Comment by yangheng95** [comment]
Do you mean the split process in input, or output phase?

**Comment by seominseok48349278** [comment]
Split runs twice? The split I'm talking about is that this function is executed

https://github.com/yangheng95/PyABSA/blob/1382fbd6086a4944d1a41db978165bb22399c404/pyabsa/core/atepc/dataset_utils/atepc_utils.py#L20

I want to cut the sentence into morpheme units, calculate the score with it, and then combine it back into the original string.

**Comment by yangheng95** [comment]
https://github.com/yangheng95/PyABSA/blob/ffd1ff003b07bc29f9e11857ff05c4dd88305894/pyabsa/core/atepc/dataset_utils/data_utils_for_inference.py#L62

**Comment by yangheng95** [comment]
Is this what you want?

**Comment by seominseok4834** [comment]
I'm sorry. I made a mistake.

What I wanted to say was the part where the split words came back together. concatenate part

**Comment by seominseok48349278** [comment]
I'm sorry. I made a mistake.

What I wanted to say was the part where the split words came back together.

**Comment by yangheng95** [comment]
https://github.com/yangheng95/PyABSA/blob/ffd1ff003b07bc29f9e11857ff05c4dd88305894/pyabsa/core/atepc/prediction/aspect_extractor.py#L410

**Comment by seominseok48349278** [comment]
Oh, that's right. Thank you.
