### ISSUE TITLE
使用预训练好的模型进行情感分析时加载模型出现错误

### ISSUE THREAD

**Issue by yaoysyao** [yangheng95/PyABSA#204]
使用预训练好的模型进行情感分析时，加载模型的过程中出现错误，加载的模型为：001-1.4-Multil-APC-fast_lcf_bert_Multilingual_acc_94.72_f1_90.07.zip

出现的错误：Exception: 'APCConfigManager' object has no attribute 'num_labels' Fail to load the model from E:\AI\Pyabsa\1.4-20220505T111038Z-001\1.4\Multilingual\APC\Multil-APC-fast_lcf_bert_Multilingual_acc_94.72_f1_90.07\fast_lcf_bert_Multilingual_acc_94.72_f1_90.07! 

加载模型代码：aspect_extractor = ATEPCCheckpointManager.get_aspect_extractor(checkpoint=‘Multil-APC-fast_lcf_bert_Multilingual_acc_94.72_f1_90.07')

使用其他的模型就没有问题，如使用001-1.4-Multil-APC-fast_lcf_atepc_Multilingual_cdw_apcacc_88.96_apcf1_81.58_atef1_81.92.zip这个模型就没有问题

**Comment by yangheng95** [comment]
Apc和atepc模型的加载和使用是不同的，你应该在用atepc模型加载apc的checkpoint

**Comment by yaoysyao** [comment]
> Apc和atepc模型的加载和使用是不同的，你应该在用atepc模型加载apc的checkpoint

OK
