### ISSUE TITLE
通过加载已经预训练的模型进行情感分析时出现的错误

### ISSUE THREAD

**Issue by yaoysyao** [yangheng95/PyABSA#208]
通过使用已经预训练的模型进行情感分析时，出现了错误
加载模型代码：aspect_extractor = ATEPCCheckpointManager.get_aspect_extractor(checkpoint=‘/model/pyabsa/fast_lcf_atepc_Multilingual’)
模型的目录文件如下：
![image](https://user-images.githubusercontent.com/38513384/175916327-039987a1-395e-4666-9587-275818128c07.png)
模型我记得是以前通过谷歌网盘分享给我的
出现的错误：
Traceback (most recent call last):
  File "/ddnstor/imu_yaoyuanshuai/imu_yaoyuanshuai/python_code/PyFakeReview/./fake_review/main.py", line 39, in <module>
    need_emotion_data = pyabsa_emotion.emotion_data(need_emotion_data)
  File "/ddnstor/imu_yaoyuanshuai/imu_yaoyuanshuai/python_code/PyFakeReview/fake_review/pyabsa_emotion.py", line 27, in emotion_data
    aspect_extractor = load_pyabsa_model()
  File "/ddnstor/imu_yaoyuanshuai/imu_yaoyuanshuai/python_code/PyFakeReview/fake_review/pyabsa_emotion.py", line 18, in load_pyabsa_model
    aspect_extractor = ATEPCCheckpointManager.get_aspect_extractor(checkpoint=const.model_emotion_pyabsa)
  File "/home/imu_yaoyuanshuai/.conda/envs/yaoyuanshuai_python_3.9.12/lib/python3.9/site-packages/pyabsa/utils/pyabsa_utils.py", line 162, in decorated
    return f(*args, **kwargs)
  File "/home/imu_yaoyuanshuai/.conda/envs/yaoyuanshuai_python_3.9.12/lib/python3.9/site-packages/pyabsa/functional/checkpoint/checkpoint_manager.py", line 149, in get_aspect_extractor
    aspect_extractor = AspectExtractor(checkpoint, sentiment_map=sentiment_map, eval_batch_size=eval_batch_size)
  File "/home/imu_yaoyuanshuai/.conda/envs/yaoyuanshuai_python_3.9.12/lib/python3.9/site-packages/pyabsa/core/atepc/prediction/aspect_extractor.py", line 88, in __init__
    raise RuntimeError('Exception: {} Fail to load the model from {}! '.format(e, model_arg))

RuntimeError: Exception: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like microsoft/mdeberta-v3-base is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'. Fail to load the model from model/pyabsa/fast_lcf_atepc_Multilingual! 

查看错误发现为网络连接错误，但是通过询问服务器人员反馈说没有做网络限制，请问如果是这种情况下，能否可以通过离线模式进行使用，比如我下载某些文件放到服务器上，从而不在访问huggingface网站

**Comment by yangheng95** [comment]
你可以下载预训练模型。例如[microsoft/mdeberta-v3-base](https://huggingface.co/microsoft/mdeberta-v3-base/tree/main)放到本地目录，然后将模型目录命名为microsoft/mdeberta-v3-base从而尝试从本地磁盘加载预训练模型

**Comment by yaoysyao** [comment]
> 你可以下载预训练模型。例如[microsoft/mdeberta-v3-base](https://huggingface.co/microsoft/mdeberta-v3-base/tree/main)放到本地目录，然后将模型目录命名为microsoft/mdeberta-v3-base从而尝试从本地磁盘加载预训练模型

关于存放的路径有要求吗？比如说必须要放在某一个目录或者必须要放在项目目录

**Comment by yangheng95** [comment]
目录名为microsoft，mdeberta-v3-base下存放这个链接下https://huggingface.co/microsoft/mdeberta-v3-base/tree/main下载的预训练模型。即与目录结构与字符串‘microsoft/mdeberta-v3-base’匹配。

目前在推理阶段还没办法指定预训练模型路径，所以使用这个方法模拟加载本地的deberta，但我不确定是否奏效。 后续我会抽时间更新推理阶段的预训练模型下载失败解决方案

**Comment by yaoysyao** [comment]
> 目录名为microsoft，mdeberta-v3-base下存放这个链接下[https://huggingface.co/microsoft/mdeberta-v3-base/tree/main下载的预训练模型。即与目录结构与字符串‘microsoft/mdeberta-v3-base’匹配。](https://huggingface.co/microsoft/mdeberta-v3-base/tree/main%E4%B8%8B%E8%BD%BD%E7%9A%84%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E3%80%82%E5%8D%B3%E4%B8%8E%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E4%B8%8E%E5%AD%97%E7%AC%A6%E4%B8%B2%E2%80%98microsoft/mdeberta-v3-base%E2%80%99%E5%8C%B9%E9%85%8D%E3%80%82)
> 
> 目前在推理阶段还没办法指定预训练模型路径，所以使用这个方法模拟加载本地的deberta，但我不确定是否奏效。 后续我会抽时间更新推理阶段的预训练模型下载失败解决方案

好的，我尝试一下，可以考虑通过手动指定目录的方式，因为在服务器和本地目录有所差别，不如直接由用户指定目录

**Comment by yangheng95** [comment]
请尝试pip install 1.15.6a0，在checkpointmanager.get_sentiment_classifier(..., offline=True)。在此之前需要下载同名预训练模型

**Comment by yangheng95** [comment]
@yaoysyao 感谢测试！
