### ISSUE TITLE
使用atepc分析时有些文本无法获取结果

### ISSUE THREAD

**Issue by yaoysyao** [yangheng95/PyABSA#216]
你好，冒昧打扰，作者辛苦了，谢谢维护这个项目，在使用过程中遇到如下问题：
版本：1.16.5
文本如下：
Let me begin by saying that there are two kinds of people, those who will give the Tokyo Hotel 5 stars and rave about it to everyone they know, or... people who can't get past the broken phone, blood stains, beeping fire alarms, peg-legged receptionist, lack of water pressure, cracked walls, strange smells, questionable elevator, televisions left to die after the digital conversion, and the possibility that the air conditioner may fall out the window at any moment. That being said, I whole-heartedly give the Tokyo Hotel 5 stars. This is not a place to quietly slip in and out of with nothing to show but a faint memory of the imitation Thomas Kinkade painting bolted to the wall above your bed. And, there is no continental breakfast or coffee in the lobby. There are a few vending machines, but I'm pretty sure they wont take change minted after 1970. Here your senses will be assaulted, and after you leave you will have enough memories to compete with a 1,000 mile road-trip. I beg anyone who is even mildly considering staying here to give it a chance. The location is prime. We were able to walk down Michigan Ave and the river-walk in the middle of the night, all without straying too far from the hotel. There is a grocery store a block away and parking (which may cost more that your hotel room) across the street. Besides, this place is cheap. Super-cheap for downtown Chicago. The closest price we found in the area was four times as expensive. But, be sure to grab some cash. They don't accept credit cards. Some rules though: - Say hello to Clifton Jackson, the homeless guy by Jewel-Osco. - Buy him a drink, some chicken and look him up on Facebook. - Stay on the 17 floor. All the way at the top. - Go out the fire escape (be sure to prop the door open or you'll have a looong walk down) - Be very very careful. - Explore. (Yes, that ladder will hold your weight) - Be very very careful. - Don't be alarmed by any weird noises you hear. - Spend the night on the roof. 17 stories up, in the heart of Chicago. - Write your own Yelp review. I want to see that others are getting the Tokyo Hotel Experience. - Check out is at noon. Be sure to drink lots of water. - Spend the next day hung over. And... Please be careful on the roof.
使用的预训练好的模型：fast_lcf_atepc_Multilingual_cdw_apcacc_88.96_apcf1_81.58_atef1_81.92
得到的结果：'aspect': [], 'position': [], 'sentiment': [], 'probs': [], 'confidence': []
从结果看出，无法分析文本的细粒度情感，请问这种情况出现的原因是文本造成的还是模型的原因
关于预训练好的模型，我在hugging face上看到你有更新一些checkpoint，请问那些模型是不是可以直接用来加载使用？

**Comment by yaoysyao** [comment]
还有一些文本经过分析后得到的结果是可以获取情感，但是aspect为空

**Comment by yangheng95** [comment]
文本太长了，太长的文本请分几段输入，multilingual-256-2这个checkpoint目前可以处理大约200个词的文本，是目前训练的建模长度最长的模型。不清楚你说的什么意思，使用available_checkpoints()可以查看当前可用的checkpoints。

**Comment by yangheng95** [comment]
> 还有一些文本经过分析后得到的结果是可以获取情感，但是aspect为空

请给出一些例子，谢谢

**Comment by yaoysyao** [comment]
> > 还有一些文本经过分析后得到的结果是可以获取情感，但是aspect为空
> 
> 请给出一些例子，谢谢

感谢回答，经过测试，发现这个问题也是由于句子过长造成的，太长的文本分段输入，是按照长度分段还是按照标点符号句号分段？在推理的过程中是否考虑到了上下文？还是单纯地考虑每个句子，如果按照长度分段或者按照标点符号分段输入是否影响最终的推理结果？

**Comment by yangheng95** [comment]
> > > 还有一些文本经过分析后得到的结果是可以获取情感，但是aspect为空
> > 
> > 
> > 请给出一些例子，谢谢
> 
> 感谢回答，经过测试，发现这个问题也是由于句子过长造成的，太长的文本分段输入，是按照长度分段还是按照标点符号句号分段？在推理的过程中是否考虑到了上下文？还是单纯地考虑每个句子，如果按照长度分段或者按照标点符号分段输入是否影响最终的推理结果？

不会结合上下文，因为模型的应用场景是短评论，不是长文本

**Comment by yaoysyao** [comment]
> > > > 还有一些文本经过分析后得到的结果是可以获取情感，但是aspect为空
> > > 
> > > 
> > > 请给出一些例子，谢谢
> > 
> > 
> > 感谢回答，经过测试，发现这个问题也是由于句子过长造成的，太长的文本分段输入，是按照长度分段还是按照标点符号句号分段？在推理的过程中是否考虑到了上下文？还是单纯地考虑每个句子，如果按照长度分段或者按照标点符号分段输入是否影响最终的推理结果？
> 
> 不会结合上下文，因为模型的应用场景是短评论，不是长文本

如果这样说的话，那么按照标点符号来划分每一个句子可能比较好，而不是单纯地按照长度划分，请问有测试过按照哪种方式划分准确率最好这个问题吗？

**Comment by yaoysyao** [comment]
> 文本太长了，太长的文本请分几段输入，multilingual-256-2这个checkpoint目前可以处理大约200个词的文本，是目前训练的建模长度最长的模型。不清楚你说的什么意思，使用available_checkpoints()可以查看当前可用的checkpoints。

还有一个问题，这个200个词仅仅说的是200个单词吗，是否包括空格，标点符号等非单词

**Comment by yangheng95** [comment]
第一个问题请自行测试。200个词是估计，最大建模长度其实是256，包括符号，但一些词语分此后会拆分为多个token，所以尽量控制在200词以内。

**Comment by yaoysyao** [comment]
> 第一个问题请自行测试。200个词是估计，最大建模长度其实是256，包括符号，但一些词语分此后会拆分为多个token，所以尽量控制在200词以内。

好的，谢谢

**Comment by yaoysyao** [comment]
还是上面那个例子，我发现按照句号分割成多个小文本还是有些很长，那么是否可以按照逗号来分段文本，最后把结果汇总起来，这样做在推理的过程中对结果会有影响吗？理论上可以这样做吗

**Comment by yangheng95** [comment]
可以试试，影响应该不大

**Comment by yaoysyao** [comment]
> 可以试试，影响应该不大

OK
