### ISSUE TITLE
Minor error of aspect term extraction

### ISSUE THREAD

**Issue by DorisFangWork** [yangheng95/PyABSA#217]
Hi Author,

I used fast_lcfs_atepc model to train my own dataset about "Immigration", the result is pretty good:
- Aspect sentiment classification accuracy: 80.54%
- Aspect sentiment classification F1: 80.76%
- Aspect term extraction F1: 97.84%

However, I noticed minor errors.
Original sentence:"and gov **keeps** importing more wp and ep , and they stay like 5 person in 1 room to survive and depress everyone else ' s wages"
Results from model inference and inference JSON file not match, position should be [6] and [8], and "keeps" is an entire word.

![image](https://user-images.githubusercontent.com/72718674/182850724-f3284e2c-230c-4a50-bc38-e8dc7f46fdb5.png)
![image](https://user-images.githubusercontent.com/72718674/182851729-54d4e3c3-56c1-4cbe-b926-2c533d4f98ea.png)

**Comment by yangheng95** [comment]
Hi,
Thanks for your report. Would you share your dataset for debugging?
