### ISSUE TITLE
Help on training using a Chinese corpus 

### ISSUE THREAD

**Issue by harrywang** [yangheng95/PyABSA#218]
Hi, Thanks for the great work!

I wonder whether you can give us some pointers on how to train using a Chinese corpus.

1. which Chinese base pre-train Bert model do you suggest? We see `atepc_config.pretrained_bert = 'microsoft/deberta-v3-base'` is used in the example code but don't know whether a Chinese base model is better for our situation.
2. should we train from an existing checkpoint? such as:
```
aspect_extractor = ATEPCTrainer(config=atepc_config,
                                dataset=dataset_path,
                                from_checkpoint='multilingual2',  # set checkpoint to train on the checkpoint.
                                checkpoint_save_mode=1,
                                auto_device=True
                                ).load_trained_model()
```

We are still learning about this topic and your framework  - sorry for stupid questions if any :).

**Comment by yangheng95** [comment]
You can try `microsoft/mdeberta-v3-base` in Q1. It is not necessary to resume from an existing ckpt, but you can try resume from `multilingual-256-2`

**Comment by harrywang** [comment]
Thanks a lot for the quick reply!
