### ISSUE TITLE
google collab  code not working or no update?

### ISSUE THREAD

**Issue by akashAD98** [yangheng95/PyABSA#219]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/62583018/185737779-a8b5722c-d3f9-471d-b942-15453ec91d23.png">

<img width="665" alt="image" src="https://user-images.githubusercontent.com/62583018/185737745-434a1c2e-4025-4005-9cbe-9e6a48cbaa9a.png">

**Comment by yangheng95** [comment]
Hi, the from_local args is depricated, please remove it and select a available checkpoint before use.

**Comment by akashAD98** [comment]
got it @yangheng95
