### ISSUE TITLE
请问下中文的数据集是如何生成的？

### ISSUE THREAD

**Issue by shikimoon** [yangheng95/PyABSA#22]
我注意到貌似是用bert做tokenize后用空格间隔生成的，那如果里面含有英文呢，也是一样的吗

**Comment by yangheng95** [comment]
这个库提供的数据集没有类似的情况，其实不一定需要用空格给中文分词，也可以把空格去掉。不管文本里面有没有英文，BERT分词中文应该都采用单字分词

**Comment by shikimoon** [comment]
> 这个库提供的数据集没有类似的情况，其实不一定需要用空格给中文分词，也可以把空格去掉。不管文本里面有没有英文，BERT分词中文应该都采用单字分词

我试了下不用空格确实结果一样。谢谢
