### ISSUE TITLE
regrad evaluation

### ISSUE THREAD

**Issue by Astudnew** [yangheng95/PyABSA#222]
Hello, thank you for sharing this work.
Regarding the evaluation of LCF- ATEPC model why do you just use F1 and accuracy for evaluation why yo do not use Class-wise performance why do not use class-wise precision, recall, and F1 score? can we use these performance metrics with LCF-ATEPC
Thanks

**Comment by yangheng95** [comment]
You can try setting config.show_metric=True

**Comment by Astudnew** [comment]
Thanks but these metrics (class-wise precision, recall, and F1 score) are important for LCF-ATEPC performance evaluation (for ATE and APC)? or F1 and Accuracy are sufficient as in your paper( A multi-task learning model for Chinese-oriented aspect polarity classification and aspect term extraction)?

**Comment by yangheng95** [comment]
Actually it depends on what you think, important or not
