### ISSUE TITLE
kwargs in AspectExtractor constructor are removed with kwargs.pop() and cannot be reused

### ISSUE THREAD

**Issue by gfigueroa** [yangheng95/PyABSA#229]
- The constructor of the `AspectExtractor` class under `pyabsa/core/atepc/prediction/aspect_extractor.py` has `**kwargs` argument.
- However, each key/value pair in `kwargs` is removed when using `kwargs.pop` and cannot be reused.
- This should be changed to `kwargs.get`, especially in the case of `if kwargs.get('offline', False)`, since it is mentioned twice in the code.
- This bug doesn't allow me to use offline mode correctly.

**Comment by yangheng95** [comment]
Oops, I will fix it soon

**Comment by yangheng95** [comment]
You can try 1.16.19a0, please tell me if it works. Thanks very much

**Comment by gfigueroa** [comment]
@yangheng95 awesome, that worked, thanks!
