### ISSUE TITLE
Problem with Aspect_Extraction

### ISSUE THREAD

**Issue by Joostb** [yangheng95/PyABSA#232]
Hey, thanks for your extremely useful library!

I was trying to run the make_dataset code, but I ran into some problems. I looked into the functionality of the code, and I think the problem lies with the call to extract_aspect. Which is basically the same as in this demo: https://github.com/yangheng95/PyABSA/blob/bffd723245aa2c2d0ad224d14955de5c5cd5987c/demos/aspect_term_extraction/extract_aspects_multilingual.py

(There is also a small problem in the demo, which is easy to fix:  rename AspectExtractor to aspect_extractor).

But even when I change this, I get a `list index out of range` error (it occurs here: https://github.com/yangheng95/PyABSA/blob/9599e24ab7bcabadef36d3657a4802bd50443e49/pyabsa/core/atepc/prediction/aspect_extractor.py#L417)

**Comment by yangheng95** [comment]
I will fix it later. Before that you can install early versions which may work.

**Comment by yangheng95** [comment]
Fixed
