### ISSUE TITLE
在已训练的中文模型上进行增量训练的问题

### ISSUE THREAD

**Issue by stay-leave** [yangheng95/PyABSA#233]
大佬你好！我想用自己的数据集再次训练你发布的模型，但是遇到了
`Error(s) in loading state_dict for FAST_LCF_ATEPC:
	size mismatch for dense.weight: copying a param with shape torch.Size([2, 768]) from checkpoint, the shape in current model is torch.Size([3, 768]).
	size mismatch for dense.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([3]).`
的错误。
我的代码是：
`from pyabsa import ATEPCCheckpointManager
from pyabsa.functional import ATEPCModelList
from pyabsa.functional import Trainer, ATEPCTrainer
from pyabsa.functional import ABSADatasetList
from pyabsa.functional import ATEPCConfigManager

checkpoint_path = 'fast_lcf_atepc_Chinese_cdw_apcacc_96.0_apcf1_94.96_atef1_91.34'  # pending update

config = ATEPCConfigManager.get_atepc_config_chinese()
print(config)
config.model = ATEPCModelList.FAST_LCF_ATEPC#
print(config)
config.evaluate_begin = 4
config.num_epoch = 5

#TShirt = ABSADatasetList.TShirt
chinese_data = '100.CustomDataset'#改成自己的数据集进行增量训练

aspect_extractor = Trainer(config=config,
                           dataset=chinese_data,
                           from_checkpoint=checkpoint_path,
                           checkpoint_save_mode=1,
                           auto_device=True
                           ).load_trained_model()`
使用的是最新版pyABSA库。请问该怎么修改？非常感谢！

**Comment by yangheng95** [comment]
这是因为标签数量不一样，中文模型只有两类，你可以用multilingual，效果也不错

**Comment by stay-leave** [comment]
好的，谢谢大佬
