### ISSUE TITLE
Checkpoint:multilingual2 is not found是什么原因呀

### ISSUE THREAD

**Issue by yier2333** [yangheng95/PyABSA#234]

**Comment by yangheng95** [comment]
可能是存储空间不够删除了，请使用available_checkpoints()查看可用模型

**Comment by yier2333** [comment]
> 可能是存储空间不够删除了，请使用available_checkpoints()查看可用模型

我后来发现原因是因为默认安装的是cpu版本的torch，安装gpu版本就不会报错，但是会报protobuf问题，改为protobuf==3.19.0就好了，作者大大可以把requirements.txt放出来，然后extract_aspect希望可以开放infer_batch_size接口，因为_extract默认256我的小破机器内存不足了呜呜呜，我强制改了代码，最后灰常谢谢作者，这个中文的开源项目真少。

**Comment by yier2333** [comment]
解决啦

**Comment by yangheng95** [comment]
> > 可能是存储空间不够删除了，请使用available_checkpoints()查看可用模型
> 
> 我后来发现原因是因为默认安装的是cpu版本的torch，安装gpu版本就不会报错，但是会报protobuf问题，改为protobuf==3.19.0就好了，作者大大可以把requirements.txt放出来，然后extract_aspect希望可以开放infer_batch_size接口，因为_extract默认256我的小破机器内存不足了呜呜呜，我强制改了代码，最后灰常谢谢作者，这个中文的开源项目真少。

可以在get_aspect_extractor()函数中指定eval_batch_size
