### ISSUE TITLE
模型文件读取失败

### ISSUE THREAD

**Issue by stay-leave** [yangheng95/PyABSA#235]
大佬您好！今天我把版本更新到2.0，发现可以很快地下载您训练好的模型了。但是在执行预测脚本的时候遇到了问题。在使用多语言模型时，报出bug：
`Exception: Unable to load vocabulary from file. Please check that the provided vocabulary is accessible and not corrupted. Fail to load the model from checkpoints\ATEPC_MULTILINGUAL_CHECKPOINT\fast_lcf_atepc_Multilingual_cdw_apcacc_78.08_apcf1_77.81_atef1_75.41! `

我的报错代码如下：
`aspect_extractor = ATEPC.AspectExtractor('multilingual')`

但是我将多语言换成中文可以正常输出预测结果。
下载下来的模型文件如下所示：
![image](https://user-images.githubusercontent.com/58450966/201508189-2ec192fb-a443-4eb7-b3f2-229de48ef884.png)

**Comment by yangheng95** [comment]
你先退回2.0.0试试

**Comment by stay-leave** [comment]
应该是我电脑的问题，我在租的云显卡上跑是正常的。谢谢大佬！
