### ISSUE TITLE
1.6.18升级到最新版后的问题

### ISSUE THREAD

**Issue by yaoysyao** [yangheng95/PyABSA#236]
你好，
        原本我用的是1.16.18版本，做情感分析时采用的是加载从huggingface上下载的已经预训练好的模型，模型地址：https://huggingface.co/spaces/yangheng/Multilingual-Aspect-Based-Sentiment-Analysis/tree/main/checkpoint/Multilingual/ATEPC，
加载模型的代码为：

`
from pyabsa import ATEPCCheckpointManager
`
`
def load_pyabsa_model():
    aspect_extractor = ATEPCCheckpointManager.get_aspect_extractor(checkpoint=const.model_emotion_pyabsa)
    return aspect_extractor
`

升级到最新版后，我下载了最新的源码，似乎找不到ATEPCCheckpointManager这个类，也搜索不到get_aspect_extractor这个方法，请问最新版的如何加载本地已经预训练的模型？
谢谢

**Comment by yangheng95** [comment]
请查看examplev2中的新的示例，v2的文档我会陆续更新

**Comment by yaoysyao** [comment]
> 请查看examplev2中的新的示例，v2的文档我会陆续更新

好的，谢谢了
