### ISSUE TITLE
GPU consumption jumping up and down

### ISSUE THREAD

**Issue by JulesBelveze** [yangheng95/PyABSA#24]
Hi there,
I'm using your `LCA_BERT` on a custom dataset and after experiencing a relatively slow training I dug into the GPU consumption and it seems like the current implementation is not fully leveraging GPUs as the GPU consumption is jumping up and down (see image below).

![Screenshot 2021-05-06 at 17 25 32](https://user-images.githubusercontent.com/32683010/117324424-11ace800-ae90-11eb-9007-116a24c9ea68.png)

I'm trying to investigate, but have you already experienced such a behavior?
Cheers

**Comment by yangheng95** [comment]
Sorry, I didnt notice this problem, maybe I will review the code soon and correct it.
