### ISSUE TITLE
Aspect_Sentiment_Classification.ipynb error

### ISSUE THREAD

**Issue by Rad710** [yangheng95/PyABSA#242]
When running the notebook, the following error shows up

<img width="878" alt="Screenshot 2022-12-19 003101" src="https://user-images.githubusercontent.com/85505832/208308994-67a3b5fe-4067-42ed-8b36-10da1a77c982.png">

**Comment by yangheng95** [comment]
Which version and optimizer do you use?

**Comment by Rad710** [comment]
I use version 2.0.19 and I'm just running the provided example of Aspect_Sentiment_Classification.ipynb

**Comment by yangheng95** [comment]
Thanks for your reply, wich versions of torch and transformers do you use?

**Comment by Rad710** [comment]
I use torch 1.7.1 and transformers is 4.25.1

**Comment by yangheng95** [comment]
The v2.0 introduces a maximize option, which is only available in torch 1.12 or 1.13.
