### ISSUE TITLE
Could not fidn Colab tutorials

### ISSUE THREAD

**Issue by rukshar69** [yangheng95/PyABSA#243]
I was going through [Colab tutorials](https://github.com/yangheng95/PyABSA/blob/v2/readme/tutorial_readme.md) section and tried to access [APC](https://github.com/yangheng95/PyABSA/blob/v2.0.0/examples-v2/aspect_polarity_classification/Aspect_Sentiment_Cassification.ipynb) and [ATEPC](https://github.com/yangheng95/PyABSA/blob/v2.0.0/examples-v2/aspect_term_extraction/Aspect_Term_Extractor.ipynb). In both cases, I get **Page not found** error. Where may I find the collab notebook tutorials?

**Comment by yangheng95** [comment]
you can find them at [APC](https://github.com/yangheng95/PyABSA/blob/v2/examples-v2/aspect_polarity_classification/Aspect_Sentiment_Cassification.ipynb) and [ATEPC](https://github.com/yangheng95/PyABSA/blob/v2/examples-v2/aspect_term_extraction/Aspect_Term_Extractor.ipynb).
