### ISSUE TITLE
关于数据集格式.xml.seg.graph的生成问题

### ISSUE THREAD

**Issue by caibird2020** [yangheng95/PyABSA#245]
大佬您好，我想使用自己的数据集进行训练，可是我的文件是txt格式的，但是训练的文件是.xml.seg和.xml.seg.graph格式，请问我如何得到这两种格式的数据呢？简单的改一下文件后缀可以吗，还是说要特殊的代码进行转换？

**Comment by yangheng95** [comment]
你可以截图给我看一下你现有的数据，目前不知道你的数据是啥样的

**Comment by caibird2020** [comment]
数据集是我找的中文相机数据集
![image](https://user-images.githubusercontent.com/64406248/210537088-32833378-d11d-4b7b-beec-64c19f69526a.png)

**Comment by yangheng95** [comment]
Graph数据呢？

**Comment by caibird2020** [comment]
这些数据是我运行songyouwei大佬的项目里自带的英文数据集
![image](https://user-images.githubusercontent.com/64406248/210542809-d86e53bf-612e-402b-8707-59c4513ecbd0.png)
![image](https://user-images.githubusercontent.com/64406248/210542843-8d8ebd93-f36f-4c10-9e6c-bb4aeaef4005.png)
![image](https://user-images.githubusercontent.com/64406248/210542871-57c6e13e-6a6a-41fd-982d-6561cdd98a7f.png)

**Comment by yangheng95** [comment]
不用管这个，框架会自动抽取的，你只需要关心数据集的命名方式就行，参照absadatasets这个库命名

**Comment by caibird2020** [comment]
谢谢大佬，但是我不是很懂，“数据集的命名方式按照ABSAdatasets库来命名“，ABSAdatasets库里的数据集命名如下
![image](https://user-images.githubusercontent.com/64406248/210545978-75eef42e-8865-43de-8dd0-bba7cbf4227e.png)
也就是说我下载的中文数据集要命名为camera_Train_Gold.xml.seg这样就行了吗

**Comment by yangheng95** [comment]
最后要加后缀.apc

**Comment by caibird2020** [comment]
谢谢大佬，我再琢磨琢磨

**Comment by caibird2020** [comment]
大佬，我还想请教一下，我在运行dependency_graph.py时报错，显示没有'en_core_web_sm'这个模块，请问'en_core_web_sm'起到什么作用呢，如何解决这个问题呢？
![image](https://user-images.githubusercontent.com/64406248/210578714-61f1ea30-2559-4c88-ba6c-53c964847208.png)

**Comment by yangheng95** [comment]
这是spacy提供的模型，可以抽取句法等信息。中文应该下载对应的包，这个是针对英文的。
