### ISSUE TITLE
problem running aspect extractor model due to missing state_dict keys when loading model from checkpoint

### ISSUE THREAD

**Issue by 3awny** [yangheng95/PyABSA#247]
**please see errors below**
```
RuntimeError: Exception: Error(s) in loading state_dict for FAST_LCF_BERT:
        Missing key(s) in state_dict:
```
**followed by:**
`size mismatch for dense.weight: copying a param with shape torch.Size([3, 3]) from checkpoint, the shape in current model is torch.Size([3, 768]). Fail to load the model from checkpoints/APC_MULTILINGUAL_CHECKPOINT/fast_lcf_bert_Multilingual_acc_82.66_f1_82.06! `

Im trying to run the Aspect Extractor as per your provided example:
```
        # you can view all available checkpoints by calling available_checkpoints()
        checkpoint_map = available_checkpoints(show_ckpts=True)
        aspect_extractor = ATEPC.AspectExtractor('multilingual',
                                         auto_device=True,  # False means load model on CPU
                                         cal_perplexity=True,
                                         )


        # instance inference
        aspect_extractor.predict(['I love this movie, it is so great!'],
                                save_result=True,
                                print_result=True,  # print the result
                                ignore_error=True,  # ignore the error when the model cannot predict the input
                                )
```

Please let me know if you have any advice on this. Thank you in advance

**Comment by yangheng95** [comment]
Which version of PyABSA do you use?

**Comment by yangheng95** [comment]
It seems you are using a APC ckpt to load an ATEPC predictor. So you can remove the APC ckpt and try again

**Comment by 3awny** [comment]
OK, it's working now after I deleted the APC checkpoint. It's because I previously ran the APC model and it downloaded checkpoint it seems. Which the ATEPC was trying to load from path. Thanks! 

PS. im using latest PyABSA version.

Great stuff by the way :)
