### ISSUE TITLE
How to use my own dataset for trainer?

### ISSUE THREAD

**Issue by Winnieliu0504** [yangheng95/PyABSA#248]
I referred to this document: 
[PyABSA]/[examples-v2]/[aspect_polarity_classification]/aspect_polarity_classification)/Aspect_Sentiment_Cassification.ipynb

and tried to pass my own dataset to PyABSA trainers, but I can't use this code:
`my_dataset = DatasetItem("my_dataset", ["my_dataset1", "my_dataset2"])`

I wrote this for my data:
`my_dataset = DatasetItem("131.Electronics", ["131.Electronics"])`

and the error shows that it cannot find dataset: 131.Electronics

What should I do to use my own dataset to train the model? Thanks!

**Comment by yangheng95** [comment]
Your datasets should be located in the integrated_datasets/{apc|atepc}_datasets/131.Electronics. If it fails again, you can paste your code here, I will help you.

**Comment by Winnieliu0504** [comment]
I've solve this issue. Thank you so much!

**Comment by Winnieliu0504** [comment]
I've solve this issue. Thank you so much!
