### ISSUE TITLE
Can't import pyabsa in colab

### ISSUE THREAD

**Issue by Skipper91** [yangheng95/PyABSA#257]
Hey there. I can't import pyabsa in my colab notebook. Everytime i try, it is crashing. Not totaly sure, what causes the crash.

**Comment by Skipper91** [comment]
I tried to follow this tutorial: https://www.youtube.com/watch?v=-UEU-HGjUyQ.

**Comment by yangheng95** [comment]
You need to downgrade to 1.16.27
