### ISSUE TITLE
atepc_result = aspect_extractor.batch_predict() can not run

### ISSUE THREAD

**Issue by kekekula** [yangheng95/PyABSA#260]
**When I run the code below：**
atepc_result = aspect_extractor.batch_predict(target_file=inference_source,  #
                                              save_result=True,
                                              print_result=True,  # print the result
                                              pred_sentiment=True,  # Predict the sentiment of extracted aspect terms
                                              )
**It fails and gives the following message：**
Exception: Cmd('git') not found due to: FileNotFoundError('[WinError 2] 系统找不到指定的文件。')
  cmdline: git clone -v --branch=v2.0 --depth=1 -- https://gitee.com/yangheng95/ABSADatasets.git C:\Users\ADMINI~1\AppData\Local\Temp\tmpx8mwz05b. Fail to clone ABSADatasets, please check your connection

Can anyone help me solve this problem? please....

**Comment by yangheng95** [comment]
需要先安装git： https://git-scm.com/download/win

**Comment by kekekula** [comment]
成功了！超级感谢！
