### ISSUE TITLE
Inference Dataset 疑問

### ISSUE THREAD

**Issue by Winnieliu0504** [yangheng95/PyABSA#261]
想請問一下這個套件在 Inference的步驟是否可以只讀資料集中的某些欄位(如圖一), 並且在 Inference之後增加其他欄位以便做後續分析？

<img width="1035" alt="截圖 2023-03-01 下午9 52 02" src="https://user-images.githubusercontent.com/41277734/222158598-34331a12-bc4a-4f42-ad36-b01dab1c6ec3.png">

**如上圖，在Inference時只讀 Online Review - Inference 和 Label 欄位** 

**結果輸出之後加上 Customer Rating 的欄位，如下：**
<img width="771" alt="截圖 2023-03-01 下午10 04 32" src="https://user-images.githubusercontent.com/41277734/222163101-540fcdfb-48f2-4a63-a975-0790065ccc33.png">

如果要得到以上的結果，是否只能用迴圈一筆一筆做 Inference，而沒辦法用Batch Inference的方式呢？感謝！

**Comment by yangheng95** [comment]
暂时不支持

**Comment by Winnieliu0504** [comment]
了解，謝謝！
