### ISSUE TITLE
 Missing key(s) in state_dict - LCF_ATEPC

### ISSUE THREAD

**Issue by jamiehshare** [yangheng95/PyABSA#263]
Hi @yangheng95,

Thanks for all of your effort and time put into PyABSA.

I've been trying to follow the ATEPC tutorial from [here](https://github.com/yangheng95/PyABSA/blob/v2/examples-v2/aspect_term_extraction/Aspect_Term_Extractor.ipynb), however I always come stuck when attempting to train from a checkpoint. 

I am trying to run (from the tutorial):

```
trainer = ATEPC.ATEPCTrainer(
    config=config,
    dataset=dataset,
    from_checkpoint="english",
    # if you want to resume training from our pretrained checkpoints, you can pass the checkpoint name here
    auto_device=DeviceTypeOption.AUTO,
    path_to_save=None,  # set a path to save checkpoints, if it is None, save checkpoints at 'checkpoints' folder
    checkpoint_save_mode=ModelSaveOption.SAVE_MODEL_STATE_DICT,
    load_aug=False,
    # there are some augmentation dataset for integrated datasets, you use them by setting load_aug=True to improve performance
)
```
and am constantly met with an error message of: 

`RuntimeError: Error(s) in loading state_dict for LCF_ATEPC:
        Missing key(s) in state_dict: "bert4local.embeddings.position_ids",` 

This appears similar to issue #247, but I'm only working with ATEPC ckpt/predictors (not APC). I receive the output message `Checkpoint downloaded at: checkpoints/ATEPC_ENGLISH_CHECKPOINT/fast_lcf_atepc_English_cdw_apcacc_82.36_apcf1_81.89_atef1_75.43` so am confident the appropriate checkpoint has been downloaded.

If it helps, I am using PyABSA 2.0.28.

Do you have any advice on how I may try to fix this?

Thank you very much in advance

**Comment by yangheng95** [comment]
It maybe checkpoint searching problem or version problem. You don't need to train from a checkpoint, just try comment the from_checkpoint

**Comment by jamiehshare** [comment]
Okay thank you, I'll comment out the from_checkpoint.

If I wanted to fine-tune the pretrained model to a specific use case using my own data, I'd need to train from the pretrained checkpoint though right? This was what I will need to do, but was just trying to follow the tutorial to start with.

**Comment by yangheng95** [comment]
Fine-tuning from a checkpoint will accelerate your training process, however, it merely improve the performance if your dataset is large enough (say, > 500 data points). If you want to fine-tune from our checkpoint, you can remove the `checkpoints` directory and retry.
