### ISSUE TITLE
'MetricVisualizer' object has no attribute 'add_metric'

### ISSUE THREAD

**Issue by LaurentVeyssier** [yangheng95/PyABSA#264]
Hi @yangheng95 

Thank you for your fantastic work with pyABSA !

I am trying to train from a checkpoint using my own toy dataset. I am using version 1.16.27 (`pip install pyabsa==1.16.27`) with TorchVersion:1.12.1+cu113+cuda11.3. I am following the ATEPC example from [here](https://github.com/yangheng95/PyABSA/blob/release/demos/aspect_term_extraction/ATEPC_USAGES.ipynb).

I am using an 'english' checkpoint compatible with v1 (I can successfully do interference on Restaurant14 dataset or batches of custom strings). I would like to fine-tune a checkpoint ultimately.

I run the following:

`aspect_extractor = Trainer(config=config,
                          dataset=dataset,
                          from_checkpoint=checkpoint_path,
                          checkpoint_save_mode=1,
                          auto_device=True,
                          ).load_trained_model()`

I constantly met with an error message of:

`File ~\anaconda3\envs\pyabsa\lib\site-packages\pyabsa\core\atepc\training\atepc_trainer.py:380, in Instructor.run(self)
    377     self.opt.MV.add_metric('Test-ATE-F1', ate_result)
    379 else:
--> 380     self.opt.MV.add_metric('Max-APC-Test-Acc w/o Valid Set', self.opt.max_test_metrics['max_apc_test_acc'])
    381     self.opt.MV.add_metric('Max-APC-Test-F1 w/o Valid Set', self.opt.max_test_metrics['max_apc_test_f1'])
    382     self.opt.MV.add_metric('Max-ATE-Test-F1 w/o Valid Set', self.opt.max_test_metrics['max_ate_test_f1'])

AttributeError: 'MetricVisualizer' object has no attribute 'add_metric'`

The error systematically occurs at the end of the last epoch. The training runs smoothly prior to that point. The Metric Visualizer log information shown in your custom training example never displayed. I have the issue whether I use a checkpoint or not. 

I tried with both `Trainer`  and `ATEPCTrainer` resulting in the same issue (I do not know the difference between the two btw and why the ATEPC exemple is using `Trainer` and not `ATEPCTrainer`).

Do you have any advice on how I may try to fix this ?

Many thanks in advance.

**Comment by yangheng95** [comment]
Please try installing metric_visualizer==0.9.4

**Comment by yangheng95** [comment]
In V1.x, the ATEPCTrainer is an alias for Trainer.

**Comment by LaurentVeyssier** [comment]
Thank you for your response!
The add_metric method is now available but I get a new error still from metric_visualizer package:

![image](https://user-images.githubusercontent.com/68251051/222723350-1abd0af5-ad18-4fe2-a4a9-f9471b5ddb6b.png)

**Comment by yangheng95** [comment]
I release a patch 0.9.5, please try it

**Comment by LaurentVeyssier** [comment]
thanks again for the support, all working good now !
