### ISSUE TITLE
Error custom training pyABASA v2 Missing keys in loading state_dict for LCF_ATEPC

### ISSUE THREAD

**Issue by LaurentVeyssier** [yangheng95/PyABSA#265]
Hi

Thank you for your fantastic work with pyABSA !

I am trying to train from a checkpoint using pyABSA v2.0.28. I follow the following tutorial [here](https://pyabsa.readthedocs.io/en/v2/6_tutorials/Aspect_Term_Extractor.html).

I run:

`from pyabsa import AspectTermExtraction as ATEPC

trainer = ATEPC.ATEPCTrainer(
    config=config,
    dataset=dataset,
    from_checkpoint="english",
    auto_device=DeviceTypeOption.AUTO,
    path_to_save=None, 
    checkpoint_save_mode=ModelSaveOption.SAVE_MODEL_STATE_DICT,
    load_aug=False,
)`
I use a custom toy dataset which I prepared according to the specifications. Previously, in a separate install of pyABSA v1, I was able to use this dataset to train from a checkpoint using pyABSA v1.16.27.

I assign the dataset with either:
`dataset = DatasetItem("my_dataset", ["140.Reviews"])`
or
`dataset = "140.Reviews"`

I use an “english” checkpoint which I downloaded in v2 with :

`aspect_extractor = ATEPC.AspectExtractor('english',
                                         auto_device=True,
                                         cal_perplexity=True )
`

![image](https://user-images.githubusercontent.com/68251051/222971738-a34734d1-cf6e-4e5d-92e1-ffe82d8c23a2.png)

The checkpoint appears in my pyABSA2 checkpoints folder.
I am able to perform full batch inference using this checkpoint on Restaurant16 dataset.

While calling the Trainer, the 'convert examples to features' proceeds to 100% but then I get the following error:
![image](https://user-images.githubusercontent.com/68251051/222971261-cf895054-b987-4a65-9f2e-da07780efae4.png)
....
![image](https://user-images.githubusercontent.com/68251051/222971283-e066eba4-8472-44e5-ad9d-8ba77585be6b.png)

It looks like an incompatible checkpoint. Yet the checkpoint should be valid from the above steps.

Would you be able to advise how I could solve the issue ?

Many thanks in advance for your feedback.

**Comment by yangheng95** [comment]
This is a duplicated issue: #263 
I will have a look later.

**Comment by LaurentVeyssier** [comment]
Hello, thank you for looking at this issue. Unfortunately, I still experience the exact same problem. I deleted the former checkpoint, initialized the ATEPC.AspectExtractor (resulting into downloading the english checkpoint) and launched the trainer described in my initial post above.  It ends up with the same issue as above. Would you have any idea ?
I am quite excited to see you have introduced a triplet extraction. I will definitely try this out!
Many thanks in advance for your feedback.

**Comment by yangheng95** [comment]
Did you update to the latest version?

**Comment by LaurentVeyssier** [comment]
ahhh... I did update to test the triplet but after I retried the training. So I will test again using the latest pyABSA version and will let you know. Did not think about this. Sorry for that.  Many thanks.

**Comment by LaurentVeyssier** [comment]
Hi
Unfortunately, still getting an error. Deleted the English checkpoint, downloaded it again using ATEPC.AspectExtractor.
Error while calling the Trainer:
![image](https://user-images.githubusercontent.com/68251051/224417231-d216f0fd-5544-4848-b1aa-97a8710afb3e.png)
![image](https://user-images.githubusercontent.com/68251051/224417351-0d348988-0a8f-4664-ac85-7d73d812ea4a.png)

I am using pyabasa 2.1.6

**Comment by yangheng95** [comment]
Please try use another model: config.model = FAST_LCF_ATEPC
Because the downloaded checkpoint is trained using FAST_LCF_ATEPC model, which can not be resumed from LCF_ATEPC.
