### ISSUE TITLE
Failed to generate sentiment for sentences containing more than one aspect

### ISSUE THREAD

**Issue by RajNS02** [yangheng95/PyABSA#266]
Hello.

I am trying out this PyABSA APC model on huggingface:
https://huggingface.co/yangheng/deberta-v3-large-absa-v1.1
Sentence: Everything is always cooked to perfection , the [B-ASP] service [E-ASP] is excellent. The [B-ASP] decor [E-ASP]  is also cool and understated.

It works fine when I provide only one aspect in a sentence. However, when there are more than one aspect, it gives sentiment score for only one of them (probably the first aspect).

Could you please suggest how can I get sentiments for all of the provided aspects? 
Thanks in advance.

**Comment by yangheng95** [comment]
https://github.com/yangheng95/PyABSA/blob/v2/examples-v2/aspect_polarity_classification/inference.py

**Comment by RajNS02** [comment]
Thanks for the reply.

Could you please help me out in this regard:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/95965558/222975127-17449ddb-9c6f-4f04-a3f1-497722ae478e.png">

Aren't we explicitly providing the sentiments to the model as shown in the above image? So, how is it that the model is "predicting" the sentiments associated with the aspects?

Thanks.

**Comment by yangheng95** [comment]
These are reference, can be none.

**Comment by RajNS02** [comment]
Oh, got it! :-D
Thank you so much.

Cheers!

**Comment by RajNS02** [comment]
Hello.

Unfortunately, even after adding the $LABEL$ tag, its giving sentiment of just one aspect.:
1. End tag: "$LABEL$ None, None"
https://huggingface.co/yangheng/deberta-v3-large-absa-v1.1?text=excellent+%5BB-ASP%5D+staff+%5BE-ASP%5D+and+%5BB-ASP%5D+customer+service+%5BE-ASP%5D.+very+clean+and+spotless+elegant+and+luxurious+with+a+beautiful+%5BB-ASP%5D+ocean++view+%5BE-ASP%5D.+the+%5BB-ASP%5D+bed+%5BE-ASP%5D+is+very+comfortable+and+relaxing%2C+i+give+it+a+five+star.+%24LABEL%24
2. End tag: "$LABEL$ Positive, Positive"
https://huggingface.co/yangheng/deberta-v3-large-absa-v1.1?text=Everything+is+always+cooked+to+perfection+%2C+the+%5BB-ASP%5D+service+%5BE-ASP%5D+is+excellent.+The+%5BB-ASP%5D+decor+%5BE-ASP%5D+is+also+cool+and+understated.+%24LABEL%24+Positive%2C+Positive

Could you please suggest what am I missing here?
Thanks.

**Comment by yangheng95** [comment]
This model on Huggingface is not for multiple aspects inference. Please use refer to the examples for APC 

> https://github.com/yangheng95/PyABSA/blob/v2/examples-v2/aspect_polarity_classification/inference.py

**Comment by RajNS02** [comment]
Unfortunately, everytime I try to import PyABSA >=2.0 versions  in Google Colab, the notebook just crashes.

However, PyABSA <=1.16.27 does work with Colab, but I am not able to find the examples which deal with **prediction** of multiple aspects in a sentence.

So, could you suggest some workaround for this issue?
Thanks.

**Comment by yangheng95** [comment]
https://colab.research.google.com/drive/1oDgxmc9aYNjBbzIQcv_g7XZax8On8zma

**Comment by RajNS02** [comment]
Thank you so much!
Peace✌

**Comment by Ibrokhimsadikov** [comment]
@yangheng95 I want to use quadruple model, but it is crushing on AWS Sagemaker as well if I pip install >2.2.0 versions

**Comment by yangheng95** [comment]
> @yangheng95 I want to use quadruple model, but it is crushing on AWS Sagemaker as well if I pip install >2.2.0 versions

It is hard to say why 2.0.0 + versions does not work on colab or sagemaker, but you can copy code out of pyabsa and develop
