### ISSUE TITLE
关于方面提取和对该方面的情感分类

### ISSUE THREAD

**Issue by caibird2020** [yangheng95/PyABSA#271]
大佬我又来了，我看过一些ABSA的论文，但还是不太清楚模型是怎么提取测试集中句子的方面，我知道通过softmax对极性进行判断，但是首先是要对方面进行提取，然后才能判断方面的极性吧，之前用过您在huggingface上开发的小程序，就是输入一个句子，右边能显示句子的方面还有极性，我就想知道这个过程是怎么样的，感觉一些论文里写的不是特别清楚，希望大佬能解惑，谢谢！

**Comment by yangheng95** [comment]
这个问题不适合文字解释，多看论文和代码。我精力有限，有些问题实在兼顾不来

**Comment by caibird2020** [comment]
谢谢您，我还有个小问题就是，您这份代码是只能预测给定方面的极性吗，还是说既能预测句子中的方面，又能预测极性

**Comment by yangheng95** [comment]
你说的是ATEPC，demo里有

**Comment by caibird2020** [comment]
好的谢谢
