### ISSUE TITLE
triplet annotation tool option

### ISSUE THREAD

**Issue by LaurentVeyssier** [yangheng95/PyABSA#273]
Hi
Many thanks again for the great work! I tested the new triplet module with v2.1.6, it works perfectly. Amazing!
I realize I would need to fine-tune for my domain. Is there a chance the annotation tool is also available ? I love the available dataset annotation tool, but it does not accommodate for the opinion as far as i understand it.
Alternatively, would you recommend a tool for quick, error free, triplet annotation that you may have been using for the integrated aste datasets?
Thank you for your feedback

**Comment by yangheng95** [comment]
Sorry, I have no idea about a ASTE annotation tool.
