### ISSUE TITLE
Which languages are supported by the multilingual APC models?

### ISSUE THREAD

**Issue by ghost** [yangheng95/PyABSA#280]
Hi Hang, first: thanks for your great work on these models and for open sourcing them 👏

I wondered which languages are supported by the two multilingual models for APC. They do seem to return reasonable output for all the languages I want to use them for (German, Spanish, French, Italian and Portuguese). But as I'm not fluent in all of them myself, it's difficult to observe performance without a labelled dataset for evaluation.

What languages do you (not) recommend using your multilingual APC models for? Which languages were the models finetuned on? I couldn't find a list on this repository.

**Comment by yangheng95** [comment]
You can find the datasets here: https://huggingface.co/spaces/yangheng/PyABSA

<img width="381" alt="image" src="https://user-images.githubusercontent.com/51735130/225328319-ef9d21d0-6e03-4365-ba2b-7cacda20243b.png">

**Comment by ghost** [comment]
Thank you. It might be handy to list the languages covered by the datasets (and their percentage) somewhere in the README.
