### ISSUE TITLE
Aspect Embedding

### ISSUE THREAD

**Issue by Winnieliu0504** [yangheng95/PyABSA#284]
Hello,

Many thanks for the great work! I would like to know how can I **get each aspect's embedding** after using the `make_ABSA_dataset` code? 
I need this for my fine-tune model but I can't really understand the source code about this. I guess it may be in the "pyabsa > framework" folder?

Could you give me more information about which part should I check for it?
Thank you for your feedback!

**Comment by yangheng95** [comment]
I don't really get your point, can you give me an example?

**Comment by Winnieliu0504** [comment]
For example, I can get a result like this after using `make_ABSA_dataset` code :
```
{'text': ' Boot time is super fast, around anywhere from 35 seconds to 1 minute .',
'aspect': ['Boot time'].
'sentiment': ['Positive']}
```
How can I get the word embedding of "Boot Time"?
Since the model has the ability to extract "Boot Time" as an aspect and even knows the sentiment of it, I guess there must be an embedding to represent the aspect.

I need to get all the embeddings represents to each aspect in my dataset and cluster the aspects for further process since there are too many aspects in my data after doing the aspect extraction.

Thank you for your feedback!

**Comment by yangheng95** [comment]
For example, if you use Fast_LCF_BERT model, the embedding is here:
https://github.com/yangheng95/PyABSA/blob/3d6cc4a43670d71d7444d4f6ddbcf6614b5f806a/pyabsa/tasks/AspectPolarityClassification/models/__lcf__/fast_lcf_bert.py#L41

**Comment by Winnieliu0504** [comment]
Got it, thanks a lot!!!
