### ISSUE TITLE
ImportError: Failed to initialize: Bad git executable.

### ISSUE THREAD

**Issue by mbadikyan** [yangheng95/PyABSA#287]
When importing:

from pyabsa import AspectTermExtraction

in my docker container named "preprocessing container", I get the following error:

Traceback (most recent call last):
preprocessing_container    |   File "process_data.py", line 15, in <module>
preprocessing_container    |     from pyabsa import AspectTermExtraction as ate
preprocessing_container    |   File "/usr/local/lib/python3.8/site-packages/pyabsa/__init__.py", line 14, in <module>
preprocessing_container    |     from pyabsa.utils.data_utils.dataset_item import DatasetItem
preprocessing_container    |   File "/usr/local/lib/python3.8/site-packages/pyabsa/utils/__init__.py", line 9, in <module>
preprocessing_container    |     from pyabsa.utils.absa_utils.make_absa_dataset import make_ABSA_dataset
preprocessing_container    |   File "/usr/local/lib/python3.8/site-packages/pyabsa/utils/absa_utils/make_absa_dataset.py", line 18, in <module>
preprocessing_container    |     from pyabsa.tasks.AspectTermExtraction.prediction.aspect_extractor import (
preprocessing_container    |   File "/usr/local/lib/python3.8/site-packages/pyabsa/tasks/AspectTermExtraction/__init__.py", line 11, in <module>
preprocessing_container    |     from .trainer.atepc_trainer import ATEPCTrainer
preprocessing_container    |   File "/usr/local/lib/python3.8/site-packages/pyabsa/tasks/AspectTermExtraction/trainer/atepc_trainer.py", line 14, in <module>
preprocessing_container    |     from ..prediction.aspect_extractor import AspectExtractor
preprocessing_container    |   File "/usr/local/lib/python3.8/site-packages/pyabsa/tasks/AspectTermExtraction/prediction/aspect_extractor.py", line 21, in <module>
preprocessing_container    |     from pyabsa.utils.data_utils.dataset_manager import detect_infer_dataset
preprocessing_container    |   File "/usr/local/lib/python3.8/site-packages/pyabsa/utils/data_utils/dataset_manager.py", line 15, in <module>
preprocessing_container    |     import git
preprocessing_container    |   File "/usr/local/lib/python3.8/site-packages/git/__init__.py", line 91, in <module>
preprocessing_container    |     raise ImportError("Failed to initialize: {0}".format(exc)) from exc
preprocessing_container    | ImportError: Failed to initialize: Bad git executable.
preprocessing_container    | The git executable must be specified in one of the following ways:
preprocessing_container    |     - be included in your $PATH
preprocessing_container    |     - be set via $GIT_PYTHON_GIT_EXECUTABLE
preprocessing_container    |     - explicitly set via git.refresh()
preprocessing_container    | 
preprocessing_container    | All git commands will error until this is rectified.
preprocessing_container    | 
preprocessing_container    | This initial warning can be silenced or aggravated in the future by setting the
preprocessing_container    | $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
preprocessing_container    |     - quiet|q|silence|s|none|n|0: for no warning or exception
preprocessing_container    |     - warn|w|warning|1: for a printed warning
preprocessing_container    |     - error|e|raise|r|2: for a raised exception
preprocessing_container    | 
preprocessing_container    | Example:
preprocessing_container    |     export GIT_PYTHON_REFRESH=quiet

Any clues on what this might be? Thank you!

**Comment by yangheng95** [comment]
Did you install git in your container? https://git-scm.com/

**Comment by mbadikyan** [comment]
I believe so, I have the following line in my DockerFile:

RUN apt-get -y install git python3-pip

**Comment by yangheng95** [comment]
Please test if `git` command is available in your container and try `pip install gitpython` then
