### ISSUE TITLE
> > > > Which taks do you need to do, APC, ATEPC or ASTE? See the demo https://huggingface.co/spaces/yangheng/PyABSA for details.

### ISSUE THREAD

**Issue by christianjosef27** [yangheng95/PyABSA#289]
> > > > Which taks do you need to do, APC, ATEPC or ASTE? See the demo https://huggingface.co/spaces/yangheng/PyABSA for details.
> > > 
> > > 
> > > I want to do ATEPC. I understand that with this task I can extract 1 or multiple aspect terms and determine their sentiments. I hope I can use my train dataset somehow, otherwise it would be a lot of work to create it again with your provided tool.
> > > Thanks for your help!
> > 
> > 
> > ***PS: the column "aspect categories" of my train dataset are not a must. I just added them because I might use them later on.
> 
> First convert you data to APC format as following (You need to write the code yourself): <img alt="image" width="553" src="https://user-images.githubusercontent.com/51735130/224088707-8369eb03-a979-4a00-8f06-6296ea202df1.png">
> 
> Then, convert it to ATEPC dataset: [convert_apc_](https://github.com/yangheng95/PyABSA/blob/v2/examples-v2/aspect_polarity_classification/convert_apc_to_atepc_dataset.py)

Okay I see, thank you for those hints! I will try that, however I was wondering the 2 points:

1-So is it true that this way is also a "common way" of doing it/or lets say possible without too big obstacles?
Or is it rather hard to convert my format into the APC format? (I have coding background but not a lot)

2-And the 2. step to convert to ATEPC dataset is basically just using that function of yours right?

_Originally posted by @christianjosef27 in https://github.com/yangheng95/PyABSA/issues/189#issuecomment-1462445292_

**Comment by yangheng95** [comment]
Yes. If you follow the data annotation, this is a simple thing
