### ISSUE TITLE
小白求助谢谢🙏

### ISSUE THREAD

**Issue by GuanxiJiang** [yangheng95/PyABSA#293]
您好, 我在一开始import的时候不知道为什么就会报错 
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/92268173/228895110-8350ee8d-f65e-4bbc-993a-ff4f6f3ca489.png">
还想请问一下您, 对于我下面的数据集可以fine-tune你的模型吗? 我觉得它的conent也不属于严格意义上的aspect, 然后对个aspect它只判断最后的极性。

<img width="396" alt="image" src="https://user-images.githubusercontent.com/92268173/228895674-93316471-1379-4c32-9a1a-360528facb3b.png">

**Comment by yangheng95** [comment]
这应该是你的环境导致的，跟这个库的关系不大。你的数据集有部分content是空的，这个得剔除掉
