### ISSUE TITLE
AttributeError: 'MetricList' object has no attribute 'iqr'

### ISSUE THREAD

**Issue by christianjosef27** [yangheng95/PyABSA#298]
Hi, I tried training on a custom dataset and that worked until epoch 3, however, afterwards an error raised interrupting the training.

The error message:

![image](https://user-images.githubusercontent.com/83338998/230786676-060c2961-b9ee-4f60-8f4b-be8933fe0e97.png)

How can I try resolving it? Is there a bug in the metric_visualizer.py?

**Comment by yangheng95** [comment]
try `pip install metric-visualizer -U`

**Comment by christianjosef27** [comment]
Thanks for quick reply!

It seems it was already the latest version:
![image](https://user-images.githubusercontent.com/83338998/230787530-013512af-a669-4cb3-8f4b-494383092959.png)

**Comment by yangheng95** [comment]
Please show me your code to help debug

**Comment by christianjosef27** [comment]
1.
![image](https://user-images.githubusercontent.com/83338998/230882531-e8d28085-6d43-441d-a320-433db028a906.png)

2.
![image](https://user-images.githubusercontent.com/83338998/230882631-e9b4d513-0f80-4e5a-9508-02c08cd72ba0.png)

3.
![image](https://user-images.githubusercontent.com/83338998/230882800-25a1b6f8-ac23-4a9a-95e9-606d195f86e5.png)


I use pyabsa version 2.2.2 and metric_visualizer as said should be 0.9.6.
I pass the directory to  Trainer which  contains my train, val and test datasets in ATEPC Format.

**Comment by yangheng95** [comment]
please check the Python version and scipy version

**Comment by christianjosef27** [comment]
![image](https://user-images.githubusercontent.com/83338998/230969687-2d03a84e-0b99-4804-9cd6-6a18cfbcfd0e.png)

Should I try installing the latest versions of each python and scipy?
Or which versions do you recommend?

**Comment by yangheng95** [comment]
pip install scipy -U

**Comment by christianjosef27** [comment]
Thanks I updated scipy and trying the training running.... I keep u updated
