### ISSUE TITLE
Incorrect checkpoint

### ISSUE THREAD

**Issue by MouzaMrinal** [yangheng95/PyABSA#302]
@yangheng95  , While trying to run the below code am getting error: "No checkpoint found in Model Hub for task: checkpoints/multitask/googleflan-t5-base-instruction/checkpoint-7316"

I have taken the below code directly from your example:

  ```
          from pyabsa import ABSAInstruction
            
            if __name__ == "__main__":
                generator = ABSAInstruction.ABSAGenerator(
                    "checkpoints/multitask/googleflan-t5-base-instruction/checkpoint-7316"
                )
                example = [
                    "The food is good, but the service is bad.",
                    "The laptop is good, but the battery life is bad.",
                ]
            
                for example in example:
                    result = generator.predict(example)
                    print(result)
```

**Comment by yangheng95** [comment]
> @yangheng95 , While trying to run the below code am getting error: "No checkpoint found in Model Hub for task: checkpoints/multitask/googleflan-t5-base-instruction/checkpoint-7316"
> 
> I have taken the below code directly from your example:
> 
> ```
>         from pyabsa import ABSAInstruction
>           
>           if __name__ == "__main__":
>               generator = ABSAInstruction.ABSAGenerator(
>                   "checkpoints/multitask/googleflan-t5-base-instruction/checkpoint-7316"
>               )
>               example = [
>                   "The food is good, but the service is bad.",
>                   "The laptop is good, but the battery life is bad.",
>               ]
>           
>               for example in example:
>                   result = generator.predict(example)
>                   print(result)
> ```

Please try the following code isntead
```
generator = ABSAInstruction.ABSAGenerator('multilingual')
```

**Comment by MouzaMrinal** [comment]
Thanks for the quick response. This works. Closing the issue
