### ISSUE TITLE
How to use ATEPC for APC inference

### ISSUE THREAD

**Issue by neoyipeng2018** [yangheng95/PyABSA#31]
Hi,

Thanks for creating this repo, it's very useful! 

So I've created a ATEPC model, and now only want to do APC inference - is that possible? 
Don't see that in the examples so far.

Thanks, Yi Peng

**Comment by yangheng95** [comment]
check this parameter: https://github.com/yangheng95/PyABSA/blob/058ae4ef2ac9d150da75dec534118b3125b1f78a/examples/aspect_term_extraction/extract_aspects.py#L40

**Comment by yangheng95** [comment]
We cannot use atepc model predict sentiment only now, it's a additional feature of atepc task.

**Comment by neoyipeng2018** [comment]
I see, thanks for the clarification!
