### ISSUE TITLE
How to show APC Train Acc, APC Train F1 and ATE-F1 while training the model? 

### ISSUE THREAD

**Issue by alfadoraflyh** [yangheng95/PyABSA#319]
How can I display APC Train Acc, APC Train F1, and ATE-F1 while training the model? I need this information to evaluate whether the model is overfitting or underfitting. Thank you

**Comment by yangheng95** [comment]
These information is available in training log prining.

**Comment by alfadoraflyh** [comment]
![Screenshot_output_training](https://github.com/yangheng95/PyABSA/assets/72862438/86322877-1a56-4344-82d9-79c72b7d7bc1)

Excuse me, did you mean this output ("trainer.log")?
