### ISSUE TITLE
LFC-BERT Sementic-relative-distance

### ISSUE THREAD

**Issue by Pager07** [yangheng95/PyABSA#32]
In LCF-Paper  https://www.mdpi.com/2076-3417/9/16/3389/htm, the sementic-relative distance is given by 
|position_of_token - average_position_of_aspect| - (average_length_of_aspect /2). But in your implementation for LFC_Bert in feature_dynamic_weighted fucntion, you calcuated sementic-relative distance as |position_of_token - average_position_of_aspect| +(average_length_of_aspect /2). May you please help me understand the this difference?

**Comment by yangheng95** [comment]
I am sorry for this puzzle, but I am somehow didnt catch your meaning. please refer to the latest implementation of CDW vec cacculation at https://github.com/yangheng95/PyABSA/blob/f16de405a9a11945b3b26be73daef5b5fab62ee1/pyabsa/module/apc/dataset_utils/apc_utils.py#L291 , it is clear to understand and accurate.

**Comment by Pager07** [comment]
The new implementation of CDW vec on the apc_utils file is very clear thanks. 
The [link](https://github.com/fhamborg/newstsc/blob/master/models/lcf.py) here references your code, (presumably your old code). 

I notice the CDW vec generated using this implementation [here ](https://github.com/fhamborg/newstsc/blob/master/models/lcf.py)is different from CDW vec from this implementation [here](https://github.com/yangheng95/PyABSA/blob/f16de405a9a11945b3b26be73daef5b5fab62ee1/pyabsa/module/apc/dataset_utils/apc_utils.py#L291). 

Could you tell me which one is the correct?

**Comment by yangheng95** [comment]
Both codes of the old version are not very accurate, because sometimes the aspect location calculated is wrong (e.g., some word/token is the same as the beginning of an aspect will be regarded as the aspect and calculate position, which has been solved in PyABSA). To answer your question,  |position_of_token - average_position_of_aspect| +(average_length_of_aspect /2) seems to be more reasonable but not completely right.

**Comment by yangheng95** [comment]
However, the difference could be ignored to some extent.

**Comment by ningmiaokai** [comment]
> The new implementation of CDW vec on the apc_utils file is very clear thanks. The [link](https://github.com/fhamborg/newstsc/blob/master/models/lcf.py) here references your code, (presumably your old code).
> 
> I notice the CDW vec generated using this implementation [here ](https://github.com/fhamborg/newstsc/blob/master/models/lcf.py)is different from CDW vec from this implementation [here](https://github.com/yangheng95/PyABSA/blob/f16de405a9a11945b3b26be73daef5b5fab62ee1/pyabsa/module/apc/dataset_utils/apc_utils.py#L291).
> 
> Could you tell me which one is the correct?

Hello, could you tell me what's the meaning of opt in [here](https://github.com/yangheng95/PyABSA/blob/f16de405a9a11945b3b26be73daef5b5fab62ee1/pyabsa/module/apc/dataset_utils/apc_utils.py#L291).
Thank you!
