### ISSUE TITLE
Annotation method for quadruple extraction

### ISSUE THREAD

**Issue by BBabuRAA** [yangheng95/PyABSA#328]
## Unless you provide the REQUIRED information, your problem may not be addressed.
N/A

### PyABSA Version (Required)
Latest Version

### ABSADataset Version (Required if you use integrated datasets)
Latest version

### Code To Reproduce (Required)
N/A

### Full Console Output (Required)
N/A

### Describe the bug
Not a bug, but I was wondering what the best annotation methods are for Quadruple extraction? Can we auto-annotate or use the DPT tool? Or will we have to do it ourselves completely?

**Comment by yangheng95** [comment]
I am sorry but the annotation tool is not available for ASTE and ACOS. You need to do the annotation your self.

**Comment by BBabuRAA** [comment]
No worries, thank you for the quick response!
