### ISSUE TITLE
failed to loading the checkpoint

### ISSUE THREAD

**Issue by GamBling111** [yangheng95/PyABSA#341]
I'm using my own computer.But failed to load the checkpoint.
Here is the bug:
RuntimeError: Exception: Error(s) in loading state_dict for FAST_LCF_ATEPC:
        Unexpected key(s) in state_dict: "bert4global.embeddings.position_ids".  Fail to load the model from checkpoints/ATEPC_ENGLISH_CHECKPOINT/fast_lcf_atepc_English_cdw_apcacc_82.36_apcf1_81.89_atef1_75.43! 

I have tried other checkpoint like mutilin,but still got the same bug.
Thanks in advance.

**Comment by JGasconMoreno** [comment]
I have the same problem after a clean installation in a new virtual environment, 

[2023-07-26 10:52:36] (2.3.1) Downloading checkpoint:english 
[2023-07-26 10:52:36] (2.3.1) Notice: The pretrained model are used for testing, it is recommended to train the model on your own custom datasets
Downloading checkpoint: 534MB [02:17,  3.89MB/s]                         
Find zipped checkpoint: [./checkpoints\ASTE_ENGLISH_CHECKPOINT\ASTE-EMCGCN_SemEval_f1_74.71.zip](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/jgascon/Documents/GitHub/content_lib/src/adhoc_analysis/BuyerAdvocate/checkpoints/ASTE_ENGLISH_CHECKPOINT/ASTE-EMCGCN_SemEval_f1_74.71.zip), unzipping

Done.
[2023-07-26 10:55:08] (2.3.1) If the auto-downloading failed, please download it via browser: https://huggingface.co/spaces/yangheng/PyABSA/resolve/main/checkpoints/English/ASTE/ASTE-EMCGCN_SemEval_f1_74.71.zip 
[2023-07-26 10:55:08] (2.3.1) Load sentiment classifier from checkpoints\ASTE_ENGLISH_CHECKPOINT
[2023-07-26 10:55:08] (2.3.1) config: checkpoints\ASTE_ENGLISH_CHECKPOINT\emcgcn.config
[2023-07-26 10:55:08] (2.3.1) state_dict: checkpoints\ASTE_ENGLISH_CHECKPOINT\emcgcn.state_dict
[2023-07-26 10:55:08] (2.3.1) model: None
[2023-07-26 10:55:08] (2.3.1) tokenizer: checkpoints\ASTE_ENGLISH_CHECKPOINT\emcgcn.tokenizer
[2023-07-26 10:55:09] (2.3.1) Set Model Device: cpu
[2023-07-26 10:55:09] (2.3.1) Device Name: Unknown
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File [c:\Users\jgascon\Documents\GitHub\content_lib\.venv\lib\site-packages\pyabsa\tasks\AspectSentimentTripletExtraction\prediction\predictor.py:82](file:///C:/Users/jgascon/Documents/GitHub/content_lib/.venv/lib/site-packages/pyabsa/tasks/AspectSentimentTripletExtraction/prediction/predictor.py:82), in AspectSentimentTripletExtractor.__init__(self, checkpoint, **kwargs)
     79     self.model = self.config.model(config=self.config).to(
     80         self.config.device
     81     )
---> 82     self.model.load_state_dict(
     83         torch.load(
     84             state_dict_path, map_location=torch.device("cpu")
     85         )
     86     )
     87 elif model_path:

File [c:\Users\jgascon\Documents\GitHub\content_lib\.venv\lib\site-packages\torch\nn\modules\module.py:2041](file:///C:/Users/jgascon/Documents/GitHub/content_lib/.venv/lib/site-packages/torch/nn/modules/module.py:2041), in Module.load_state_dict(self, state_dict, strict)
   2040 if len(error_msgs) > 0:
-> 2041     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   2042                        self.__class__.__name__, "\n\t".join(error_msgs)))
   2043 return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for EMCGCN:
	Unexpected key(s) in state_dict: "bert.embeddings.position_ids". 

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
Cell In[2], line 4
      1 from pyabsa import AspectSentimentTripletExtraction as ASTE
      3 # Load the model
----> 4 triplet_extractor = ASTE.AspectSentimentTripletExtractor("english")
      5 #triplet_extractor = ASTE.AspectSentimentTripletExtractor("multilingual")

File [c:\Users\jgascon\Documents\GitHub\content_lib\.venv\lib\site-packages\pyabsa\tasks\AspectSentimentTripletExtraction\prediction\predictor.py:99](file:///C:/Users/jgascon/Documents/GitHub/content_lib/.venv/lib/site-packages/pyabsa/tasks/AspectSentimentTripletExtraction/prediction/predictor.py:99), in AspectSentimentTripletExtractor.__init__(self, checkpoint, **kwargs)
     96             print_args(self.config)
     98     except Exception as e:
---> 99         raise RuntimeError(
    100             "Fail to load the model from {}! "
    101             "Please make sure the version of checkpoint and PyABSA are compatible."
    102             " Try to remove he checkpoint and download again"
    103             " \nException: {} ".format(checkpoint, e)
    104         )
    106 self.dataset = ASTEInferenceDataset(self.config, self.tokenizer)
    108 self.__post_init__(**kwargs)

RuntimeError: Fail to load the model from english! Please make sure the version of checkpoint and PyABSA are compatible. Try to remove he checkpoint and download again 
Exception: Error(s) in loading state_dict for EMCGCN:
	Unexpected key(s) in state_dict: "bert.embeddings.position_ids".

**Comment by JGasconMoreno** [comment]
I have solved using  transformers=4.29.0. Just uninstall and install again this specific version

**Comment by GamBling111** [comment]
> 

I don't understand about transformers.Do transformers mean the version of Pyabsa or something else?It's my first time to do this job.It may sound silly,but please tell me more details about it.Thanks.

**Comment by JGasconMoreno** [comment]
No worry. Transformers is a library in python, the problem is that the newer versions are not compatible with the last version of pyabsa. You need to uninstall transformers (pip uninstall transformers) and then install the specific version (pip install transformers==4.29.0).

**Comment by GamBling111** [comment]
Thank you for your answer.
