### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by deutschoo** [yangheng95/PyABSA#348]
## Unless you provide the REQUIRED information, your problem may not be addressed.
Installed the pyabsa according the readme step by step, but it seems the installation is still failed. 
here the error information after importing the package " from pyabsa import AspectTermExtraction as ATEPC, available_checkpoints"

### Describe the bug
ImportError                               Traceback (most recent call last)
File ~\Anaconda3\envs\pyabsa\lib\site-packages\confection\__init__.py:38, in <module>
     37 try:
---> 38     from pydantic.v1 import BaseModel, Extra, ValidationError, create_model
     39     from pydantic.v1.fields import ModelField

File ~\Anaconda3\envs\pyabsa\lib\site-packages\pydantic\__init__.py:13, in <module>
      4 from pydantic_core.core_schema import (
      5     FieldSerializationInfo,
      6     FieldValidationInfo,
   (...)
     10     ValidatorFunctionWrapHandler,
     11 )
---> 13 from . import dataclasses
     14 from ._internal._annotated_handlers import (
     15     GetCoreSchemaHandler as GetCoreSchemaHandler,
     16 )

File ~\Anaconda3\envs\pyabsa\lib\site-packages\pydantic\dataclasses.py:11, in <module>
      9 from typing_extensions import Literal, dataclass_transform
---> 11 from ._internal import _config, _decorators, _typing_extra
     12 from ._internal import _dataclasses as _pydantic_dataclasses

File ~\Anaconda3\envs\pyabsa\lib\site-packages\pydantic\_internal\_config.py:9, in <module>
      7 from typing_extensions import Literal, Self
----> 9 from ..config import ConfigDict, ExtraValues, JsonEncoder, JsonSchemaExtraCallable
     10 from ..errors import PydanticUserError

File ~\Anaconda3\envs\pyabsa\lib\site-packages\pydantic\config.py:9, in <module>
      8 from ._migration import getattr_migration
----> 9 from .deprecated.config import BaseConfig
     10 from .deprecated.config import Extra as _Extra

File ~\Anaconda3\envs\pyabsa\lib\site-packages\pydantic\deprecated\config.py:6, in <module>
      4 from typing import TYPE_CHECKING, Any
----> 6 from typing_extensions import Literal, deprecated
      8 from .._internal import _config

ImportError: cannot import name 'deprecated' from 'typing_extensions' (C:\Users\Lenovo\Anaconda3\envs\pyabsa\lib\site-packages\typing_extensions.py)

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 from pyabsa import AspectTermExtraction as ATEPC, available_checkpoints

File ~\Anaconda3\envs\pyabsa\lib\site-packages\pyabsa\__init__.py:13, in <module>
      9 __name__ = "pyabsa"
     10 __version__ = "2.3.2.2"
---> 13 from pyabsa.utils.notification_utils.notification_utils import (
     14     check_emergency_notification,
     15 )
     17 check_emergency_notification()
     19 from pyabsa.framework.flag_class import *

File ~\Anaconda3\envs\pyabsa\lib\site-packages\pyabsa\utils\__init__.py:9, in <module>
      1 # -*- coding: utf-8 -*-
      2 # file: __init__.py
      3 # time: 2021/6/5 0005
      4 # author: YANG, HENG <hy345@exeter.ac.uk> (杨恒)
      5 # github: https://github.com/yangheng95
      6 # Copyright (C) 2021. All Rights Reserved.
      8 from pyabsa.utils.data_utils.dataset_item import DatasetItem
----> 9 from pyabsa.utils.absa_utils.make_absa_dataset import make_ABSA_dataset
     10 from pyabsa.utils.absa_utils.absa_utils import (
     11     generate_inference_set_for_apc,
     12     convert_apc_set_to_atepc_set,
     13 )
     15 from pyabsa.utils.text_utils.word2vec import train_word2vec

File ~\Anaconda3\envs\pyabsa\lib\site-packages\pyabsa\utils\absa_utils\make_absa_dataset.py:18, in <module>
     14 from termcolor import colored
     16 from pyabsa.framework.flag_class.flag_template import LabelPaddingOption
---> 18 from pyabsa.tasks.AspectTermExtraction.prediction.aspect_extractor import (
     19     AspectExtractor,
     20 )
     21 from pyabsa.utils.pyabsa_utils import fprint
     24 def make_ABSA_dataset(dataset_name_or_path, checkpoint="english"):

File ~\Anaconda3\envs\pyabsa\lib\site-packages\pyabsa\tasks\AspectTermExtraction\prediction\aspect_extractor.py:33, in <module>
     31 from pyabsa.framework.prediction_class.predictor_template import InferenceModel
     32 from ..models import ATEPCModelList
---> 33 from ..dataset_utils.__lcf__.atepc_utils import (
     34     load_atepc_inference_datasets,
     35     process_iob_tags,
     36 )
     37 from ..dataset_utils.__lcf__.data_utils_for_inference import (
     38     ATEPCProcessor,
     39     convert_ate_examples_to_features,
     40     convert_apc_examples_to_features,
     41 )
     42 from ..dataset_utils.__lcf__.data_utils_for_training import split_aspect

File ~\Anaconda3\envs\pyabsa\lib\site-packages\pyabsa\tasks\AspectTermExtraction\dataset_utils\__lcf__\atepc_utils.py:12, in <module>
      9 import re
     10 import string
---> 12 from pyabsa.tasks.AspectPolarityClassification.dataset_utils.__lcf__.apc_utils import (
     13     get_syntax_distance,
     14     get_lca_ids_and_cdm_vec,
     15     get_cdw_vec,
     16 )
     17 from pyabsa.utils.pyabsa_utils import fprint
     20 # It is hard to tokenize multilingual text, I decide to use a pretrained tokenizer, you can alter according to your demands
     21 # tokenizer = AutoTokenizer.from_pretrained('bert-base-multilingual-cased')

File ~\Anaconda3\envs\pyabsa\lib\site-packages\pyabsa\tasks\AspectPolarityClassification\dataset_utils\__lcf__\apc_utils.py:13, in <module>
     11 import networkx as nx
     12 import numpy as np
---> 13 import spacy
     14 import termcolor
     16 from pyabsa.framework.tokenizer_class.tokenizer_class import pad_and_truncate

File ~\Anaconda3\envs\pyabsa\lib\site-packages\spacy\__init__.py:6, in <module>
      3 from typing import Any, Dict, Iterable, Union
      5 # set library-specific custom warning handling before doing anything else
----> 6 from .errors import setup_default_warnings
      8 setup_default_warnings()  # noqa: E402
     10 # These are imported as part of the API

File ~\Anaconda3\envs\pyabsa\lib\site-packages\spacy\errors.py:3, in <module>
      1 import warnings
----> 3 from .compat import Literal
      6 class ErrorsWithCodes(type):
      7     def __getattribute__(self, code):

File ~\Anaconda3\envs\pyabsa\lib\site-packages\spacy\compat.py:4, in <module>
      1 """Helpers for Python and platform compatibility."""
      2 import sys
----> 4 from thinc.util import copy_array
      6 try:
      7     import cPickle as pickle

File ~\Anaconda3\envs\pyabsa\lib\site-packages\thinc\__init__.py:5, in <module>
      2 import numpy
      4 from .about import __version__
----> 5 from .config import registry
      7 # fmt: off
      8 __all__ = [
      9     "registry",
     10     "__version__",
     11 ]

File ~\Anaconda3\envs\pyabsa\lib\site-packages\thinc\config.py:2, in <module>
      1 import catalogue
----> 2 import confection
      3 from confection import VARIABLE_RE, Config, ConfigValidationError, Promise
      5 from .types import Decorator

File ~\Anaconda3\envs\pyabsa\lib\site-packages\confection\__init__.py:42, in <module>
     40     from pydantic.v1.main import ModelMetaclass
     41 except ImportError:
---> 42     from pydantic import BaseModel, create_model, ValidationError, Extra  # type: ignore
     43     from pydantic.main import ModelMetaclass  # type: ignore
     44     from pydantic.fields import ModelField  # type: ignore

File ~\Anaconda3\envs\pyabsa\lib\site-packages\pydantic\__init__.py:13, in <module>
      3 import pydantic_core
      4 from pydantic_core.core_schema import (
      5     FieldSerializationInfo,
      6     FieldValidationInfo,
   (...)
     10     ValidatorFunctionWrapHandler,
     11 )
---> 13 from . import dataclasses
     14 from ._internal._annotated_handlers import (
     15     GetCoreSchemaHandler as GetCoreSchemaHandler,
     16 )
     17 from ._internal._annotated_handlers import (
     18     GetJsonSchemaHandler as GetJsonSchemaHandler,
     19 )

File ~\Anaconda3\envs\pyabsa\lib\site-packages\pydantic\dataclasses.py:11, in <module>
      7 from typing import TYPE_CHECKING, Any, Callable, Generic, NoReturn, TypeVar, overload
      9 from typing_extensions import Literal, dataclass_transform
---> 11 from ._internal import _config, _decorators, _typing_extra
     12 from ._internal import _dataclasses as _pydantic_dataclasses
     13 from ._migration import getattr_migration

File ~\Anaconda3\envs\pyabsa\lib\site-packages\pydantic\_internal\_config.py:9, in <module>
      6 from pydantic_core import core_schema
      7 from typing_extensions import Literal, Self
----> 9 from ..config import ConfigDict, ExtraValues, JsonEncoder, JsonSchemaExtraCallable
     10 from ..errors import PydanticUserError
     11 from ..warnings import PydanticDeprecatedSince20

File ~\Anaconda3\envs\pyabsa\lib\site-packages\pydantic\config.py:9, in <module>
      6 from typing_extensions import Literal, TypeAlias, TypedDict
      8 from ._migration import getattr_migration
----> 9 from .deprecated.config import BaseConfig
     10 from .deprecated.config import Extra as _Extra
     12 if TYPE_CHECKING:

File ~\Anaconda3\envs\pyabsa\lib\site-packages\pydantic\deprecated\config.py:6, in <module>
      3 import warnings
      4 from typing import TYPE_CHECKING, Any
----> 6 from typing_extensions import Literal, deprecated
      8 from .._internal import _config
      9 from ..warnings import PydanticDeprecatedSince20

ImportError: cannot import name 'deprecated' from 'typing_extensions' (C:\Users\Lenovo\Anaconda3\envs\pyabsa\lib\site-packages\typing_extensions.py)

Would you please tell me how to fix the problem, thank you

**Comment by yangheng95** [comment]
Can you specify your environment, e.g., torch version, python version?

**Comment by deutschoo** [comment]
邮件已收到，谢谢！

**Comment by yangheng95** [comment]
Please try to upgrade typing_extensions.

**Comment by deutschoo** [comment]
>my torhc version is  2.0.1+cpu, python i installed according your instructions in the github, 3.8. thank you

**Comment by deutschoo** [comment]
> Please try to upgrade typing_extensions.

typing_extensions is the newest version，4.7.1. and my typing_extensions is as follows:
Name: typing_extensions
Version: 4.7.1
Summary: Backported and Experimental Type Hints for Python 3.7+
Home-page:
Author:
Author-email: "Guido van Rossum, Jukka Lehtosalo, Łukasz Langa, Michael Lee" <levkivskyi@gmail.com>
License:
Location: c:\users\lenovo\anaconda3\envs\pyabsa\lib\site-packages
Requires:
Required-by: annotated-types, huggingface-hub, pyabsa, pydantic, pydantic_core, torch, typer.
what should i do next if i want to use the pyabsa normally? thank you very much for reply and looking forward to your instructions. many thanks!

**Comment by yangheng95** [comment]
Probably your environment is not compatible with pyabsa. Try to create a new env of python3.9+, then retry installing pyabsa.

**Comment by deutschoo** [comment]
I see, i will have a try again. Thank you very much for your reply!&nbsp;



---Original---
From: "Heng ***@***.***&gt;
Date: Sun, Aug 13, 2023 16:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yangheng95/PyABSA] install problem (Issue #348)




 
Probably your environment is not compatible with pyabsa. Try to create a new env of python3.9+, then retry installing pyabsa.

**Comment by deutschoo** [comment]
> Probably your environment is not compatible with pyabsa. Try to create a new env of python3.9+, then retry installing pyabsa.

Hi, I upgraded python to 3.9 and upgraded the pydantic to the newest version. typing_extensions is the newest version. However,  the same bug message come up as follows: 
ImportError: cannot import name 'deprecated' from 'typing_extensions' (C:\Users\Lenovo\Anaconda3\envs\pyabsa\lib\site-packages\typing_extensions.py)
Is there any other solutions? Thank you very much!

**Comment by yangheng95** [comment]
https://github.com/tiangolo/fastapi/discussions/9808
try to use python3.7

**Comment by deutschoo** [comment]
> [tiangolo/fastapi#9808](https://github.com/tiangolo/fastapi/discussions/9808) try to use python3.7

thank you so much!!!! installation succeeded!!!!!!!!!
