### ISSUE TITLE
some bug in TUTORIALS of Aspect Term Extraction and Sentiment Classification

### ISSUE THREAD

**Issue by TianqiFu** [yangheng95/PyABSA#367]
https://pyabsa.readthedocs.io/en/latest/6_tutorials/Aspect_Term_Extraction.html
Simple Prediction
**text=ex,** should be **example=ex**
Batch Inference
**target_file=ATEPC.ATEPCDatasetList.Restaurant16,** should be **inference_source=ATEPC.ATEPCDatasetList.Restaurant16,**

![屏幕截图 2023-12-01 171352](https://github.com/yangheng95/PyABSA/assets/19373187/ab854f71-b847-480d-afc0-f085ccfbd19d)

**Comment by yangheng95** [comment]
Thanks for report, will fix soon
