### ISSUE TITLE
Max length in ASTE

### ISSUE THREAD

**Issue by BLM3826** [yangheng95/PyABSA#371]
Hello, i am trying to use the inference of the ASTE model on my dataset. I noticed and reproduced it on the huggingface space that the maximum amount of words that the model can receive is 55. Is there a reason for that?

When you give it a text with more than 55 words the model returns:

`(2.3.4) Ignore error while processing: *sentence given* Error info:list index out of range`

Is there a way to override this?

**Comment by yangheng95** [comment]
This is a known problem caused by the ASTE model adapted from, and probably will not be resolved
