### ISSUE TITLE
what the input of lcf_glove?

### ISSUE THREAD

**Issue by yunbujian** [yangheng95/PyABSA#38]
Please tell me what the input of **lcf_glove** for global context processor and local one? Thanks!

**Comment by yangheng95** [comment]
Do you mean the input format? Both the input for global and local context processor are plain context.

**Comment by yunbujian** [comment]
Thanks! but you mean both global and local processor are context or the whole text? don't have aspect words?

**Comment by yangheng95** [comment]
The whole context with aspect, only the position of the aspect is used to locate and calculate the LCF vec. In another word, the aspect itself is regarded the same as the other context words.

**Comment by yangheng95** [comment]
If you are not going to replement the LCF-GloVe, to use the model in this repo, you may review the code. Becasue the code of GloVe based models are no longer supported.

**Comment by yunbujian** [comment]
谢谢！我就是看到你代码里没有LCF-GloVe了，但我想自己搭一个，所以全局和局部的输入都是单纯的一整句话，是这个意思嘛？

**Comment by yangheng95** [comment]
是的



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 10, 2021 21:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yangheng95/PyABSA] what the input of lcf_glove? (#38)




 
谢谢！我就是看到你代码里没有LCF-GloVe了，但我想自己搭一个，所以全局和局部的输入都是单纯的一整句话，是这个意思嘛？
