### ISSUE TITLE
How to rewrite the Custom Dataset?

### ISSUE THREAD

**Issue by cyborgrob** [yangheng95/PyABSA#396]
I apologize in advance if this is a completely newb question, but both myself and a friend have looked over the instructions and various other closed issues for hours and can't figure it out. How do you replace the placeholder dataset in '100.CustomDataset' with your own custom dataset, and how do you get PyABSA to find it after you do?

The instructions in the [ABSADataset](https://github.com/yangheng95/ABSADatasets) README say to "put your data into the prepared dataset files" (ie, 100.CustomDataset or similar). But... how? ABSADataset is a public repo, so I can't go overwriting that with my own dataset obviously. But when I clone ABSADataset to my local system and change the files there, when I run PyABSA it still goes looking for the files in the standard github repo at https://github.com/yangheng95/ABSADatasets, and not my local system. I also tried uploading my datasets to Google Drive and giving the aspect extractor the direct path, but that resulted in an error.

So how do you how do you actually overwrite/merge the default custom dataset with your own? If anyone could point us in the right direction we'd really appreciate it. Also please let me know if you need any additional info.

**Comment by cyborgrob** [comment]
```
# Put your dataset into integrated_datasets folder, it this folder does not exist, you need to call:
from pyabsa import download_all_available_datasets

download_all_available_datasets()
```

**Comment by TimotiusAnrez** [comment]
i see that the issue is closed, how do you use your own dataset?
