### ISSUE TITLE
How to Determine the Dataset Used for Pretrained Models from Checkpoints?

### ISSUE THREAD

**Issue by anata0954** [yangheng95/PyABSA#399]
**Describe the bug**
Pretrained model checkpoints are often used in pyabsa, but it's not always clear which datasets were used for their training. How can one determine the datasets used to train these checkpoints?
请问怎么样可以知道代码中的checkpoints是在哪些数据集上训练所得的呢？

**Comment by anata0954** [comment]
比如aspect_opinion_sentiment_category_extraction这一任务

**Comment by yangheng95** [comment]
Refer to: https://huggingface.co/spaces/yangheng/PyABSA/blob/main/checkpoints-v2.0.json

**Comment by anata0954** [comment]
Thank you. I have found the corresponding training dataset in checkpoint file. 
But i wonder are those datasets used for APC, ATEPC or text classification in [https://github.com/yangheng95/ABSADatasets/tree/v1.2](url) suitable for ACOS task? 
Or is there anyplace storing dataset for ACOS task?

**Comment by yangheng95** [comment]
https://github.com/yangheng95/ABSADatasets/tree/v2.0/datasets/acos_datasets

**Comment by anata0954** [comment]
thank you soooo much :)
