### ISSUE TITLE
ImportError: cannot import name 'TypeGuard'

### ISSUE THREAD

**Issue by alphamaviwiki** [yangheng95/PyABSA#46]
Hello, I face this problem when I try to install PyABSA. Let me know what happened, thx.

Traceback (most recent call last):
  File "test1.py", line 9, in <module>
    from pyabsa import load_sentiment_classifier
  File "/home/alphama/.env/lib/python3.6/site-packages/pyabsa/__init__.py", line 11, in <module>
    from .functional import train_apc, load_sentiment_classifier
  File "/home/alphama/.env/lib/python3.6/site-packages/pyabsa/functional.py", line 12, in <module>
    from pyabsa.dataset_utils import detect_dataset
  File "/home/alphama/.env/lib/python3.6/site-packages/pyabsa/dataset_utils.py", line 9, in <module>
    import git
  File "/home/alphama/.env/lib/python3.6/site-packages/git/__init__.py", line 8, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/home/alphama/.env/lib/python3.6/site-packages/git/exc.py", line 10, in <module>
    from git.compat import safe_decode
  File "/home/alphama/.env/lib/python3.6/site-packages/git/compat.py", line 32, in <module>
    from git.types import TBD
  File "/home/alphama/.env/lib/python3.6/site-packages/git/types.py", line 18, in <module>
    from typing_extensions import TypeGuard  # noqa: F401
ImportError: cannot import name 'TypeGuard'

**Comment by yangheng95** [comment]
This is an unexpected error, which may be caused by package "gitpython", you can try reinstall the ```gitpython``` package

**Comment by yangheng95** [comment]
Another potential method to solve this problem is to create a new virtual envs, then install pyabsa (please install torch at first).

For detailed information, PyABSA is developed and tested under Python3.9 with CUDA11, torch1.8.1

**Comment by yangheng95** [comment]
> Hello, I face this problem when I try to install PyABSA. Let me know what happened, thx.
> 
> Traceback (most recent call last):
> File "test1.py", line 9, in
> from pyabsa import load_sentiment_classifier
> File "/home/alphama/.env/lib/python3.6/site-packages/pyabsa/**init**.py", line 11, in
> from .functional import train_apc, load_sentiment_classifier
> File "/home/alphama/.env/lib/python3.6/site-packages/pyabsa/functional.py", line 12, in
> from pyabsa.dataset_utils import detect_dataset
> File "/home/alphama/.env/lib/python3.6/site-packages/pyabsa/dataset_utils.py", line 9, in
> import git
> File "/home/alphama/.env/lib/python3.6/site-packages/git/**init**.py", line 8, in
> from git.exc import * # @nomove @IgnorePep8
> File "/home/alphama/.env/lib/python3.6/site-packages/git/exc.py", line 10, in
> from git.compat import safe_decode
> File "/home/alphama/.env/lib/python3.6/site-packages/git/compat.py", line 32, in
> from git.types import TBD
> File "/home/alphama/.env/lib/python3.6/site-packages/git/types.py", line 18, in
> from typing_extensions import TypeGuard # noqa: F401
> ImportError: cannot import name 'TypeGuard'

I review the code and I think maybe the 'TypeGuard' in your environment is ambigous due to package conflict.

**Comment by alphamaviwiki** [comment]
I fixed this error since I should install "typing_extensions" alone not typeguard.

**Comment by yangheng95** [comment]
Nice job.

**Comment by yangheng95** [comment]
Nice job.
