### ISSUE TITLE
如果想在已保存模型的基础上重新加载训练，应该怎么修改代码呢？

### ISSUE THREAD

**Issue by SmallSmallQiu** [yangheng95/PyABSA#48]
我使用train_atepc_Chinese.py文件训练了自己的模型，但是发现没办法在已保存模型的基础上继续训练，请问这个问题应该怎么处理呢？

**Comment by yangheng95** [comment]
这个功能实现起来不复杂，我这两天有时间就做

**Comment by SmallSmallQiu** [comment]
> 这个功能实现起来不复杂，我这两天有时间就做

好滴，谢谢你。
我有尝试自己修改代码，不过确实有点难度，麻烦你啦。

**Comment by yangheng95** [comment]
参考：
https://github.com/yangheng95/PyABSA/blob/release/examples/aspect_polarity_classification/train_based_on_checkpoint.py

另外需要重新安装新版pyabsa运行该example

**Comment by yangheng95** [comment]
你好，请问你是否进行过测试或者有什么建议吗？

**Comment by SmallSmallQiu** [comment]
> 你好，请问你是否进行过测试或者有什么建议吗？
我使用ATEPC模型进行测试时发现好像一句号（逗号分隔）的，提取出的对象最多才两个，这个可以改进吗？
我现在只是暂时训练了一份数据集，后续如果有其他发现也会及时反馈到到这里，希望这个项目越来越好。

**Comment by yangheng95** [comment]
> > 你好，请问你是否进行过测试或者有什么建议吗？
> > 我使用ATEPC模型进行测试时发现好像一句号（逗号分隔）的，提取出的对象最多才两个，这个可以改进吗？
> > 我现在只是暂时训练了一份数据集，后续如果有其他发现也会及时反馈到到这里，希望这个项目越来越好。

这个问题应该与模型关系不大，是数据集太小的问题，特别是在多个语言数据集混合时识别可能出现不全的情况。这个问题比较难解决，我们也希望有人能贡献开源或者私有脱敏数据集。
