### ISSUE TITLE
ImportError: cannot import name 'BERT_SPC'  When pyabsa-0.9.2.0

### ISSUE THREAD

**Issue by ChrisMengxl** [yangheng95/PyABSA#49]
ImportError                               Traceback (most recent call last)
<ipython-input-1-b6c414ceb065> in <module>
----> 1 from pyabsa import train_apc, apc_config_handler, ABSADatasetList, APCCheckpointManager
      2 from pyabsa.model_utils import APCModelList
      3 
      4 save_path = 'state_dict'
      5 apc_param_dict_english = apc_config_handler.get_apc_param_dict_english()

~/anaconda3/envs/Py36CUDA110/lib/python3.6/site-packages/pyabsa/__init__.py in <module>
     13 from update_checker import UpdateChecker
     14 
---> 15 from pyabsa.config.apc_config import apc_config_handler
     16 from pyabsa.config.atepc_config import atepc_config_handler
     17 from pyabsa.config.classification_config import classification_config_handler

~/anaconda3/envs/Py36CUDA110/lib/python3.6/site-packages/pyabsa/config/apc_config/apc_config_handler.py in <module>
     10 from pyabsa.tasks.apc.__bert__ import TNet_LF_BERT
     11 from pyabsa.tasks.apc.__glove__ import TNet_LF
---> 12 from pyabsa.tasks.apc.models import BERT_SPC
     13 
     14 # if you find the optimal param set of some situation, e.g., some model on some datasets

ImportError: cannot import name 'BERT_SPC'

**Comment by yangheng95** [comment]
Hello, Can you show me your training code?

**Comment by ChrisMengxl** [comment]
> 
> 
> Hello, Can you show me your training code?

I think it's my fault.Thx

**Comment by yangheng95** [comment]
I reproduce this error, I will fix it soon, please use 0.9.1.0 before I push the fix patch. Thanks

**Comment by yangheng95** [comment]
It's a strange error, I assume this error was introdcued while I pack the code, now I repack and upload a fix patch 0.9.2.1, you can try it and tell me if the problem continues. Thanks!

**Comment by ChrisMengxl** [comment]
> 
> 
> It's a strange error, I assume this error was introdcued while I pack the code, now I repack and upload a fix patch 0.9.2.1, you can try it and tell me if the problem continues. Thanks!

Thank you for your project and timely reply. The problem was fixed in Patch 0.9.2.1.
