### ISSUE TITLE
Aspect Term Extraction Leaderboard

### ISSUE THREAD

**Issue by janpf** [yangheng95/PyABSA#50]
Hi,
Quick suggestion: I just found the APC leaderboard: https://github.com/yangheng95/PyABSA/blob/release/examples/aspect_polarity_classification/leaderboard.md

=> I would suggest adding such a leaderboard for Aspect Term Extraction as well. Results might be really interesting :)

Keep up the great work, I really like it!

**Comment by yangheng95** [comment]
That is a good idea, I will consider it soon
