### ISSUE TITLE
从您给出的地址下载了checkpoint之后需要对代码做什么调整从本地加载下载好的模型呢

### ISSUE THREAD

**Issue by SongShihao731** [yangheng95/PyABSA#55]
国内无法连接到google drive，所以我从百度网盘下载了您的checkpoint 可是不太清楚如何从导入下载好的模型，希望得到您的解答，谢谢您。
例如我需要对 extract_aspects_chinese.py 中部分代码进行怎么的修改呢？
"""
从Google Drive下载提供的预训练模型
aspect_extractor = ATEPCCheckpointManager.get_aspect_extractor(checkpoint='Chinese')
model_path = 'state_dict/lcf_atepc_cdw_apcacc_96.88_apcf1_96.35_atef1_91.2'
"""

**Comment by yangheng95** [comment]
Baidu网盘上的checkpoint不适合1.0以上的版本，我刚刚更新了新版的checkpoint，下载后克隆最新的examples，再将下载的zip文件名， 解压后的路径或者Google drive上的checkpoint名字作为ATEPCCheckpointManager.get_aspect_extractor的checkpoint参数即可

**Comment by SongShihao731** [comment]
谢谢您

**Comment by yangheng95** [comment]
> 谢谢您

我在测试的时候发现了一个问题会导致checkpoint加载失败，更新到v1.0.5可以解决这个问题

**Comment by SongShihao731** [comment]
再次感谢您 : )

**Comment by yangheng95** [comment]
不客气

**Comment by yangheng95** [comment]
I've tested all training and inference examples (passed in all situations), so I close this issue. But any error found could be reported, I would solve the problems as soon as possible.
