### ISSUE TITLE
AttributeError: 'ATEPCConfigManager' object has no attribute 'pretrained_bert_name'

### ISSUE THREAD

**Issue by hitz02** [yangheng95/PyABSA#56]
Error in running aspect extractor training example - 

aspect_extractor = Trainer(config=config,
                           dataset=tshirt,
                           from_checkpoint=checkpoint_path,
                           checkpoint_save_mode=1,
                           auto_device=True
                           )

**Comment by yangheng95** [comment]
Heelo, I am working on testing the examples, can you show me the stacktrace to locate the error reason?

**Comment by hitz02** [comment]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/pyabsa/functional/config/config_manager.py in __getattribute__(self, arg_name)
     60         try:
---> 61             value = super().__getattribute__('args')[arg_name]
     62             args_call_count = super().__getattribute__('args_call_count')

KeyError: 'pretrained_bert_name'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
5 frames
<ipython-input-6-569c3db59397> in <module>()
      4                            from_checkpoint=checkpoint_path,
      5                            checkpoint_save_mode=1,
----> 6                            auto_device=True
      7                            )

/usr/local/lib/python3.7/dist-packages/pyabsa/functional/trainer/trainer.py in __init__(self, config, dataset, from_checkpoint, checkpoint_save_mode, auto_device)
     92             config.model_path_to_save = None
     93 
---> 94         self.train()
     95 
     96     def train(self):

/usr/local/lib/python3.7/dist-packages/pyabsa/functional/trainer/trainer.py in train(self)
    103             self.config.seed = s
    104             if self.checkpoint_save_mode:
--> 105                 model_path.append(self.train_func(self.config, self.from_checkpoint, self.logger))
    106             else:
    107                 # always return the last trained model if dont save trained model

/usr/local/lib/python3.7/dist-packages/pyabsa/core/atepc/training/atepc_trainer.py in train4atepc(opt, from_checkpoint_path, logger)
    352     while not trainer:
    353         try:
--> 354             trainer = Instructor(opt, logger)
    355             if from_checkpoint_path:
    356                 model_path = find_files(from_checkpoint_path, '.model')

/usr/local/lib/python3.7/dist-packages/pyabsa/core/atepc/training/atepc_trainer.py in __init__(self, opt, logger)
     58         }
     59 
---> 60         self.tokenizer = AutoTokenizer.from_pretrained(self.opt.pretrained_bert_name, do_lower_case=True)
     61         bert_base_model = AutoModel.from_pretrained(self.opt.pretrained_bert_name)
     62         processor = ATEPCProcessor(self.tokenizer)

/usr/local/lib/python3.7/dist-packages/pyabsa/functional/config/config_manager.py in __getattribute__(self, arg_name)
     67         except Exception as e:
     68 
---> 69             return super().__getattribute__(arg_name)
     70 
     71     def __setattr__(self, arg_name, value):

AttributeError: 'ATEPCConfigManager' object has no attribute 'pretrained_bert_name'

**Comment by yangheng95** [comment]
OK, this is fixed just now in 1.0.7, which is cause by a rename of a parameter.

**Comment by yangheng95** [comment]
I've tested all training and inference examples (passed in all situations), so I close this issue. But any error found could be reported, I would solve the problems as soon as possible.
