### ISSUE TITLE
extract_aspects_chinese.py 默认在GPU上运行出现的问题

### ISSUE THREAD

**Issue by SongShihao731** [yangheng95/PyABSA#58]
###测试反馈
您好，在您的示例extract_aspects_chinese.py 中代码中：
aspect_extractor = ATEPCCheckpointManager.get_aspect_extractor(checkpoint='lcf_atepc_cdw_apcacc_95.2_apcf1_94.28_atef1_90.49')默认会使用GPU进行处理，但这会导致一个错误 ValueError: could not convert string to float: '[N/A]' 出现问题的文件是auto.py.如果默认不使用GPU而使用CPU则示例代码正常：
aspect_extractor = ATEPCCheckpointManager.get_aspect_extractor(checkpoint='lcf_atepc_cdw_apcacc_95.2_apcf1_94.28_atef1_90.49',auto_device=False)
本机运行环境有 2060，CUDA也安装调试完成。
感谢您高频率的维护代码~ cool

**Comment by yangheng95** [comment]
您能贴出代码错误的trace吗

**Comment by SongShihao731** [comment]
![image](https://user-images.githubusercontent.com/74278211/129506163-312ad27c-1838-48dd-a9fb-9ecea52e1de8.png)

**Comment by yangheng95** [comment]
我注意到这个问题了，autocuda的是采用的GitHub上的开源代码，是通过系统命令nvidia-smi查询cuda，可能你的命令配置有问题。能让我看一下你的环境中该命令的输出吗

**Comment by SongShihao731** [comment]
![image](https://user-images.githubusercontent.com/74278211/129506959-ff0df23c-f105-4e57-a650-69d3dca8181b.png)

**Comment by yangheng95** [comment]
这个输出确实不大一样，不清楚是否是新版本导致的问题。我发布一个补丁，让您可以直接手动指定cuda device，可以吗？
如果确实是nvidia查询结果改版的话，我后面会修改autocuda源码

**Comment by SongShihao731** [comment]
麻烦您了

**Comment by yangheng95** [comment]
我发不了1.0.7.1版本，宁可以使用auto_deivce='cuda'指定GPU，请反馈一下测试结果，谢谢！

**Comment by SongShihao731** [comment]
代码显示可以正常运行了，感谢您
![image](https://user-images.githubusercontent.com/74278211/129515309-05b9e283-fb6c-4fad-a9e0-169410ec0e90.png)

**Comment by yangheng95** [comment]
除此之外您还可以加载完模型后手动切换device： https://github.com/yangheng95/PyABSA/blob/release/examples/common_usages/change_loading_device.py

**Comment by SongShihao731** [comment]
谢谢~
