### ISSUE TITLE
About the Chinese dataset.

### ISSUE THREAD

**Issue by gaozhengjie** [yangheng95/PyABSA#6]
I found that there is a Chinese dataset in your repo, but why isn't the Chinese dataset used in your paper *`LCF: A Local Context Focus Mechanism for Aspect-Based Sentiment Classification`*? I want to know where did you get this Chinese data set. Could you disclose it? Because I find that there will always be some differences in the number of the four Chinese data sets, I want to know from the source what the original data set looks like. Thank you!

**Comment by yangheng95** [comment]
The paper was published last August, and the dataset was recently processed.

This original dataset are available at [Learning multi-grained aspect target sequence for Chinese sentiment analysis](https://www.sciencedirect.com/science/article/pii/S0950705118300972), and some samples with obvious errors were filtered during processing, such as those with the aspect  "0".

**Comment by gaozhengjie** [comment]
OK, thank you very much for your answer. @yangheng95
