### ISSUE TITLE
Checkpoints for Glove-Based and different Models

### ISSUE THREAD

**Issue by kunalverma75** [yangheng95/PyABSA#63]
Hey, Thanks for creating such an amazing library. May I know if there are pretrained checkpoints or models available for Glove based APC models. If not I would be training them and would like to share the checkpoints as well

**Comment by yangheng95** [comment]
Hi, we dont provide GloVe based checkpoint yet, we will be appreciated for your contribution, e.g., shares of checkpoint and test code in many situations to help stabilize the code.

**Comment by kunalverma75** [comment]
Thanks, will try to contribute to the project
