### ISSUE TITLE
How to use Trained  APC model for inference

### ISSUE THREAD

**Issue by kunalverma75** [yangheng95/PyABSA#64]
I trained an APC model and now want to use the sentiment classifier. Can you point me how to load the sentiment classifier. Could not find examples of it. For example if checkpoint save is off and when checkpoint save is on.

**Comment by yangheng95** [comment]
Hi,
If you save the checkpoint, you can just use your checkpoint by assign the checkpoint to your checkpoint directory
https://github.com/yangheng95/PyABSA/blob/dc929a2a3e2cde9490723dfa1f622e6762bcfa5f/examples/aspect_polarity_classification/sentiment_inference.py#L18
```
checkpoint='checkpoint name, or path or zipped checkpoint archive'
```
or if not save, the trainer will return a sentiment classifier as well, just use the returned sentiment classifier for inference.

https://github.com/yangheng95/PyABSA/blob/dc929a2a3e2cde9490723dfa1f622e6762bcfa5f/examples/aspect_polarity_classification/train_apc.py#L32

**Comment by kunalverma75** [comment]
Yeah its working, I think there is some problem with Google Colab or just mine as it was not saving the checkpoints earlier. On Kaggle notebooks and on local machine everything worked fine.

**Comment by Astudnew** [comment]
> Yeah its working, I think there is some problem with Google Colab or just mine as it was not saving the checkpoints earlier. On Kaggle notebooks and on local machine everything worked fine.

please could you share with complete example/code of using APC on google colab or kaggel?
