### ISSUE TITLE
from transformers.models.bert.modeling_bert import BertPooler and other import paths not found or outdated

### ISSUE THREAD

**Issue by TheEliasBe** [yangheng95/PyABSA#65]
Hi, thanks for your code!
I found that some import paths for the `transformers` package don't seem to work. I've updated them in the project and could do a PR from my work.

Examples:
`from transformers.models.bert.modeling_bert import BertPooler`
to
`from transformers.modeling_bert import BertPooler`

Maybe this is just an issue on my side?

**Comment by yangheng95** [comment]
Maybe you can update transformers to 4.5 or upper, that could solve you poblem. But if the problem continues you can comment here, I will help you.

**Comment by TheEliasBe** [comment]
Yes, I noted this as well. The environment we're using still had a very outdated version installed. Sorry for bothering you.

**Comment by yangheng95** [comment]
Please feel free do PR or report errors, so that we can improve this work together.
