### ISSUE TITLE
Training taking too much time when evaluation begins

### ISSUE THREAD

**Issue by kunalverma75** [yangheng95/PyABSA#69]
I am training multilingual models using your library, some of the key points observed during training:

1. Training takes too much time in epochs where evaluation starts
2. If we set (evaluation_begin>num_epochs) model does not save checkpoint after training

Attaching a screenshot of the training 
![image](https://user-images.githubusercontent.com/36312861/131383494-cd694eb2-0c12-456e-8f71-d6deb7f97a58.png)

**Comment by yangheng95** [comment]
Hello, 
yes, both are expected behaviours, and evaluation is very expensive. the evalute_begin should be in (0, num_epoch-1), and we can set a large eval span to save time, e.g., config.log_step=200

**Comment by kunalverma75** [comment]
Ok thanks a lot for clarifications!
