### ISSUE TITLE
代码中模型与论文中有偏差

### ISSUE THREAD

**Issue by yunbujian** [yangheng95/PyABSA#72]
![52ebd50f6ccc9d813cbd151630fa933](https://user-images.githubusercontent.com/59611117/131605041-2a743540-4344-46fb-9962-d63adc3e619c.png)

在LCF（2018年）的那篇论文中，论文中的CDM后面和concat之后都有MHSA模块，但是代码中并没有，请问应该以哪个为准呢？

**Comment by yangheng95** [comment]
请以代码为准。代码经过了很多次迭代，不仅模型结构有变化，数据处理这些对效果影响较大的部分也都进行了重构，所以效果会与论文不同。另外这篇早期论文统计结果的时候不严谨，所以结果都偏高。
