### ISSUE TITLE
NoneType Error while doing 5-fold Cross-validation

### ISSUE THREAD

**Issue by kunalverma75** [yangheng95/PyABSA#73]
I am training a multilingual model on a custom dataset. While training if cross-validation is not set, everything works. But when I set the parameter 

> cross_validate_fold = 5
I am getting the error below after the first fold of training. 

AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/.conda/envs/env_Kunal/lib/python3.9/site-packages/torch/serialization.py in _check_seekable(f)
    307     try:
--> 308         f.seek(f.tell())
    309         return True

AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-6-a3d2087f4a12> in <module>
      7 apc_config_multilingual.cross_validate_fold = 5
      8 datasets_path = '/home/development/kunalv/env_testing/MTP_Kunal/Dutch'  # file or dir are acceptable for 'datasets_path'
----> 9 sent_classifier = Trainer(config=apc_config_multilingual,
     10                           dataset=datasets_path,
     11                           #from_checkpoint="/home/development/kunalv/env_testing/MTP_Kunal/checkpoints/fast_lcf_bert_acc_83.6_f1_65.2/",

~/.conda/envs/env_Kunal/lib/python3.9/site-packages/pyabsa/functional/trainer/trainer.py in __init__(self, config, dataset, from_checkpoint, checkpoint_save_mode, auto_device)
    101             config.model_path_to_save = None
    102 
--> 103         self.train()
    104 
    105     def train(self):

~/.conda/envs/env_Kunal/lib/python3.9/site-packages/pyabsa/functional/trainer/trainer.py in train(self)
    113             config.seed = s
    114             if self.checkpoint_save_mode:
--> 115                 model_path.append(self.train_func(config, self.from_checkpoint, self.logger))
    116             else:
    117                 # always return the last trained model if dont save trained model

~/.conda/envs/env_Kunal/lib/python3.9/site-packages/pyabsa/core/apc/training/apc_trainer.py in train4apc(opt, from_checkpoint_path, logger)
    493     load_checkpoint(trainer, from_checkpoint_path)
    494 
--> 495     return trainer.run()

~/.conda/envs/env_Kunal/lib/python3.9/site-packages/pyabsa/core/apc/training/apc_trainer.py in run(self)
    466         lca_criterion = nn.CrossEntropyLoss()
    467         self._reset_params()
--> 468         return self._train(criterion, lca_criterion)
    469 
    470 

~/.conda/envs/env_Kunal/lib/python3.9/site-packages/pyabsa/core/apc/training/apc_trainer.py in _train(self, criterion, lca_criterion)
    164         self.prepare_dataloader(self.train_set)
    165         if self.val_dataloaders:
--> 166             return self._k_fold_train_and_evaluate(criterion, lca_criterion)
    167         else:
    168             return self._train_and_evaluate(criterion, lca_criterion)

~/.conda/envs/env_Kunal/lib/python3.9/site-packages/pyabsa/core/apc/training/apc_trainer.py in _k_fold_train_and_evaluate(self, criterion, lca_criterion)
    384                         iterator.postfix = postfix
    385                         iterator.refresh()
--> 386             self.model = torch.load(find_file(save_path, 'model')).to(self.opt.device)
    387             max_fold_acc, max_fold_f1 = self._evaluate_acc_f1(self.test_dataloader)
    388             if max_fold_acc > max_fold_acc_k_fold:

~/.conda/envs/env_Kunal/lib/python3.9/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    592         pickle_load_args['encoding'] = 'utf-8'
    593 
--> 594     with _open_file_like(f, 'rb') as opened_file:
    595         if _is_zipfile(opened_file):
    596             # The zipfile reader is going to advance the current file position.

~/.conda/envs/env_Kunal/lib/python3.9/site-packages/torch/serialization.py in _open_file_like(name_or_buffer, mode)
    233             return _open_buffer_writer(name_or_buffer)
    234         elif 'r' in mode:
--> 235             return _open_buffer_reader(name_or_buffer)
    236         else:
    237             raise RuntimeError(f"Expected 'r' or 'w' in mode but got {mode}")

~/.conda/envs/env_Kunal/lib/python3.9/site-packages/torch/serialization.py in __init__(self, buffer)
    218     def __init__(self, buffer):
    219         super(_open_buffer_reader, self).__init__(buffer)
--> 220         _check_seekable(buffer)
    221 
    222 

~/.conda/envs/env_Kunal/lib/python3.9/site-packages/torch/serialization.py in _check_seekable(f)
    309         return True
    310     except (io.UnsupportedOperation, AttributeError) as e:
--> 311         raise_err_msg(["seek", "tell"], e)
    312     return False
    313 

~/.conda/envs/env_Kunal/lib/python3.9/site-packages/torch/serialization.py in raise_err_msg(patterns, e)
    302                                 + " Please pre-load the data into a buffer like io.BytesIO and"
    303                                 + " try to load from it instead.")
--> 304                 raise type(e)(msg)
    305         raise e
    306 

AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.

**Comment by yangheng95** [comment]
Hi,
Thanks for your report, I will check it.

**Comment by yangheng95** [comment]
The error is located, I will release a patch to fix it soon.

**Comment by kunalverma75** [comment]
Thank you so much for so fast fixes!

**Comment by yangheng95** [comment]
Please install the pre-release version and run again:
```
pip install pyabsa==1.1.12a0
```
Please tell me if there is any problem or bug, thanks!

**Comment by kunalverma75** [comment]
Sure checking it

**Comment by kunalverma75** [comment]
Yes, The issue is fixed. Thanks a lot again!

**Comment by yangheng95** [comment]
Thanks for your contribution, I will merge this fix patch into next release version.
