### ISSUE TITLE
interrupted by signal 9: SIGKILL

### ISSUE THREAD

**Issue by htthYjh** [yangheng95/PyABSA#74]
当我执行 train_atepc_multilingual.py 这个文件的时候，任务总是被kill掉。使用的是12G显存的RTX 2080 Ti GPU。 
根据前辈的经验：将batch_size 由16改成4还是未成功，能在训练任务提供一点经验指导么。谢谢！
异常日志:
Version 1.1.7 of pyabsa is outdated. Version 1.1.9 was released Wednesday August 25, 2021.
already exists
******************** Release Note of Version 1.1.9 ********************
1.	Fix a problem in BERT-ATEPC model
******************** Release Note of Version 1.1.8 ********************
1.	Fix a problem may cuase checkpoint saving failure
You can update via pip: pip install -U pyabsa
multilingual dataset is integrated dataset from: https://github.com/yangheng95/ABSADatasets
Seems datasets downloaded /workspace/osint_dev/PyABSA/examples/aspect_term_extraction/integrated_datasets
Downloading: 100%|██████████| 672M/672M [01:00<00:00, 11.1MB/s]
Some weights of the model checkpoint at bert-base-multilingual-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Using bos_token, but it is not set yet.
Using eos_token, but it is not set yet.
100%|██████████| 10557/10557 [00:32<00:00, 323.54it/s, convert examples to features]
100%|██████████| 6607/6607 [00:21<00:00, 302.94it/s, convert examples to features]

Process finished with exit code 137 (**interrupted by signal 9: SIGKILL**)

**Comment by yangheng95** [comment]
This is a OOM error (RAM, not cuda memory). The multilingual dataset is very large, I recommend you to  fit your own dataset based on our multilingual checkpoint.

**Comment by yangheng95** [comment]
I trained the model using 32G RAM, but I dont test it on lower RAM

**Comment by yangheng95** [comment]
> I trained the model using 32G RAM, but I dont test it on lower RAM.
Refer https://github.com/yangheng95/PyABSA/blob/release/examples/aspect_term_extraction/train_atepc_based_on_checkpoint.py to train using out checkpoints

**Comment by htthYjh** [comment]
I want to run extract_aspects_multilingual.py and download checkpoint of 'Multilingual' and train based on it ,but fail to download:

_# 从Google Drive下载提供的预训练模型
aspect_extractor = ATEPCCheckpointManager.get_aspect_extractor(checkpoint='Multilingual')

atepc_result = aspect_extractor.extract_aspect(inference_source=examples,  # list-support only, for current
                                               print_result=True,  # print the result
                                               pred_sentiment=True,  # Predict the sentiment of extracted aspect terms
                                               )_
error log:
    Checkpoint: Multilingual is not found.
![image](https://user-images.githubusercontent.com/22820364/132121223-935f2c13-eb78-4792-8601-6176a1eff67b.png)

**Comment by yangheng95** [comment]
Some training are expensive, we will upload the checkpoint as soon as I can

**Comment by htthYjh** [comment]
Thank you vary mach

**Comment by yangheng95** [comment]
Hello, 
I upload the multilingual checkpoint, please try.

**Comment by htthYjh** [comment]
Can you provide a link to the shared file? I want to download it directly through the link. The execution code still cannot be downloaded. It may be due to the network.

**Comment by yangheng95** [comment]
https://drive.google.com/file/d/1vDr85mflnZofpzIsnwffgQVwqE1U0QoO/view?usp=sharing

**Comment by htthYjh** [comment]
thank you very much
