### ISSUE TITLE
关于使用中文数据集进行训练，召回率过低的问题

### ISSUE THREAD

**Issue by fathouse** [yangheng95/PyABSA#8]
我使用了其中的中文数据集，并将模型替换成了Bert-chinese，但是结果却总是Acc>95,F1<60,请问这种情况如何解决？

**Comment by fathouse** [comment]
camera:
batch_size:16
max_test_acc_overall:95.6896551724138
max_f1_overall:63.26241933988123
batch_size:32
max_test_acc_overall:95.0
max_f1_overall:62.65156587737234

car:
batch_size:16
max_test_acc_overall:97.19298245614036
max_f1_overall:64.27432216905902
batch_size:32
max_test_acc_overall:97.19298245614036
max_f1_overall:64.27432216905902
notebook:
batch_size:16
max_test_acc_overall:92.90322580645162
max_f1_overall:61.1015911872705
batch_size:32
max_test_acc_overall:92.25806451612904
max_f1_overall:60.698241560775244

phone:
batch_size:16
max_test_acc_overall:96.63093415007657
max_f1_overall:64.07987611639298
batch_size:32
max_test_acc_overall:96.47779479326188
max_f1_overall:63.91524621082011

**Comment by fathouse** [comment]
@yangheng95

**Comment by yangheng95** [comment]
应该是这里的原因[https://github.com/yangheng95/LC-ABSA/blob/7285a57037b9b497c626b742a6a8c269ff3d482d/train_apc.py#L189](https://github.com/yangheng95/LC-ABSA/blob/7285a57037b9b497c626b742a6a8c269ff3d482d/train_apc.py#L189)，我现在没有时间修改，近几天会更新，请耐心等待修复

**Comment by fathouse** [comment]
谢谢您，我照着看看
