### ISSUE TITLE
[Bug Report] Runtime Error - Division by Zero on custom dataset

### ISSUE THREAD

**Issue by kunalverma75** [yangheng95/PyABSA#80]
**Bug Description**
The model is giving zerodivision error on multilingual custom dataset (I have provided the file as well). I don't see any special characters in the file as well.
**Code**
apc_config_multilingual = APCConfigManager.get_apc_config_multilingual()
apc_config_multilingual.seed = 52
apc_config_multilingual.model = APCModelList.LCFS_DUAL_BERT
apc_config_multilingual.evaluate_begin = 0
apc_config_multilingual.log_step=50
apc_config_multilingual.cross_validate_fold=-1
apc_config_multilingual.learning_rate = 3e-5
apc_config_multilingual.batch_size= 16
apc_config_multilingual.num_epoch = 8
apc_config_multilingual.auto_evaluate = False
datasets_path = "train.apc.txt"
sent_classifier = Trainer(config=apc_config_multilingual,
                                    dataset=datasets_path,
                                    checkpoint_save_mode=1,
                                    auto_device=True)

**Whole Stack Trace**
Waring, auto_evaluate=True, however cannot find test set using for evaluating!
loading: train.apc.txt
  0%|          | 0/1773 [00:00<?, ?it/s, building word indices...]Using bos_token, but it is not set yet.
Using eos_token, but it is not set yet.
 17%|█▋        | 295/1773 [00:04<00:20, 72.38it/s, building word indices...]
division by zero
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/pyabsa/core/apc/dataset_utils/apc_utils.py in get_syntax_distance(text_raw, aspect, tokenizer, opt)
    237     try:
--> 238         raw_tokens, dist, max_dist = calculate_dep_dist(text_raw, aspect)
    239     except Exception as e:

8 frames
/usr/local/lib/python3.7/dist-packages/pyabsa/core/apc/dataset_utils/apc_utils.py in calculate_dep_dist(sentence, aspect)
    424                 flag = 0
--> 425         dist[i] = sum / len(terms)
    426         text[i] = word.text

ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-29-86fbb80c14ac> in <module>()
     14                                     dataset=datasets_path,
     15                                     checkpoint_save_mode=1,
---> 16                                     auto_device=True)
     17                                     #model_path_to_save="/content"
     18 #model,path = sent_classifier.RUN()

/usr/local/lib/python3.7/dist-packages/pyabsa/functional/trainer/trainer.py in __init__(self, config, dataset, from_checkpoint, checkpoint_save_mode, auto_device)
    101             config.model_path_to_save = None
    102 
--> 103         self.train()
    104 
    105     def train(self):

/usr/local/lib/python3.7/dist-packages/pyabsa/functional/trainer/trainer.py in train(self)
    113             config.seed = s
    114             if self.checkpoint_save_mode:
--> 115                 model_path.append(self.train_func(config, self.from_checkpoint, self.logger))
    116             else:
    117                 # always return the last trained model if dont save trained model

/usr/local/lib/python3.7/dist-packages/pyabsa/core/apc/training/apc_trainer.py in train4apc(opt, from_checkpoint_path, logger)
    488 
    489     # in case of handling ConnectionError exception
--> 490     trainer = Instructor(opt, logger)
    491     load_checkpoint(trainer, from_checkpoint_path)
    492 

/usr/local/lib/python3.7/dist-packages/pyabsa/core/apc/training/apc_trainer.py in __init__(self, opt, logger)
     42             self.tokenizer = AutoTokenizer.from_pretrained(self.opt.pretrained_bert, do_lower_case=True)
     43 
---> 44             self.train_set = ABSADataset(self.opt.dataset_file['train'], self.tokenizer, self.opt)
     45             if 'test' in self.opt.dataset_file:
     46                 self.test_set = ABSADataset(self.opt.dataset_file['test'], self.tokenizer, self.opt)

/usr/local/lib/python3.7/dist-packages/pyabsa/core/apc/dataset_utils/data_utils_for_training.py in __init__(self, fname, tokenizer, opt)
     32             label_set.add(polarity)
     33 
---> 34             prepared_inputs = prepare_input_for_apc(opt, tokenizer, text_left, text_right, aspect)
     35 
     36             text_raw = prepared_inputs['text_raw']

/usr/local/lib/python3.7/dist-packages/pyabsa/core/apc/dataset_utils/apc_utils.py in prepare_input_for_apc(opt, tokenizer, text_left, text_right, aspect)
    199 
    200     if 'lcfs' in opt.model_name or 'ssw_s' in opt.model_name or opt.use_syntax_based_SRD:
--> 201         syntactical_dist, _ = get_syntax_distance(text_raw, aspect, tokenizer, opt)
    202     else:
    203         syntactical_dist = None

/usr/local/lib/python3.7/dist-packages/pyabsa/core/apc/dataset_utils/apc_utils.py in get_syntax_distance(text_raw, aspect, tokenizer, opt)
    239     except Exception as e:
    240         print(e)
--> 241         raise RuntimeError('Are you using syntax-based SRD on a dataset containing Chinese text?')
    242 
    243     raw_tokens.insert(0, tokenizer.bos_token)

RuntimeError: Are you using syntax-based SRD on a dataset containing Chinese text
[train.apc.txt](https://github.com/yangheng95/PyABSA/files/7218353/train.apc.txt)
?

**Comment by yangheng95** [comment]
Received, Test and Reply later.

**Comment by yangheng95** [comment]
![image](https://user-images.githubusercontent.com/51735130/134527895-9ccac890-2afa-4b3f-ab65-32f3806e0d31.png)

I see a empty aspect in the dataset which triggered this error. BTW, I notice your dataset is nor English, I suppose you can use the corresponding model in spaCy. You can revise the model loading code, or I can release a patch to enable alternative SpaCy models.

**Comment by kunalverma75** [comment]
Oh Thanks a lot. I am trying some techniques for improving multilingual performance hence I created custom datasets with a mix of english and words from other languages (hence the dataset is not entirely english).
