### ISSUE TITLE
[Bug Report] extract_aspect.self._extract()

### ISSUE THREAD

**Issue by FrancisDacian** [yangheng95/PyABSA#88]
when the length of the prediction dataset is longer than 128, function `extract_aspect` can only return the unique first 128(bs) prediction results rather than the length of the prediction dataset.
Eg. 
length of the prediction dataset: 1000
expected result: 1000 corresponding results.
actual return: 1000 results contains only 128 unique results.
Thru checking the code, from `extraction_res, sentence_res = self._extract(inference_source)` line of code, returns are not expected, I will say there are bugs in function `self._extract`

**Comment by yangheng95** [comment]
Received, will review it

**Comment by FrancisDacian** [comment]
change the 
`all_tokens[i]`
to
`all_tokens[i+(self.opt.eval_batch_size*i_batch)]`
in the loop `for i, i_ate_logits in enumerate(ate_logits):`
can be helpful.

**Comment by yangheng95** [comment]
Thanks very much, I will test and fix it soon

**Comment by FrancisDacian** [comment]
just checked the result with my dataset and pull a request to solve it.
