### ISSUE TITLE
About the method of data annotation

### ISSUE THREAD

**Issue by ccscute** [yangheng95/PyABSA#9]
First of all, respect your work. I want to ask about your data annotation method. I have some texts in specific fields (Chinese)  that I want to apply for ABSA.
I also saw your other article, and I also want to ask about how to annotate your [data.](https://github.com/yangheng95/LCF-ATEPC)
Can you tell me what software or method you use?
Just like '$T$', B I O，Word segmentation tool 
Thank you！

**Comment by yangheng95** [comment]
Unfortunately, there is no tool that can automatically preprocess and annotate the datasets. I preprocess the datasets by coding by myself.

**Comment by ccscute** [comment]
Ha ha, thank you for your reply！Your work is great！
